// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrainDocument } from "./TrainDocument";

/**
 * What reading a geartrain came to: the document, and whether reading it
 * changed it.
 */
export type Imported = { document: TrainDocument, 
/**
 * Whether the train was relieved on the way in — a toggle the file had
 * given that the graph cannot honour, turned back automatic (the module
 * documentation, *What is adjusted on import*). The values are the
 * file's own throughout.
 */
adjusted: boolean, };
