// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Train } from "../core/Train";

/**
 * A geartrain as it is exchanged: a name, and the train's inputs. The
 * format it is written at is the file's, stated by [`to_toml`] and held by
 * [`from_toml`], and not a field of the document.
 */
export type TrainDocument = { 
/**
 * The tab's name. Not unique, per the specification.
 */
name: string, train: Train, };
