// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the train is used, which is what turns a ratio into a tooth count.
 */
export type Actuation = { "intermittent": { 
/**
 * Output sweep per actuation, degrees.
 */
range_degrees: number, actuations: number, } } | { "continuous": { 
/**
 * Percentage of the peak input speed.
 */
operating_percent: number, runtime_hours: number, } };
