// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanetaryShaft } from "./PlanetaryShaft";

/**
 * Which shaft drives and which is held.
 *
 * **This is an addition to the specification's field list** (docs/rationale.md#additions-to-the-specifications-field-list). The
 * specification names only "Driven By", which picks one shaft of three and
 * leaves the arrangement undetermined: a sun-driven set behaves quite
 * differently with the ring held than with the carrier held. Naming the held
 * shaft as well is what makes the six modes of docs/reference.md#planetary-sets reachable.
 */
export type Arrangement = { input: PlanetaryShaft, fixed: PlanetaryShaft, };
