// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A value the solver can work out for you, or that you can set yourself.
 *
 * The specification has about a dozen of these — profile shift, altered
 * addendum, centre distance, face width — all with the same shape: a toggle,
 * and a field that is locked while the toggle is on. One generic covers them
 * all (`docs/rationale.md#inputs-are-the-only-state`).
 *
 * `manual` is kept even while `auto` is set, so turning automatic *off* leaves
 * the field showing the last value rather than jumping to a stale one. It is
 * the UI's job to seed `manual` from the solved value when the toggle flips.
 */
export type Auto<T> = { auto: boolean, manual: T, };
