// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bound } from "./Bound";
import type { LayoutReport } from "./LayoutReport";

/**
 * **One axis's report**: how its planets lay out, where it is replicated.
 */
export type AxisReport = { 
/**
 * The layout, its `axis` the graph's number for it.
 */
layout: LayoutReport | null, 
/**
 * **The counts the axis may be replicated to** ([`shape::Axis::count`]),
 * [`crate::auto::COUNT`]. Sent so the panel holds the box to the core's
 * bound rather than one written beside it.
 */
count: Bound, };
