// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AxisBody } from "./AxisBody";

/**
 * **An axis, and what turns about it.**
 */
export type AxisGroup = { axis: number, 
/**
 * The body that carries it round, where one does — a planet's axis.
 */
carried_by: number | null, 
/**
 * How many copies stand round the carrier.
 */
count: number, 
/**
 * The bodies on it, in the graph's order.
 */
bodies: Array<AxisBody>, };
