// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AxisBody } from "./AxisBody";

/**
 * **An axis, and what turns about it.**
 */
export type AxisGroup = { axis: number, 
/**
 * The body that carries it round — a planet's axis's carrier — or
 * ground, 0, where none does: the graph's own encoding
 * ([`super::shape::Axis::carried_by`]).
 */
carried_by: number, 
/**
 * How many copies stand round the carrier.
 */
count: number, 
/**
 * The bodies on it, in the graph's order.
 */
bodies: Array<AxisBody>, };
