// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One body on an axis: the gears fixed to it, the axes it carries round.
 */
export type AxisBody = { body: number, members: Array<number>, carries: Array<number>, };
