// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An axis gears turn about: fixed in ground, or carried round another axis
 * by a shaft — a planet's, riding the carrier.
 */
export type Axis = { 
/**
 * The shaft whose frame this axis stands still in, where it is not
 * ground's: a carrier. `None` is an axis fixed in ground.
 */
carried_by: number | null, 
/**
 * How many times this axis, its shafts and their gears are replicated
 * about the axis it is carried round — `N` planets. One elsewhere.
 */
count: number, };
