// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayoutReport } from "./LayoutReport";

/**
 * **One axis's report**: how its planets lay out, where it is replicated.
 */
export type AxisReport = { 
/**
 * The layout, its `axis` the graph's number for it.
 */
layout: LayoutReport | null, };
