// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Angular backlash at one gear, in degrees.
 */
export type Backlash = { nominal: number, minimum: number, maximum: number, };
