// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much a number is worth.
 *
 * Ordered weakest-last so a UI can sort or colour by it, and so the worst
 * basis in a material is `max()` over its properties.
 */
export type Basis = "overridden" | "datasheet" | "derived" | "chart" | "estimated";
