// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Measurement **between** pins or balls, for a ring.
 *
 * The internal counterpart of [`OverPins`]. The distinction is not cosmetic: on
 * an external gear the pins stand proud and you measure *across their outer
 * surfaces*, so the pin diameter **adds**; inside a ring they seat in opposing
 * spaces and you measure *between their inner surfaces*, so it **subtracts**.
 */
export type BetweenPins = { pin_diameter: number, 
/**
 * Nominal measurement, mm.
 */
nominal: number, 
/**
 * Radius of the pin centres.
 */
pin_centre_radius: number, 
/**
 * Radius at which the pin touches the flank.
 */
contact_radius: number, 
/**
 * Space for the tolerance band once JGMA 1103-01 is available (docs/reference.md#metrology), as on
 * [`OverPins`].
 */
limits: [number, number] | null, };
