// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One end of a body: the part it is listed on.
 */
export type BodyEnd = { part: number, };
