// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A body of the train on one of the shape's axes. The `i`th listed is
 * slot `i + 1` of the wiring; ground is slot 0 and is not listed.
 */
export type BodyOn = { 
/**
 * The train's body — one number across the train, ground being 0 —
 * that turns on this axis. Its position in the list is the shape's
 * own numbering of it for the kinematics, ground 0 and the first
 * listed 1.
 */
body: number, axis: number, };
