// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Exact } from "./Exact";
import type { Term } from "./Term";

/**
 * One body of the train's motion, for the front end.
 */
export type BodyReport = { body: number, 
/**
 * **A body a train may be addressed at**: one some part has as a
 * port, which is every body but a replicated one — a planet orbits
 * and nothing can be attached to it.
 */
port: boolean, 
/**
 * **Held by the train** — ground under another name — so no case can
 * say anything of it. A port and held is a body the picker does not
 * offer; a port and not held is what a load can enter by.
 */
held: boolean, 
/**
 * Turns per turn of what is driven — the whole answer where it is one
 * answer, and the particular part of it where it is a family.
 */
speed: Exact, 
/**
 * **The rest of a family**: one term per free body this one depends
 * on, *coefficient turns per turn of that body*. Empty where the
 * answer is one answer.
 */
terms: Array<Term>, };
