// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BodyEnd } from "./BodyEnd";
import type { Exact } from "./Exact";
import type { Term } from "./Term";

/**
 * One body of the train's motion, for the front end.
 */
export type BodyReport = { body: number, 
/**
 * Every stage it is listed on, and what it is there — a slot that is
 * no port too, a planet's.
 */
ends: Array<BodyEnd>, 
/**
 * Turns per turn of what is driven — the whole answer where it is one
 * answer, and the particular part of it where it is a family.
 */
speed: Exact, 
/**
 * **The rest of a family**: one term per free body this one depends
 * on, *coefficient turns per turn of that body*. Empty where the
 * answer is one answer.
 */
terms: Array<Term>, };
