// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **What a body is**, structurally — which is the only thing `gear-core` may
 * say about it, a name being a word the application shows.
 *
 * It was a `&'static str` — `"sun"`, `"crank"`, `"wobble"` — which is English
 * in the core (rule 2) and a *role* rather than a fact. A general epicyclic
 * stage has no sun; it has central members and carriers, and this is the list
 * that survives that: ground, the body a member spins with, or a carrier —
 * a frame that is nobody's body. The front end names the second after the
 * member (`gearNumber`) and the third with its own word, as it already does.
 */
export type BodyLabel = { "kind": "ground" } | { "kind": "member", member: number, } | { "kind": "carrier", index: number, };
