// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BodyLabel } from "./BodyLabel";

/**
 * One end of a body: the stage it is listed on, and what it is there.
 */
export type BodyEnd = { stage: number, label: BodyLabel, };
