// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A bound on one input. `None` on a side that is genuinely unbounded.
 *
 * Exclusivity matters and is carried rather than assumed: a module of exactly
 * zero collapses every radius, so `m > 0`, while an addendum exactly at its
 * floor is a legal (if pointless) tooth.
 */
export type Bound = { min: number | null, max: number | null, exclusive_min: boolean, exclusive_max: boolean, };
