// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A quantity held for each **kind** of load case — the one two-valued shape
 * left once the cases themselves became a list, and it is about allowables
 * rather than loads: a material has two, so a rating has two things to be
 * judged against, however many loads there are.
 *
 * Built through [`ByKind::of`] for the same reason [`Directional`] is: there is
 * no path by which one kind is answered and the other not.
 */
export type ByKind<T> = { ultimate: T, fatigue: T, };
