// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadFreedom } from "./LoadFreedom";

/**
 * One figure of one load of a case: what a panel names when it toggles it.
 */
export type CaseFreedom = { load: number, which: LoadFreedom, };
