// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which allowable a load case is judged against.
 *
 * **This is the whole of what a kind decides in the core.** An ultimate load
 * has to be survived once, so the ultimate figure is the right bar; a fatigue
 * load has to be survived for its duty, so the fatigue figure is — and only a
 * fatigue case has a duty to count cycles over, or a drive to reverse. Rating
 * a peak against a fatigue allowable asks the wrong question, and it is what
 * this crate did before the two kinds existed. Everything else about a load
 * case — where it enters, what holds it, how big it is — is the same question
 * for either kind, and a kind is otherwise a preset and a vocabulary, as
 * [`PairKind`] is over a pair.
 */
export type CaseKind = "ultimate" | "fatigue";
