// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BodyRole } from "./BodyRole";

/**
 * One body of the train in one load case.
 */
export type CaseBody = { at: number, role: BodyRole, 
/**
 * rpm; `None` on a body that is held, which has none to report.
 */
speed: number | null, 
/**
 * The external torque on it, N·m: the load at a loaded port, the
 * reaction at a held one, nought on a free body.
 */
torque: number, };
