// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShaftLabel } from "./ShaftLabel";
import type { ShaftRef } from "./ShaftRef";
import type { ShaftRole } from "./ShaftRole";

/**
 * One shaft of the train in one load case.
 */
export type CaseShaft = { at: ShaftRef, label: ShaftLabel, role: ShaftRole, 
/**
 * rpm; `None` on a shaft that is held, which has none to report.
 */
speed: number | null, 
/**
 * The external torque on it, N·m: the load at a loaded port, the
 * reaction at a held one, nought on a free shaft.
 */
torque: number, };
