// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Sinusoid } from "./Sinusoid";

/**
 * The centre distance an eccentric mesh wants, around one revolution.
 *
 * Sampled at the **tooth positions**, one per tooth: that is where contact
 * actually is, and it is where the discrete shifts the gear was cut at land
 * exactly on the continuous `x(θ)` the mechanism is tracking. No sample count
 * to choose, and nothing interpolated.
 */
export type CentreProfile = { 
/**
 * The zero-backlash centre distance at each tooth position, mm, starting at
 * `θ = 0` and going round.
 */
commanded: Array<number>, 
/**
 * Smallest and largest of the above, mm.
 */
range: [number, number], 
/**
 * The best-fit pure sinusoid.
 *
 * What a **simple eccentric or crank** can actually deliver. `a_w(θ)` is
 * not sinusoidal even though `x(θ)` is — it passes through `inv⁻¹` and a
 * cosine on the way — so a mechanism built that way tracks this instead,
 * and the difference is the next two fields.
 *
 * Exact rather than fitted: the samples are equally spaced, so the first
 * Fourier coefficient *is* the least-squares sinusoid, with no optimiser
 * and no starting guess.
 */
sinusoid: Sinusoid, 
/**
 * The largest departure of the ideal from that sinusoid, mm of centre
 * distance.
 */
sinusoid_error: number, 
/**
 * What that departure costs, as backlash at the pitch circle, mm —
 * smallest and largest around the revolution.
 *
 * **The number an engineer building the mechanism actually needs**, and the
 * reason the centre-distance error is not the end of the story. Negative is
 * not slack but *interference*: the mechanism has brought the axes closer
 * than the teeth at that position allow.
 */
sinusoid_backlash: [number, number], };
