// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **Each pair of axes that mesh, and every mesh at that spacing.**
 */
export type Centre = { 
/**
 * The distance, by the graph's index.
 */
distance: number, axes: [number, number], 
/**
 * Every mesh across it, in the graph's order.
 */
meshes: Array<number>, };
