// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Note } from "./Note";

/**
 * Guard rails applied to degenerate input.
 *
 * These encode no physics. They stop input that cannot describe a real gear
 * from producing a NaN or a self-intersecting outline. Every guard that fires
 * appends a human-readable note, so a clamped result is never returned
 * silently — check [`Clamps::any`] when a number looks wrong, because the
 * geometry may not be the geometry that was asked for.
 */
export type Clamps = { notes: Array<Note>, };
