// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What is asked of one body. Two things, and no third.
 *
 * The train-level reading of [`crate::kinematics::Condition`], without the
 * drive's speed: a train's motion is solved at one turn of whatever is driven,
 * and a load case's speed scales it.
 */
export type Constraint = "held" | "free";
