// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What is asked of one shaft. Three things, and no fourth.
 *
 * The train-level reading of [`crate::kinematics::Condition`], without the
 * drive's speed: a train's motion is solved at one turn of whatever is driven,
 * and a load case's speed scales it. Where more than one shaft is driven they
 * are driven *together* at one turn each — which is a statement about a
 * differential's two inputs turning alike, and the family the solve returns
 * says what the other members do per turn of each.
 */
export type Constraint = "held" | "free";
