// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The three contact ratios.
 */
export type ContactRatios = { 
/**
 * Transverse, `ε_α` — profile overlap.
 */
transverse: number, 
/**
 * Overlap, `ε_β = b sin β / (π m_n)` — axial overlap. Exactly zero for a
 * spur stage.
 */
overlap: number, 
/**
 * Total, `ε_γ = ε_α + ε_β`.
 */
total: number, };
