// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **The Hertzian contact a mesh presses** — one answer for an ellipse and a
 * line, since a line is the ellipse with one curvature at zero
 * ([`crate::hertz::peak_pressure`]).
 */
export type ContactPatch = { 
/**
 * Peak Hertzian pressure, MPa — the worst anywhere on the path. On a line
 * contact that is the envelope over both members' governing points, each
 * member's own sitting on its [`GearResult`]; on a point contact it is
 * the worst of the pitch point and the two boundaries of single-pair
 * contact, which sit 10–27 % above the pitch point and are not what is
 * rated with `ε > 1` because a second pair shares the load there.
 */
max_pressure: number, 
/**
 * What the pitch point alone says, MPa — the one figure both members
 * share, and on a point contact close to the *least* severe the mesh
 * offers, since the relative radius peaks near it.
 */
at_pitch_point: number, 
/**
 * Where the worst point sits on the path, mm from the pitch point.
 */
worst_position: number, 
/**
 * The patch, mm: its length along the contact and its width across.
 *
 * On a line contact the length is the face the mesh is rated on and the
 * width the Hertz half-width doubled, `4 ρ p_max / E*`; on a point
 * contact the ellipse's two axes, the length bounded by the line the teeth
 * have. Both are what a stylus would measure.
 */
patch_length: number, patch_width: number, 
/**
 * Relative curvature along the contact, 1/mm. **Zero is line contact** —
 * the degenerate value, and every parallel mesh's — and that it is not
 * zero is what crossing the bodies did.
 */
curvature_along: number, 
/**
 * ...and across it, `1/ρ` — the reciprocal of the relative radius of
 * curvature at the worst point, in the normal plane.
 */
curvature_across: number, };
