// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShaftRef } from "./ShaftRef";

/**
 * Two shafts that turn as one: a coaxial output coupling, a locked clutch,
 * the join between two stages of a chain. One mechanism, so one type.
 */
export type Coupling = { a: ShaftRef, b: ShaftRef, };
