// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ZoneLimit } from "./ZoneLimit";

/**
 * The zone of action of a crossed pair.
 */
export type CrossedZone = { 
/**
 * Tooth pairs in contact. **Below 1 the pair loses contact between one
 * pair and the next**, which is a failure of kind rather than of margin.
 *
 * A floor for a real worm drive: throating *wraps* the wheel around the
 * worm and engages more of the thread, which can only lengthen the zone, so
 * a worm that clears `ε = 1` here clears it as built. That is an argument
 * about the direction, not a computation, and it is said next to the
 * number.
 */
contact_ratio: number, 
/**
 * What ended the zone: the teeth, or the face they are cut on.
 */
limited_by: ZoneLimit, 
/**
 * The face width at which `ε = 1`, per member, mm.
 *
 * A **geometric** minimum: it keeps contact continuous and says nothing
 * about stress. That is the opposite of the parallel stage's automatic
 * width, which inverts a stress, and the difference has to travel with the
 * number.
 */
face_width_for_continuity: [number, number] | null, 
/**
 * How far the contact point runs along each member's own axis, mm — what a
 * face has to cover, and what a parallel pair does not have at all.
 */
axial_travel: [number, number], };
