// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ZoneLimit } from "./ZoneLimit";

/**
 * What the path of contact says about a crossed-axis mesh.
 *
 * Reported for a worm drive as well as for a crossed gear pair, because both
 * are the same construction here: docs/reference.md#crossed-axes takes **both flanks as involute
 * helicoids on cylinders**, and that is where the stage's contact stress,
 * efficiency and backlash already come from. See [`crossed_mesh`] for why a
 * real worm's throated wheel makes this a floor rather than a wrong number.
 */
export type CrossedMesh = { 
/**
 * Tooth pairs in contact. **Below 1 the drive loses contact between one
 * pair and the next**, which is a failure of kind rather than of margin.
 */
contact_ratio: number, 
/**
 * What ended the zone: the teeth, or the face they are cut on.
 */
limited_by: ZoneLimit, 
/**
 * The face width at which `ε = 1`, per member, mm.
 *
 * A **geometric** minimum: it keeps contact continuous and says nothing
 * about stress. That is the opposite of the spur stage's automatic width,
 * which inverts a stress, and the difference has to travel with the number.
 */
face_width_for_continuity: [number, number] | null, 
/**
 * How far the contact point runs along each member's own axis, mm — what a
 * face has to cover, and what a parallel pair does not have at all.
 */
axial_travel: [number, number], 
/**
 * True when the tooth height was **assumed** rather than given — a worm
 * stage has no addendum input. The figures above are then a lower bound.
 */
tooth_height_assumed: boolean, 
/**
 * What the same teeth would lose with their shafts brought **parallel**, as
 * an efficiency — `None` for a worm drive, whose single-start thread is not
 * a parallel-axis gear.
 *
 * Reported for comparison: crossing shafts adds sliding, so this is the
 * best the pair can be, and how far the crossed figure falls below it is
 * what the shaft angle costs.
 *
 * It was once a *check* — the crossed model omitted the profile sliding, so
 * beating this figure meant sliding had gone missing (docs/corrections.md). The friction
 * balance counts that sliding now, and the check has become worse than
 * useless: it is the **parallel** closed form that is approximate, first
 * order in `μ` where the balance is exact, so at a very small shaft angle
 * the crossed figure legitimately sits a hundredth of a point above and the
 * old test would accuse the better number.
 */
parallel_axis_efficiency: number | null, };
