// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Backlash } from "./Backlash";
import type { CrossedZone } from "./CrossedZone";
import type { Directional } from "./Directional";
import type { LoadCase } from "./LoadCase";
import type { PointContact } from "./PointContact";

/**
 * What a crossed-axis mesh reports — everything a point contact has that a
 * line contact does not, beside what both have.
 *
 * docs/reference.md#crossed-axes takes **both flanks as involute helicoids on
 * cylinders**, and that is where the contact stress, the efficiency, the
 * backlash and the zone all come from; a real worm's throated wheel makes the
 * zone a floor rather than a wrong number ([`CrossedZone`]).
 */
export type CrossedMesh = { 
/**
 * Lead angle of each member, degrees — `90° − β`, the same fact as the
 * helix angle from the other datum. A worm is described by how far its
 * thread advances, a gear by how far its tooth leans; both are reported
 * because a crossed pair is entered either way.
 */
lead_angles: [number, number], 
/**
 * The first member's lead, mm, and axial module, mm.
 */
lead: number, axial_module: number, 
/**
 * The zone of action as the face widths in use leave it — `None` where the
 * pair has no zone at all.
 */
zone: CrossedZone | null, 
/**
 * Mesh efficiency in both drive directions.
 *
 * Unlike a parallel-axis stage these genuinely differ, and **either** can
 * be zero or negative — backward is what self-locking is, and forward is a
 * steep helix split that cannot drive at all.
 * [`Directional::locked`] reads them rather than a separate flag that could
 * disagree.
 */
efficiency: Directional<number>, 
/**
 * The coefficient of friction at which each direction stops driving.
 *
 * Negative where no friction locks the pair that way, which is the ordinary
 * case forwards: a worm you can turn is one whose forward threshold is
 * somewhere absurd or nowhere at all.
 */
locking_friction: Directional<number>, 
/**
 * What the same teeth would lose with their shafts brought **parallel**, as
 * an efficiency — `None` where the parallel pair cannot be built.
 *
 * Reported for comparison: crossing shafts adds sliding, so this is the
 * best the pair can be, and how far the crossed figure falls below it is
 * what the shaft angle costs.
 *
 * It was once a *check* — the crossed model omitted the profile sliding, so
 * beating this figure meant sliding had gone missing (docs/corrections.md). The friction
 * balance counts that sliding now, and the check has become worse than
 * useless: it is the **parallel** closed form that is approximate, first
 * order in `μ` where the balance is exact, so at a very small shaft angle
 * the crossed figure legitimately sits a hundredth of a point above and the
 * old test would accuse the better number.
 */
parallel_axis_efficiency: number | null, 
/**
 * Sliding speed at the pitch point as a multiple of the first member's
 * pitch line speed. The absolute figure needs a shaft speed, so the train
 * fills [`Self::sliding_velocity`] instead.
 */
sliding_ratio: number, 
/**
 * Sliding speed at the pitch point, mm/s. Filled in by the train.
 */
sliding_velocity: number, 
/**
 * The contact patch, in both load cases.
 */
contact: LoadCase<PointContact>, 
/**
 * Angular backlash **per member**, degrees, at the three centre distances
 * — the same reading every mesh gives ([`super::MeshReport::backlash`]),
 * and here the worm's float is in it as well as the centre line.
 */
backlash: [Backlash, Backlash], 
/**
 * Whether each member's flank is reached past its usable end by the other
 * member's tip ([`CrossedPath::flank_interference`]).
 */
flank_interference: [boolean, boolean], 
/**
 * Whether the tooth counts are coprime.
 */
coprime: boolean, };
