// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The pinion cutter a ring is shaped with.
 *
 * A ring has no meaningful geometry without one: unlike a rack-cut external
 * gear, where the tool is implied by the basic rack, the fillet a ring gets
 * depends on how many teeth its cutter had. Two rings with identical teeth,
 * module and depth are *different parts* if they were shaped differently.
 */
export type Cutter = { teeth: number, 
/**
 * Addendum, in modules — how far past its pitch circle the tool reaches.
 */
addendum: number, 
/**
 * Tip corner round, in modules.
 */
tip_round: number, };
