// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How often a tooth is loaded, which is not one number once the drive reverses.
 *
 * Both counts are always reported and are the **same number** when the drive
 * does not reverse — the ordinary case as a value rather than behind a flag, so
 * a reader can quote a range unconditionally.
 */
export type Cycles = { 
/**
 * Engagements the tooth root sees. A reversing drive loads **both** flanks
 * in bending, so every engagement counts.
 */
bending: number, 
/**
 * Engagements one flank sees. A reversing drive shares them between the two
 * flanks, so each takes half; otherwise it is the same number as `bending`.
 */
contact: number, };
