// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A quantity reported for both drive directions.
 *
 * Efficiency and angular backlash are both like this, and for the same reason:
 * the answer depends on which end is the output. For efficiency it is the
 * friction that reverses its role; for backlash it is the lever arm, since the
 * same tooth gap subtends a different angle at each member.
 *
 * A symmetric mesh puts equal numbers in both fields — computed twice through
 * the same path, not copied — so nothing has to decide in advance which meshes
 * are symmetric.
 */
export type Directional<T> = { forward: T, backward: T, };
