// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one distance came to.
 */
export type DistanceReport = { 
/**
 * The zero-backlash distance of each mesh on it, in mesh order.
 */
nominal: Array<number>, 
/**
 * The distance every mesh on it runs at.
 */
running: number, 
/**
 * `running − nominal` of the first mesh, signed as the mesh reads it.
 */
clearance: number, 
/**
 * **The mesh whose tips sized this distance**, where an automatic one
 * was opened out past what the shifts left so that its tips clear
 * ([`Distance::tip_clearance`]); `None` where the shifts' own distance
 * stood, or the distance was given.
 */
sized_by: number | null, 
/**
 * **The stagger angle**, degrees, where the distance joins two axes
 * one carrier carries and each stands at a distance from the
 * carrier's own axis: the angle about that axis between the two, from
 * the triangle the three running distances make. `None` elsewhere.
 */
stagger: number | null, };
