// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one distance came to.
 */
export type DistanceReport = { 
/**
 * The zero-backlash distance of each mesh on it, in mesh order.
 */
nominal: Array<number>, 
/**
 * The distance every mesh on it runs at.
 */
running: number, 
/**
 * `running − nominal` of the first mesh, signed as the mesh reads it.
 */
clearance: number, };
