// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Auto } from "./Auto";

/**
 * The distance between two axes, in the frame both stand still in, and what
 * goes with it.
 */
export type Distance = { axes: [number, number], 
/**
 * The angle between the two axes, degrees: 0 for parallel, 90 for a
 * worm and its wheel. A mesh on crossed axes is a point contact with a
 * model of its own ([`super::crossed`]), and the rest of the stage
 * cannot yet share a member with it.
 */
angle: number, 
/**
 * **Size the two members as a worm and its wheel** — the worm's length
 * and the wheel's face from the conventional proportions — rather than
 * as two crossed helical gears. A preset's word, and an input because
 * the recommendation is one a designer takes or leaves.
 */
worm: boolean, 
/**
 * The running distance, mm: automatic is whatever the shifts leave,
 * opened by the clearance.
 */
distance: Auto<number>, 
/**
 * The assembly clearance every mesh on this pair runs with.
 */
clearance: Auto<number>, tolerance_plus: number, tolerance_minus: number, 
/**
 * Axial float of the first axis's members, mm — a rigid slide that
 * opens one flank as far as it closes the other on a helical mesh.
 */
axial_clearance: number, };
