// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Port } from "./Port";

/**
 * How a fatigue load is applied over the life of the train — what turns a
 * ratio into a tooth count.
 */
export type Duty = { "intermittent": { 
/**
 * Sweep per actuation, degrees, at [`Self::Intermittent::at`].
 */
range_degrees: number, 
/**
 * The shaft the sweep is measured at.
 */
at: Port, actuations: number, 
/**
 * Whether the drive reverses between actuations.
 *
 * It changes nothing but the **cycle count** and which roots are
 * loaded both ways ([`loaded_cycles`], [`Reversal`]): each
 * actuation's revolutions round up on their own rather than the total
 * rounding once, because a partial sweep still loads the teeth it
 * reaches and every tooth must meet the worst of them; and the contact
 * count halves, because the two flanks share the engagements while
 * both take the full bending.
 */
reversing: boolean, } } | { "continuous": { runtime_hours: number, } };
