// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Piece } from "./Piece";
import type { Place } from "./Place";
import type { Shape } from "./Shape";

/**
 * **What a designer does to a train's graph** — the one set of edits,
 * every index the graph's own: a member, a mesh, a distance, an axis or a
 * coupling by its place in the [`Shape`]'s lists, a body by the train's
 * number for it. Each is a rule about what else changes, made whole or
 * refused whole ([`EditRefused`]) by [`super::Train::edit`].
 */
export type Edit = { "add_gear": { mate: number, on: Place, ring: boolean, } } | { "add_ratio": { distance: number, shared: number, } } | { "add_step": { axis: number, } } | { "couple": { body: number, } } | { "remove": Piece } | { "move": { member: number, to: number | null, } } | { "join": { a: number, b: number, } } | { "hold": number } | { "release": number } | { "insert": { shape: Shape, at: number | null, } };
