// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A number that is exactly a quotient of integers, and how it reads.
 */
export type Exact = { 
/**
 * For arithmetic and for a readout that rounds.
 */
value: number, 
/**
 * The quotient itself — `3721/16`, or `49` — for a readout that does not.
 * Digits and a slash, not a word.
 */
text: string, };
