// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ByKind } from "./ByKind";

/**
 * Which ratings an automatic face width is sized from.
 *
 * Four toggles, and shaped like the answer they select from so the UI can walk
 * them rather than naming each: a rating exists for every combination of what
 * fails (bending or contact) and what it is rated against (the ultimate or the
 * fatigue allowable). Per **kind** rather than per case: however many loads
 * of a kind there are, the width is the largest any of them asks for, and a
 * toggle says whether that kind of ask counts at all.
 */
export type FaceSources = { bending: ByKind<boolean>, contact: ByKind<boolean>, };
