// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadCase } from "./LoadCase";

/**
 * Which ratings an automatic face width is sized from.
 *
 * Four toggles rather than two, and shaped like the answer they select from so
 * the UI can walk them rather than naming each: a rating exists for every
 * combination of what fails (bending or contact) and what it is rated against
 * (the peak or the cyclic load).
 */
export type FaceSources = { bending: LoadCase<boolean>, contact: LoadCase<boolean>, };
