// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Broad material family.
 *
 * Carried because several conventions are per-family rather than per-material
 * — the uniform fatigue fraction applied across the polyamides, and the
 * reversed-bending penalty a planet gear takes (docs/reference.md#trains).
 */
export type Family = "steel" | "brass" | "pom" | "polyamide";
