// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Freedom } from "./Freedom";

/**
 * **What one input came to**, by the name relief knows it by — the number a
 * box turned given by relief is seeded with, so a designer holds what they
 * were shown rather than a stale zero.
 */
export type Figure = { freedom: Freedom, 
/**
 * `None` where the result carries no such figure — a crossed pair's
 * overlap — and the box keeps what it had.
 */
value: number | null, };
