// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The root fillet a shaper cut, as the span of cutter travel that traced it.
 *
 * The two travels are what the trochoid is read at; the radii and angles come
 * from [`Ring::trochoid_at`] rather than being stored, so there is one place
 * the curve is defined.
 */
export type Fillet = { 
/**
 * Cutter travel at the flank/fillet junction.
 */
s_j: number, 
/**
 * Travel at which the fillet ends.
 *
 * Zero when a root arc follows — the deepest cut, at mid-space. Non-zero
 * when the fillets from the two flanks meet before they get there, which
 * leaves a **fully filleted root** with no flat at all. Common, and not a
 * fault: it simply means the cutter's tip is wide enough that its corner
 * rounds overlap.
 */
s_root: number, };
