// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the first member's size is stated — **three readings of one number**.
 *
 * A pair's two helix angles are bound by `β₁ + β₂ = Σ`, so one number fixes
 * both, and it can be stated as what each gear carries beyond half the shaft
 * angle, as the first member's own helix angle, or as the first member's
 * pitch diameter — since `d = z m_n / cos β`, a diameter and a helix angle are
 * the same freedom read two ways. Which reading a designer uses is the whole
 * of the difference between a worm and a crossed gear: a worm's pitch diameter
 * is a *free choice* that sets its lead angle, its efficiency and whether it
 * can be back-driven, while a gear's follows from its teeth.
 *
 * ```text
 * AdditionalHelix(β_add):   β₁ = Σ/2 + β_add,   β₂ = Σ/2 − β_add
 * HelixAngle(β₁):           β₂ = Σ − β₁
 * PitchDiameter(d₁):        cos β₁ = z₁ m_n / d₁,   β₂ = Σ − β₁
 * ```
 *
 * At `Σ = 0` the first reading is the familiar shared helix angle with the
 * hands opposed, which is the specification's own "Total Helix Angle = 0.5 ×
 * Axis Angle + Additional Helix Angle".
 *
 * [verified: a `Screw` built with `d₁ = z₁ m_n / cos β₁` reports
 * `γ₁ = 90° − β₁` exactly, and `β₂ = Σ − β₁`, over three tooth pairs × four
 * shaft angles × three helix angles.]
 */
export type FirstMemberSizing = { "additional_helix": number } | { "helix_angle": number } | { "pitch_diameter": number };
