// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the first member's size is fixed.
 *
 * **This is the whole of the difference between a worm drive and a crossed gear
 * pair**, and it is worth being explicit about because the mathematics is
 * otherwise identical — docs/reference.md#crossed-axes argued they are one thing, and this is where that
 * argument is cashed.
 *
 * A worm's pitch diameter is a *free choice*: nothing in its thread count fixes
 * it, and it is what sets the lead angle, the efficiency, and whether the drive
 * can be back-driven at all. An ordinary gear's is not free — it follows from
 * its tooth count and helix angle, `d = z m_n / cos β`. So the two differ in
 * which of `d` and `β` is the input, and in nothing else:
 *
 * ```text
 * sin γ = z m_n / d        and      γ = 90° − β        so      sin γ = cos β
 * ```
 *
 * [verified: a `Screw` built with `d₁ = z₁ m_n / cos β₁` reports
 * `γ₁ = 90° − β₁` exactly, and `β₂ = Σ − β₁`, over three tooth pairs × four
 * shaft angles × three helix angles.]
 */
export type FirstMemberSizing = { "pitch_diameter": number } | { "helix_angle": number };
