// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **One row of a case's flow.**
 */
export type FlowRow = { "body": { body: number, } } | { "mesh": { mesh: number, to: number, } } | { "idle": { mesh: number, to: number, } } | { "junction": { part: number, meshes: Array<number>, terminals: Array<number>, } } | { "coupling": { coupling: number, to: number, } };
