// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Freedom } from "./Freedom";

/**
 * **A set of inputs bound by one relation, and how many of them may be given.**
 *
 * A geometric relation among `n` inputs leaves `n − 1` of them free, so giving
 * `n` is not a tighter specification — it is a contradiction, and one of the
 * numbers would have to be ignored. This says which inputs are in that
 * argument and how many may stand.
 *
 * # Why the *stage* declares this rather than the front end
 *
 * It was three functions in TypeScript, one per stage kind, each restating a
 * relation the core already enforces. That is two faults at once: an
 * engineering rule written outside Rust, and the same idea written once per
 * kind — so a fifth kind arrives with no relief at all, and a rule that changes
 * changes in one of four places. It is also untestable there, and was untested.
 *
 * The stage kinds genuinely differ in *what* is related, which is why this is a
 * declaration and not a constant: a pair relates its distance to its two
 * shifts, an epicyclic set relates its three shifts to each other through the
 * two distances that must agree, and a hula stage relates each mesh's pair
 * separately because its crank fixes their difference one mesh at a time.
 *
 * What does **not** differ is the resolution: too many given means the first
 * one in `order` that the designer is not this moment touching goes back to
 * automatic. Least precious first, and stated by the stage.
 */
export type FreedomGroup = { 
/**
 * How many of `order` may be given before the set is over-determined.
 */
given_at_most: number, 
/**
 * The inputs in the argument, **relief order, least precious first**.
 */
order: Array<Freedom>, };
