// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Freedom } from "./Freedom";

/**
 * **A set of inputs bound by one relation, and how many of them may be given.**
 *
 * A geometric relation among `n` inputs leaves `n − 1` of them free, so giving
 * `n` is not a tighter specification — it is a contradiction, and one of the
 * numbers would have to be ignored. This says which inputs are in that
 * argument and how many may stand.
 *
 * # Why the *stage* declares this rather than the front end
 *
 * It was three functions in TypeScript, one per stage kind, each restating a
 * relation the core already enforces. That is two faults at once: an
 * engineering rule written outside Rust, and the same idea written once per
 * kind — so a fifth kind arrives with no relief at all, and a rule that changes
 * changes in one of four places. It is also untestable there, and was untested.
 *
 * The stage kinds genuinely differ in *what* is related, which is why this is a
 * declaration and not a constant: a pair relates its distance to its two
 * shifts, an epicyclic set relates its three shifts to each other through the
 * two distances that must agree, and a hula stage relates each mesh's pair
 * separately because its crank fixes their difference one mesh at a time.
 *
 * What does **not** differ is the resolution: too many given means the first
 * one in `order` that the designer is not this moment touching goes back to
 * automatic. Least precious first, and stated by the stage.
 */
export type FreedomGroup = { 
/**
 * How many of `order` may be **given** before the set is over-determined.
 */
given_at_most: number, 
/**
 * How many of `order` may be **automatic** before it is under-determined.
 *
 * The mirror of `given_at_most`, and it is needed for a real case rather
 * than for symmetry: a centre distance is *nominal + clearance* and an
 * automatic clearance is *distance − nominal*, so with both automatic
 * neither has anything to derive from. One of the two has to be a number
 * somebody gave.
 *
 * A kind with **no** distance input would say `0` here — its clearance
 * could never be derived, because there is nothing to derive it from. That
 * is the same statement, counted; every kind has the input now, so none
 * says it.
 */
automatic_at_most: number, 
/**
 * The inputs in the argument, **relief order, least precious first**.
 *
 * **An entry is one input, stated one or more ways.** A pair's size is
 * either helix or the first pitch diameter — one freedom, three boxes —
 * so the entry that names it lists all three, and the relation counts it
 * once: given while any reading is, automatic while all are. Within an
 * entry at most one reading stands, relieved in the same order, so the
 * exclusivity of the readings is not a second group with a count to keep
 * in step with this one.
 *
 * One order serves both directions: too many given turns the first entry
 * that is not being touched automatic, and too many automatic pins the
 * first that is not being touched — by its last reading, the one the
 * solve reads first. The same walk, read the other way.
 */
order: Array<Array<Freedom>>, };
