// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One of a stage's constrainable inputs, named so a caller can find it.
 *
 * `Shift(i)` indexes the stage's members in the order
 * [`StageResult::members`] reports them — a pair's two gears, a set's sun,
 * planet and ring, a hula stage's four — so a caller that can walk members can
 * resolve one of these without knowing the kind.
 */
export type Freedom = "centre_distance" | { "shift": number };
