// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberFreedom } from "./MemberFreedom";

/**
 * One of a stage's constrainable inputs, named so a caller can find it.
 *
 * Two levels, because a stage has inputs of two kinds: its own — a distance,
 * a clearance, a ratio, a worm's diameter — and one of each per member.
 * `Member(i, _)` indexes the members in the order [`ShapeResult::members`]
 * reports them — a pair's two gears, a set's sun, planet and ring, a hula
 * stage's four — and is resolved once for every member (`Shape::inputs`), so
 * a member input that arrives costs one line there and none per preset.
 */
export type Freedom = { "distance": number } | { "clearance": number } | { "overlap": number } | { "member": [number, MemberFreedom] };
