// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cycles } from "./Cycles";
import type { LoadCase } from "./LoadCase";
import type { Material } from "./Material";
import type { Note } from "./Note";
import type { Ranges } from "./Ranges";
import type { Widths } from "./Widths";

/**
 * What a stage does to one of its gears.
 */
export type GearResult = { 
/**
 * The shift in force, after any automatic calculation.
 */
profile_shift: number, 
/**
 * Likewise the addendum.
 */
addendum: number, 
/**
 * Likewise the face width.
 */
face_width: number, 
/**
 * What a convention recommends for the face width, mm, where one applies
 * and whether or not it is in use — a worm's length and its wheel's width
 * ([`crossed::proportions`]). `None` where a rating sizes the face
 * instead, which is every other member.
 */
recommended_face_width: number | null, 
/**
 * Reference pitch diameter, mm — `z m_n / cos β`.
 *
 * An output rather than an echo: a worm's is solved where its size is
 * automatic, and every other member's follows from a helix that may have
 * been.
 */
pitch_diameter: number, 
/**
 * Helix angle, degrees, signed by hand — likewise from the sizing as
 * solved.
 */
helix_angle: number, 
/**
 * Lead angle, degrees — `90° − |β|`, the same fact from the other datum. A
 * worm is described by how far its thread advances, a gear by how far its
 * tooth leans; both are reported because a pair is entered either way.
 */
lead_angle: number, 
/**
 * Lead, mm — how far a point on the flank advances per revolution,
 * `π d tan γ`. `None` on a spur gear, whose flank does not advance.
 */
lead: number | null, 
/**
 * Torque on this gear, N·m, driving forward at peak.
 */
torque: number, 
/**
 * Torque on this gear from a back-driving load, N·m.
 *
 * `None` where none is reacted here — which is every gear of a train that
 * can be back-driven at all, and every gear upstream of whatever stage
 * stops one that cannot.
 */
back_driving_torque: number | null, 
/**
 * Rotational speed, rpm.
 */
speed: number, 
/**
 * Tooth load cycles over the duty the train describes.
 *
 * One cycle per revolution for a simple gear: a given tooth meets the mate
 * once per turn. Sun and ring gears in a planetary stage see `N_planets`
 * per revolution, and a planet is a special case again — docs/reference.md#trains.
 */
tooth_cycles: Cycles, 
/**
 * Tooth root bending stress, MPa, for each load case. `None` where the
 * stress correction is undefined for this section — see
 * [`crate::strength::bending_stress`] — or where the case carries no load.
 */
bending_stress: LoadCase<number | null>, 
/**
 * Hertzian contact stress, MPa, for each load case — at **this gear's**
 * governing point.
 *
 * The two gears of a mesh share one patch and one pressure at any instant,
 * so this is not a per-tooth curvature effect. They differ because they are
 * rated at different *moments*: each gear's dedendum is loaded alone at one
 * end of the path, and that is where its own pitting is assessed. See
 * [`crate::strength::ContactStress::governing`].
 */
contact_stress: LoadCase<number>, 
/**
 * The face width each rating would need: two per case, four in all.
 */
min_face_width: LoadCase<Widths>, 
/**
 * Guards that altered this gear's geometry.
 */
clamps: Array<Note>, 
/**
 * What the **rating** has to say about this gear, as against what was done
 * to its geometry.
 *
 * Kept apart from [`Self::clamps`] because nothing here moved a dimension:
 * a root loaded on both flanks and a notch outside the `Y_S` fit's band are
 * statements about how the number was arrived at, not about the part.
 *
 * **Per gear rather than per stage**, and that is not filing. A stage note
 * naming a member has to carry the member's name in its own text, and two
 * members raising the same note give one list two entries with one key —
 * which a keyed list in the front end cannot render (`docs/corrections.md`).
 * A note that belongs to a gear belongs *on* the gear.
 */
notes: Array<Note>, 
/**
 * The material as used, after any overrides — what the numbers were
 * actually computed from, rather than what the library holds.
 */
material: Material, 
/**
 * What this gear's geometry allows its own inputs to be.
 *
 * Computed from the **resolved** parameters, so an automatic profile shift
 * or addendum is already folded in. The UI bounds its fields by these
 * rather than by constants — see `docs/reference.md#input-ranges`.
 */
ranges: Ranges, };
