// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cycles } from "./Cycles";
import type { LoadCase } from "./LoadCase";
import type { Material } from "./Material";
import type { Note } from "./Note";
import type { Ranges } from "./Ranges";
import type { Widths } from "./Widths";

/**
 * What a stage does to one of its gears.
 */
export type GearResult = { 
/**
 * The shift in force, after any automatic calculation.
 */
profile_shift: number, 
/**
 * Likewise the addendum.
 */
addendum: number, 
/**
 * Likewise the face width.
 */
face_width: number, 
/**
 * Torque on this gear, N·m, driving forward at peak.
 */
torque: number, 
/**
 * Torque on this gear from a back-driving load, N·m.
 *
 * `None` where none is reacted here — which is every gear of a train that
 * can be back-driven at all, and every gear upstream of whatever stage
 * stops one that cannot.
 */
back_driving_torque: number | null, 
/**
 * Rotational speed, rpm.
 */
speed: number, 
/**
 * Tooth load cycles over the duty the train describes.
 *
 * One cycle per revolution for a simple gear: a given tooth meets the mate
 * once per turn. Sun and ring gears in a planetary stage see `N_planets`
 * per revolution, and a planet is a special case again — docs/reference.md#trains.
 */
tooth_cycles: Cycles, 
/**
 * Tooth root bending stress, MPa, for each load case. `None` where the
 * stress correction is undefined for this section — see
 * [`crate::strength::bending_stress`] — or where the case carries no load.
 */
bending_stress: LoadCase<number | null>, 
/**
 * Hertzian contact stress, MPa, for each load case — at **this gear's**
 * governing point.
 *
 * The two gears of a mesh share one patch and one pressure at any instant,
 * so this is not a per-tooth curvature effect. They differ because they are
 * rated at different *moments*: each gear's dedendum is loaded alone at one
 * end of the path, and that is where its own pitting is assessed. See
 * [`crate::strength::ContactStress::governing`].
 */
contact_stress: LoadCase<number>, 
/**
 * The face width each rating would need: two per case, four in all.
 */
min_face_width: LoadCase<Widths>, 
/**
 * Guards that altered this gear's geometry.
 */
clamps: Array<Note>, 
/**
 * The material as used, after any overrides — what the numbers were
 * actually computed from, rather than what the library holds.
 */
material: Material, 
/**
 * What this gear's geometry allows its own inputs to be.
 *
 * Computed from the **resolved** parameters, so an automatic profile shift
 * or addendum is already folded in. The UI bounds its fields by these
 * rather than by constants — see `docs/reference.md#input-ranges`.
 */
ranges: Ranges, };
