// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Material } from "./Material";
import type { Note } from "./Note";
import type { Ranges } from "./Ranges";

/**
 * What a stage does to one of its gears.
 */
export type GearResult = { 
/**
 * The shift in force, after any automatic calculation.
 */
profile_shift: number, 
/**
 * Likewise the addendum.
 */
addendum: number, 
/**
 * Likewise the face width.
 */
face_width: number, 
/**
 * Torque on this gear, N·m.
 */
torque: number, 
/**
 * Rotational speed, rpm.
 */
speed: number, 
/**
 * Tooth load cycles over the duty the train describes.
 *
 * One cycle per revolution for a simple gear: a given tooth meets the mate
 * once per turn. Sun and ring gears in a planetary stage see `N_planets`
 * per revolution, and a planet is a special case again — docs/reference.md#trains.
 */
tooth_cycles: number, 
/**
 * Tooth root bending stress, MPa. `None` where the stress correction is
 * undefined for this section — see [`crate::strength::bending_stress`].
 */
bending_stress: number | null, 
/**
 * Hertzian contact stress, MPa. Shared by the pair, so both gears report
 * the same number; the *allowables* they are judged against differ.
 */
contact_stress: number, 
/**
 * Face width the bending stress would need against the fatigue allowable.
 */
min_face_width_bending: number | null, 
/**
 * ...and against contact.
 */
min_face_width_contact: number, 
/**
 * Guards that altered this gear's geometry.
 */
clamps: Array<Note>, 
/**
 * The material as used, after any overrides — what the numbers were
 * actually computed from, rather than what the library holds.
 */
material: Material, 
/**
 * What this gear's geometry allows its own inputs to be.
 *
 * Computed from the **resolved** parameters, so an automatic profile shift
 * or addendum is already folded in. The UI bounds its fields by these
 * rather than by constants — see `docs/reference.md#input-ranges`.
 */
ranges: Ranges, };
