// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input parameters for a single gear.
 *
 * Angles are **degrees** here, because this is the boundary the UI writes to.
 * Everything downstream works in radians.
 *
 * `addendum`, `dedendum` and `root_radius` are multiples of the **normal**
 * module. `profile_shift` likewise.
 */
export type GearParams = { 
/**
 * Normal module, mm.
 */
module: number, 
/**
 * Normal pressure angle, degrees.
 */
pressure_angle: number, teeth: number, 
/**
 * Profile shift `x`, in modules.
 */
profile_shift: number, 
/**
 * Helix angle, degrees. Sign selects hand.
 */
helix_angle: number, 
/**
 * Addendum, in modules.
 */
addendum: number, 
/**
 * Dedendum, in modules.
 */
dedendum: number, 
/**
 * Cutter tip radius, in modules. 0.38 is the ISO 53 basic rack.
 */
root_radius: number, 
/**
 * Tooth thickness modification `k`, dimensionless, nominally 1.
 *
 * Defined on the rack: tooth width `(π m/2)·k`, space width
 * `(π m/2)·(2−k)`, so the pitch is preserved. Two gears in mesh must sum to
 * 2 for zero backlash.
 *
 * This is *not* separate geometry — it is exactly an extra thickness-only
 * profile shift, `x_s = π(k−1)/(4 tan αₙ)`. See [`GearParams::thickness_shift`].
 */
thickness_mod: number, 
/**
 * Amplitude of an **angularly varying** profile shift, in modules.
 *
 * `x(θ) = profile_shift + angular_shift · cos θ`, maximum at 0° and minimum
 * at 180° — what a hob moving radially in and out once per revolution
 * produces. It makes the tip and root envelopes eccentric by
 * `e = module · angular_shift` while the pitch and base circles stay on the
 * axis, so the body moves eccentrically at a constant ratio (docs/reference.md#angularly-varying-profile-shift).
 *
 * **Zero is an ordinary gear**, and not by a branch: every tooth then takes
 * the same shift and the whole construction collapses onto the single-`x`
 * one it extends, bit for bit.
 */
angular_shift: number, 
/**
 * `λ`, how far the indexing compensates for the varying tooth thickness.
 *
 * A gear with varying tooth thickness cannot be exactly conjugate in both
 * directions — uniform spacing on both flanks forces uniform thickness, in
 * two lines of algebra (docs/reference.md#angularly-varying-profile-shift) — so the unavoidable error can only be
 * distributed. Tooth `k` is seated at `2πk/z + λ(ψ_b,ref − ψ_b,k)`, which
 * scales the drive-flank error by `|1 − λ|` and the coast-flank error by
 * `|1 + λ|`.
 *
 * `0` is the minimax optimum and what a plain radial hob oscillation gives;
 * `1` is exactly conjugate forward and twice the error in reverse, and needs
 * the radial motion synchronised with a differential rotation of the work.
 * It has no effect at all when [`Self::angular_shift`] is zero, since every
 * tooth then has the same seat to correct towards.
 */
index_offset: number, };
