// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cycles } from "./Cycles";
import type { Widths } from "./Widths";

/**
 * What one load case does to one gear.
 */
export type GearCase = { 
/**
 * Index into the train's list of load cases.
 */
case: number, 
/**
 * Torque on this gear, N·m, signed like its own rotation, in this case's
 * direction of travel — a member at the far end of a mesh carries the
 * load referred by the ratio and cut by the loss the mesh takes carrying
 * it *that* way, which for a locked mesh is nought.
 */
torque: number, 
/**
 * **What this gear's meshes put on its body**, N·m, signed as the
 * train's body torques are: the gears on one shaft sum to the shaft's
 * own load or reaction, so where a shaft carries two gears this is what
 * it hands from the one to the other — which the case's figure for the
 * body, being the external torque, does not say. Whichever parts the
 * body lies between.
 */
on_body: number, 
/**
 * Rotational speed, rpm, from the case's speed at its port.
 */
speed: number, 
/**
 * Speed **relative to the carrier of its mesh**, rpm — what its teeth
 * actually see, and what its cycles are counted from. A pair has no
 * carrier and this is [`Self::speed`]; an epicyclic member's is not, and
 * a held ring's is not zero while its speed is.
 */
speed_against_carrier: number, 
/**
 * Tooth load cycles over the duty this case describes — a fatigue case's,
 * and `None` on an ultimate one, which is survived once.
 *
 * One cycle per revolution for a simple gear: a given tooth meets the mate
 * once per turn. An epicyclic set's members are engaged once per turn
 * relative to the carrier, once per planet — docs/reference.md#trains.
 */
cycles: Cycles | null, 
/**
 * Tooth root bending stress, MPa. `None` where the stress correction is
 * undefined for this section — see [`crate::strength::bending_stress`].
 */
bending_stress: number | null, 
/**
 * Hertzian contact stress, MPa, at **this gear's** governing point.
 *
 * The two gears of a mesh share one patch and one pressure at any instant,
 * so this is not a per-tooth curvature effect. They differ because they are
 * rated at different *moments*: each gear's dedendum is loaded alone at one
 * end of the path, and that is where its own pitting is assessed. See
 * [`crate::strength::ContactStress::governing`].
 */
contact_stress: number, 
/**
 * The face width each rating would need.
 */
min_face_width: Widths, };
