// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which member of a mesh carries the shift a designer gives.
 */
export type GivenShift = "ring" | "pinion";
