// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AxisGroup } from "./AxisGroup";
import type { Centre } from "./Centre";

/**
 * **The two groupings that need no solve** — see [the module](self).
 */
export type Groupings = { centres: Array<Centre>, axes: Array<AxisGroup>, };
