// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **A line of ISO 6336-5:2016 Table 1**, `σ_Hlim = A·HV + B` over a band of
 * hardness, for one kind of material. One is carried: the one the library's
 * steels are.
 */
export type HardnessLine = "through_hardened_alloy_steel";
