// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HardnessLine } from "./HardnessLine";
import type { QualityGrade } from "./QualityGrade";
import type { Value } from "./Value";

/**
 * **A flank's pitting endurance estimated from hardness**: a line of ISO
 * 6336-5, the material's hardness, and the quality grade it is read at —
 * the grade a designer's choice, the estimate Rust's.
 */
export type HardnessEstimate = { line: HardnessLine, 
/**
 * Vickers hardness, HV, with where it came from.
 */
hardness: Value, grade: QualityGrade, };
