// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Backlash } from "./Backlash";
import type { Directional } from "./Directional";

/**
 * One mesh of a solved drive.
 */
export type HulaMesh = { 
/**
 * Operating pressure angle, degrees.
 *
 * A one-tooth-difference pair opened far enough to clear itself runs at an
 * angle no ordinary pair would — above 50° on the shipped proportions —
 * which is a property of the arrangement rather than a fault, and is
 * reported for that reason.
 */
operating_pressure_angle: number, 
/**
 * Far-side tip gap, mm: the room the wobble body has on the side away from
 * the mesh, which is what the shift was spent on.
 */
clearance: number, 
/**
 * The same gap measured on the parts as cut, mm. It differs from the one
 * above only where a tip was clamped, and then the difference is what the
 * clamp cost.
 */
clearance_as_cut: number, contact_ratio: number, 
/**
 * The pinion's tip reaches past where the ring's flank ends.
 */
trochoid_interference: boolean, 
/**
 * The ring's tip reaches below where the pinion's flank ends.
 */
involute_interference: boolean, 
/**
 * **The tips foul away from the line of action** — the condition that
 * decides a small tooth difference, where the tip circles cross far from
 * the line of centres and the mesh itself is perfectly conjugate.
 */
tip_interference: boolean, 
/**
 * How much room the tips have where their circles cross, as an angle of
 * pinion rotation, degrees. Negative is the overlap.
 */
tip_margin: number, 
/**
 * Angular backlash at each member, degrees — the pinion's first, then the
 * ring's: nominal at the running offset, then at each end of the tolerance
 * band. The same gap subtends a different angle at each, so the two differ
 * whenever the tooth counts do.
 */
backlash: [Backlash, Backlash], 
/**
 * **This pair's own efficiency with the crank held**, 0..1, both
 * directions — what the teeth lose, and nothing about the arrangement they
 * sit in.
 *
 * It is emphatically **not** the drive's: the two of these multiply to
 * [`HulaResult::fixed_carrier_efficiency`], and the drive's own is that
 * figure put through the reduction, which on a high-ratio arrangement
 * takes a pair losing under a percent to a drive losing tens of them
 * ([`HulaResult::efficiency`]). Reported per mesh for the same reason a
 * planetary set reports it per mesh: a stage that loses more than it should
 * loses it in one of its meshes, and a single product cannot say which.
 */
efficiency: Directional<number>, };
