// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GearResult } from "./GearResult";

/**
 * One gear of a solved stage.
 *
 * The rating is a [`GearResult`], as it is for every other stage kind here, and
 * what this adds is what the *arrangement* makes of the member: which side of
 * its pair it is, and the four radii a stage of this kind is read by — a
 * member with something extra to say says it beside the answer every member
 * gives, not instead of it.
 */
export type HulaGear = { teeth: number, 
/**
 * Whether this member is the ring of its pair — an outcome of the tooth
 * counts rather than an input.
 */
ring: boolean, pitch_radius: number, base_radius: number, 
/**
 * Tip radius, mm. **Smaller** than the pitch radius on a ring.
 */
tip_radius: number, 
/**
 * Root radius, mm. Larger than the pitch radius on a ring.
 */
root_radius: number, 
/**
 * Everything a gear in a stage reports: the shift and addendum it was
 * built at, its face width, torque, speed, tooth cycles, stresses and the
 * widths its ratings ask for.
 *
 * Gear 1 is held, so its speed is zero; gears 2 and 3 share the wobble
 * body's. All four are engaged once per revolution **relative to the
 * crank**, which is what [`super::engagements`] says for every epicyclic
 * member.
 */
gear: GearResult, };
