// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Backlash } from "./Backlash";
import type { Directional } from "./Directional";
import type { HulaGear } from "./HulaGear";
import type { HulaMesh } from "./HulaMesh";
import type { Note } from "./Note";
import type { ShaftsCase } from "./ShaftsCase";

/**
 * What a hula stage came to.
 */
export type HulaResult = { 
/**
 * Input revolutions per output revolution. Negative means the output turns
 * against the crank.
 */
ratio: number, 
/**
 * `z₂z₄` and `D = z₂z₄ − z₁z₃`, the two products the ratio is written in.
 * Reported because `D` is the design rule: its size is the reduction and
 * its sign is the direction.
 */
ratio_products: [bigint, bigint], 
/**
 * The zero-backlash crank offset, mm.
 */
offset_nominal: number, 
/**
 * **The minimum far-side clearance the stage was held to**, zero where the
 * crank offset was given instead and the input went unread — the same
 * question every stage answers about its own clearance (see
 * [`super::PairResult::clearance`]).
 */
clearance: number, 
/**
 * The offset actually run at — the running clearance *inside* the
 * zero-backlash one, both meshes being internal.
 */
offset: number, 
/**
 * The running clearance, mm: the input, which both meshes have. Always
 * given, for the reason a set's is ([`super::Stage::freedoms`]) — the
 * shifts absorb the offset, so no given offset could hand it back.
 */
running_clearance: number, 
/**
 * Which mesh sits at the clearance minimum, when the offset came from it.
 */
binding_mesh: number | null, 
/**
 * Mesh efficiency with the **crank held**, 0..1, both directions: the two
 * pairs' own, multiplied.
 *
 * **It is not the stage's efficiency**, and on a high-ratio arrangement it
 * is nowhere near it: the meshes lose under a percent while the stage loses
 * tens of them, because power circulates. Both figures are reported for
 * exactly that reason — one is not a stand-in for the other, and reading
 * the mesh figure as the stage's is the mistake this pair of fields exists
 * to prevent.
 */
fixed_carrier_efficiency: Directional<number>, 
/**
 * The stage's own efficiency, 0..1, in both directions.
 *
 * It follows from the reduction and the meshes alone:
 *
 * ```text
 * η = 1 / [ R(1 − η₀) + η₀ ]
 * ```
 *
 * — which is [`stage_efficiency`] and is worth reading before choosing
 * tooth counts, because it says what a design *can* reach before any of it
 * is drawn. At `R = 49` a mesh pair losing 0.27 % gives 88 %; the same pair
 * at `R = 324` gives 53 %, and losing 0.85 % instead gives 27 %.
 *
 * **Backward is zero where the drive cannot be back-driven**, which on this
 * arrangement is the ordinary case rather than the exception: an
 * efficiency below a half forward means a reversed power flow with no
 * self-consistent solution, and the classical `2 − 1/η` for such a set is
 * negative there. Reported the way a self-locking worm reports it.
 */
efficiency: Directional<number>, 
/**
 * Speed and torque on each shaft — the grounded gear, the crank, the
 * output — in every load case, each distributed in its own direction.
 * The crank is the carrier of both meshes, and the shaft the load is
 * referred to.
 */
cases: Array<ShaftsCase>, 
/**
 * Angular backlash at whichever shaft is the **output**, degrees: gear 4
 * driving forward, the crank driving backward. The same two plays subtend
 * very different angles at the two, by exactly the reduction.
 */
backlash: Directional<Backlash>, meshes: [HulaMesh, HulaMesh], gears: [HulaGear, HulaGear, HulaGear, HulaGear], 
/**
 * **The axial contact ratio the stage comes to** — the smaller of its two
 * meshes', which is the one a given ratio is held to. What the stage's
 * `overlap` input shows while automatic.
 */
overlap: number, 
/**
 * Anything the stage had to say about the design, as every other stage kind
 * reports it. A note that names one gear rides on that gear instead — see
 * [`GearResult::notes`].
 */
notes: Array<Note>, };
