// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Backlash } from "./Backlash";

/**
 * One mesh of a solved drive.
 */
export type HulaMesh = { 
/**
 * Operating pressure angle, degrees.
 *
 * A one-tooth-difference pair opened far enough to clear itself runs at an
 * angle no ordinary pair would — above 50° on the shipped proportions —
 * which is a property of the arrangement rather than a fault, and is
 * reported for that reason.
 */
operating_pressure_angle: number, 
/**
 * Far-side tip gap, mm: the room the wobble body has on the side away from
 * the mesh, which is what the shift was spent on.
 */
clearance: number, 
/**
 * The same gap measured on the parts as cut, mm. It differs from the one
 * above only where a tip was clamped, and then the difference is what the
 * clamp cost.
 */
clearance_as_cut: number, contact_ratio: number, 
/**
 * The pinion's tip reaches past where the ring's flank ends.
 */
trochoid_interference: boolean, 
/**
 * The ring's tip reaches below where the pinion's flank ends.
 */
involute_interference: boolean, 
/**
 * Angular backlash at each member, degrees — the pinion's first, then the
 * ring's: nominal at the running offset, then at each end of the tolerance
 * band. The same gap subtends a different angle at each, so the two differ
 * whenever the tooth counts do.
 */
backlash: [Backlash, Backlash], };
