// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeshReport } from "./MeshReport";

/**
 * One mesh of a solved stage.
 *
 * [`MeshReport`] is what any parallel-axis mesh reports and is the same six
 * fields a planetary set's two meshes carry; what a hula pair adds is the room
 * it has — the far-side gap the shift was spent on, and the three ways its
 * teeth can foul.
 *
 * **The efficiency on the report is this pair's own, with the crank held** —
 * what the teeth lose, and nothing about the arrangement they sit in. It is
 * emphatically not the stage's: the two of them multiply to
 * [`HulaResult::fixed_carrier_efficiency`], and the stage's own is that figure
 * put through the reduction, which on a high-ratio arrangement takes a pair
 * losing under a percent to a stage losing tens of them
 * ([`HulaResult::efficiency`]).
 */
export type HulaMesh = { 
/**
 * The operating pressure angle, the three contact ratios, the efficiency,
 * the shared contact stress and the backlash at each member — the pinion
 * first, as the mesh was built.
 *
 * A one-tooth-difference pair opened far enough to clear itself runs at an
 * operating pressure angle no ordinary pair would — above 50° on the
 * shipped proportions — and its transverse contact ratio sits just above
 * continuous contact by construction, which is why a helical stage of this
 * kind has to buy its overlap axially.
 */
report: MeshReport, 
/**
 * Far-side tip gap, mm: the room the wobble body has on the side away from
 * the mesh, which is what the shift was spent on.
 */
clearance: number, 
/**
 * The same gap measured on the parts as cut, mm. It differs from the one
 * above only where a tip was clamped, and then the difference is what the
 * clamp cost.
 */
clearance_as_cut: number, 
/**
 * The pinion's tip reaches past where the ring's flank ends.
 */
trochoid_interference: boolean, 
/**
 * The ring's tip reaches below where the pinion's flank ends.
 */
involute_interference: boolean, 
/**
 * **The tips foul away from the line of action** — the condition that
 * decides a small tooth difference, where the tip circles cross far from
 * the line of centres and the mesh itself is perfectly conjugate.
 */
tip_interference: boolean, 
/**
 * How much room the tips have where their circles cross, as an angle of
 * pinion rotation, degrees. Negative is the overlap.
 */
tip_margin: number, };
