// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Auto } from "./Auto";
import type { Cutter } from "./Cutter";
import type { LoadSharing } from "./LoadSharing";
import type { Optimisation } from "./Optimisation";
import type { StageGear } from "./StageGear";

/**
 * A hula stage as its inputs describe it.
 */
export type HulaStage = { 
/**
 * Normal module of each mesh, mm. Two, because the pairs need not share
 * one — only the offset they run at.
 */
module: [number, number], 
/**
 * Normal pressure angle, degrees. Shared by both meshes.
 */
pressure_angle: number, 
/**
 * **The axial contact ratio** `ε_β` the stage is asked for, where it is
 * asked for one — the same input a pair has ([`super::PairStage::overlap`]),
 * asked of both meshes: a floor under every automatic face width, or,
 * with all four widths given, the thing that decides the helix, so that
 * the narrower of the two meshes reaches it.
 */
overlap: Auto<number>, 
/**
 * `k` for each mesh's **pinion**. Its ring takes the same figure, because
 * on a ring `k` describes the space, and a pinion and a ring that mesh
 * want the same one rather than complementary ones.
 */
thickness_mod: [number, number], 
/**
 * Coefficient of friction in each mesh.
 */
sliding_friction: [number, number], 
/**
 * Coefficient of **static** friction in each mesh, for breaking away.
 *
 * Whether a stage turns at all is decided at rest and against this; how
 * well it does once turning is decided against the sliding coefficient,
 * which is lower. See [`Directional::once_moving`].
 */
static_friction: [number, number], 
/**
 * The smallest far-side tip gap any mesh may run at, mm.
 *
 * A minimum, and checked whether or not the offset is taken from it: an
 * offset that fails it describes a stage that could be built and would
 * foul, which is a thing a designer is owed the number for rather than a
 * refusal.
 */
clearance: number, 
/**
 * Added to the crank offset, mm — the running clearance.
 *
 * **One number, because there is one crank.** Both meshes are separated by
 * the same distance by construction, so a clearance on each could be set
 * to disagree about a distance that is physically single.
 */
running_clearance: Auto<number>, tolerance_plus: number, tolerance_minus: number, 
/**
 * **The crank offset, or automatic.**
 *
 * The same shape every stage's centre distance has, because it is the same
 * decision: automatic derives the distance from the clearances the parts
 * have to keep, and a number given by hand is the distance to run at. The
 * arrangement below keeps its own vocabulary for that — [`Offset`] says
 * *what decides* the offset rather than how it was entered — and this is
 * the one place the two are translated.
 */
offset: Auto<number>, 
/**
 * What the stage is asked to optimise, and what it may not do to get
 * there. See [`Optimisation`].
 *
 * A pair's shift *sum* is fixed by the offset the crank has to reach, so
 * within a mesh only the division between ring and pinion is free — and
 * that division is worth real efficiency. The contact ratio defaults lower
 * here than the shared default, for a reason that is the stage's rather
 * than a relaxation of the rule: a mesh of one tooth of difference has a
 * very short path and sits just above continuous contact at every split it
 * can be built at, so a pair's usual 1.2 of design margin would forbid the
 * mechanism rather than constrain it.
 */
optimisation: Optimisation, 
/**
 * How the load is divided while two tooth pairs are engaged.
 *
 * **Off by default, and it reaches bending only** — see
 * [`super::PairStage::load_sharing`], which is the same input for the same
 * reason. One switch for the stage rather than one per mesh: it selects a
 * *model*, and a stage running two meshes under two different models of
 * the same thing would be reporting a comparison rather than a design.
 */
load_sharing: LoadSharing, 
/**
 * The shaper each mesh's ring is cut with.
 *
 * **A shaper has to be smaller than the ring it cuts**, and the rings here
 * are small: a tool larger than its workpiece is clamped down to the
 * ring's own count and then reaches none of its flank, leaving no fillet
 * at all. Both defaults are well below the default rings for that reason.
 */
cutter: [Cutter, Cutter], 
/**
 * The four gears, in [`Teeth`]'s order: the grounded one, the two that
 * ride the wobble body, then the output.
 */
gears: [StageGear, StageGear, StageGear, StageGear], };
