// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cutter } from "./Cutter";
import type { Offset } from "./Offset";
import type { Split } from "./Split";
import type { StageGear } from "./StageGear";

/**
 * A hula stage as its inputs describe it.
 */
export type HulaStage = { 
/**
 * Normal module of each mesh, mm. Two, because the pairs need not share
 * one — only the offset they run at.
 */
module: [number, number], 
/**
 * Normal pressure angle, degrees. Shared by both meshes.
 */
pressure_angle: number, 
/**
 * Helix angle, degrees. Shared.
 */
helix_angle: number, 
/**
 * `k` for each mesh's **pinion**. Its ring takes the same figure, because
 * on a ring `k` describes the space, and a pinion and a ring that mesh
 * want the same one rather than complementary ones.
 */
thickness_mod: [number, number], 
/**
 * The smallest far-side tip gap any mesh may run at, mm.
 *
 * A minimum, and checked whether or not the offset is taken from it: an
 * offset that fails it describes a drive that could be built and would
 * foul, which is a thing a designer is owed the number for rather than a
 * refusal.
 */
clearance: number, 
/**
 * Added to the crank offset, mm — the running clearance.
 *
 * **One number, because there is one crank.** Both meshes are separated by
 * the same distance by construction, so a clearance on each could be set
 * to disagree about a distance that is physically single.
 */
running_clearance: number, tolerance_plus: number, tolerance_minus: number, 
/**
 * What decides the crank offset.
 */
offset: Offset, 
/**
 * What decides each mesh's shift distribution.
 */
split: [Split, Split], 
/**
 * The shaper each mesh's ring is cut with.
 *
 * **A shaper has to be smaller than the ring it cuts**, and the rings here
 * are small: a tool larger than its workpiece is clamped down to the
 * ring's own count and then reaches none of its flank, leaving no fillet
 * at all. Both defaults are well below the default rings for that reason.
 */
cutter: [Cutter, Cutter], 
/**
 * The four gears, in [`Teeth`]'s order: the grounded one, the two that
 * ride the wobble body, then the output.
 */
gears: [StageGear, StageGear, StageGear, StageGear], };
