// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Note } from "./Note";

/**
 * One gear of a solved drive.
 */
export type HulaGear = { teeth: number, 
/**
 * Whether this member is the ring of its pair — an outcome of the tooth
 * counts rather than an input.
 */
ring: boolean, 
/**
 * The shift in force, after the split has been applied.
 */
profile_shift: number, pitch_radius: number, base_radius: number, 
/**
 * Tip radius, mm. **Smaller** than the pitch radius on a ring.
 */
tip_radius: number, 
/**
 * Root radius, mm. Larger than the pitch radius on a ring.
 */
root_radius: number, 
/**
 * Speed, rpm. Gear 1 is held, so its speed is zero; gears 2 and 3 share
 * the wobble body's.
 */
speed: number, 
/**
 * Anything clamped while this gear was built.
 */
clamps: Array<Note>, };
