// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A solved planetary layout.
 */
export type Layout = { 
/**
 * The planet thickness shift that makes the two centre distances agree.
 */
planet_shift: number, 
/**
 * The common centre distance, mm — sun-to-planet and planet-to-ring, which
 * are now the same number.
 */
centre_distance: number, 
/**
 * Operating pressure angle of the sun–planet mesh, radians.
 */
alpha_w_sun: number, 
/**
 * ...and of the planet–ring mesh.
 */
alpha_w_ring: number, 
/**
 * Residual `|a_ext − a_int|` at the returned shift, mm.
 *
 * Reported rather than asserted. It is the one number that says the solve
 * actually closed, and a caller that wants to trust the layout can look at
 * it instead of trusting this module.
 */
residual: number, 
/**
 * Planets can be spaced evenly around the sun: `(z_s + z_r) mod N = 0`.
 */
equal_spacing: boolean, 
/**
 * Every planet meshes at the same phase — `N | z_s` and `N | z_r`.
 *
 * Given equal spacing either implies the other. Rarely true, and its being
 * false is not a fault: it means the planets engage staggered, which is
 * usually preferable.
 */
simultaneous_meshing: boolean, 
/**
 * Gap between the tip circles of adjacent planets, mm.
 *
 * `2 a sin(π/N) − d_a,planet`. Negative means they overlap and the set
 * cannot be built. `None` for a single planet, which has no neighbour.
 */
planet_clearance: number | null, };
