// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the layout of one replicated axis came to.
 */
export type LayoutReport = { 
/**
 * The axis, as [`Shape::axes`] numbers them.
 */
axis: number, count: number, 
/**
 * Whether `N` equally spaced instances assemble: `Some` where the
 * arrangement is one the rule is known for — one gear on the axis
 * meshing two central members.
 */
equal_spacing: boolean | null, simultaneous_meshing: boolean | null, 
/**
 * The least tip-to-tip gap, mm, between one instance and another
 * planet it does not mesh: its neighbours on this axis, and the
 * instances of any axis it meshes on the same carrier, bar its own
 * mate — placed at their stagger ([`DistanceReport::stagger`]).
 */
clearance: number, clearance_ok: boolean, };
