// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the layout of one replicated axis came to.
 */
export type LayoutReport = { 
/**
 * The axis, as [`Shape::axes`] numbers them.
 */
axis: number, count: number, 
/**
 * Whether `N` equally spaced instances assemble: `Some` where the
 * arrangement is one the rule is known for — one gear on the axis
 * meshing two central members.
 */
equal_spacing: boolean | null, simultaneous_meshing: boolean | null, 
/**
 * Tip-to-tip gap between neighbouring instances, mm.
 */
clearance: number, clearance_ok: boolean, };
