// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContactRatios } from "./ContactRatios";

/**
 * What only a line contact reports: the transverse plane's own figures.
 */
export type LineContact = { 
/**
 * Transverse operating pressure angle `α_w`, degrees — the zero-backlash
 * pair's, which the profile shifts set. A point contact has no
 * operating angle: its normal cannot turn, so its normal pressure angle
 * is `α_n` at any shift.
 */
operating_pressure_angle: number, 
/**
 * The contact ratio decomposed: transverse, overlap and their total,
 * which is [`MeshReport::contact_ratio`].
 */
contact_ratios: ContactRatios, };
