// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **What a case says a port is.** A port the case does not mention has a
 * default — the chain's two ends are reacted, every other open port is
 * free — and an entry says otherwise, or says the default in so many
 * words.
 */
export type LoadRole = "load" | "reacted" | "free";
