// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Auto } from "./Auto";
import type { LoadRole } from "./LoadRole";

/**
 * One port of the train as a case declares it: a load, or a reaction or a
 * free port said in so many words.
 */
export type Load = { at: number, 
/**
 * What the port is. The two figures below are read only for a load,
 * and kept while the port is reacted or free for the reason
 * [`Auto::manual`] is kept while automatic: switching back finds them
 * where they were.
 */
role: LoadRole, 
/**
 * N·m, given or derived from the other loads through the flow.
 */
torque: Auto<number>, 
/**
 * rpm, given or derived from the other loads through the motion. A
 * given nought is a load held still; the flow then takes its direction
 * from the torque's sign.
 */
speed: Auto<number>, };
