// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaseKind } from "./CaseKind";
import type { Duty } from "./Duty";
import type { Load } from "./Load";

/**
 * One load the train is rated for: a torque, where it enters, what holds it,
 * and which allowable it is judged against.
 *
 * Named for the engineering term — a defined set of loads applied for analysis
 * — and deliberately *not* for a duty cycle, which is a fraction of time spent
 * running and a different idea with different implications. A fatigue case
 * carries one of those as [`Self::duty`]; the case is not it.
 *
 * A train carries any number of these, as it carries any number of stages,
 * and for the same reason: the two loads it used to hold — a peak at the input
 * and a back-driving one at the output — were the first two entries of this
 * list with their ports and directions written into the field names. A case
 * applied at the far end is not a sign on one applied at the near end; it is
 * the same kind of thing entering elsewhere, and [`Port`] is what says where.
 */
export type LoadCase = { kind: CaseKind, 
/**
 * A case switched off takes part in no rating and no sizing, and its
 * inputs stand, so it can be switched back on as it was; what it comes
 * to at the train level is still reported ([`TrainCase`]).
 */
enabled: boolean, 
/**
 * **The loads on the train's open ports.** The chain's two ends, where
 * the case does not load them, are *reacted*: each turns as the motion
 * says and carries the torque the flow puts on it, and both are
 * reported — a reaction the designer cares about, where a shaft the
 * train fixes is ground and reports no speed ([`ShaftRole`]). Every
 * other open port the case does not load is *free* — it turns and
 * carries nothing, since a reaction there is a thing a designer
 * attaches and says so by loading it. A load carries a torque and a
 * speed, each given or derived: the train has some mobility `m` under
 * what it fixes, exactly `m` of the loads' speeds decide the motion,
 * the torques on the loads and the reacted ends are `m` short of all
 * given, and the rest follow ([`Train::relieve_case`] keeps it so).
 */
loads: Array<Load>, 
/**
 * The duty a fatigue case is spent over. Read by a fatigue case alone —
 * an ultimate load is survived once and has no cycles to count — and kept
 * while the case is ultimate for the reason [`Auto::manual`] is kept while
 * automatic: switching the kind back finds it where it was.
 */
duty: Duty, };
