// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A quantity evaluated for each **load case** the train describes.
 *
 * Named for the engineering term — a defined set of loads applied for analysis
 * — and deliberately *not* for a duty cycle, which is a fraction of time spent
 * running and a different idea with different implications. One of this train's
 * inputs genuinely is that; these are not it.
 *
 * The two differ in one thing beyond their torque, and it is the thing that
 * matters: **which allowable they are rated against.** A peak load has to be
 * survived once, so it is judged against the ultimate; a cyclic one has to be
 * survived indefinitely, so it is judged against the fatigue figure. Rating a
 * peak against a fatigue allowable — which is what this crate did before the
 * two cases existed — asks the wrong question and answers it confidently.
 *
 * Built through [`LoadCase::of`] for the same reason [`Directional`] is: there
 * is no path by which a stage reports one case and not the other.
 */
export type LoadCase<T> = { 
/**
 * The worst single application: survive it once.
 */
peak: T, 
/**
 * The load it runs at: survive it for the duty.
 */
cyclic: T, };
