// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Auto } from "./Auto";
import type { Port } from "./Port";

/**
 * One load on one open port of the train.
 */
export type Load = { at: Port, 
/**
 * N·m, given or derived from the other loads through the flow. A given
 * nought is a port that turns freely and carries nothing — what a load
 * nothing holds comes to.
 */
torque: Auto<number>, 
/**
 * rpm, given or derived from the other loads through the motion. A
 * given nought is a load held still; the flow then takes its direction
 * from the torque's sign.
 */
speed: Auto<number>, };
