// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **The load ratio a fatigue figure was measured at**, `R = σ_min/σ_max`.
 *
 * A root loaded one way sees `R = 0`; one loaded on both flanks sees about
 * `R = −1`. A fatigue figure measured at one ratio is not the allowable at the
 * other, so which one a figure is decides what a reversed root is judged
 * against ([`Material::reversed_bending_fraction`]).
 */
export type LoadRatio = "reversed" | "pulsating";
