// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaseKind } from "./CaseKind";
import type { Duty } from "./Duty";
import type { Port } from "./Port";

/**
 * One load the train is rated for: a torque, where it enters, what holds it,
 * and which allowable it is judged against.
 *
 * Named for the engineering term — a defined set of loads applied for analysis
 * — and deliberately *not* for a duty cycle, which is a fraction of time spent
 * running and a different idea with different implications. A fatigue case
 * carries one of those as [`Self::duty`]; the case is not it.
 *
 * A train carries any number of these, as it carries any number of stages,
 * and for the same reason: the two loads it used to hold — a peak at the input
 * and a back-driving one at the output — were the first two entries of this
 * list with their ports and directions written into the field names. A case
 * applied at the far end is not a sign on one applied at the near end; it is
 * the same kind of thing entering elsewhere, and [`Port`] is what says where.
 */
export type LoadCase = { kind: CaseKind, 
/**
 * A case switched off takes part in nothing — no rating, no sizing, no
 * readout — and its inputs stand, so it can be switched back on as it was.
 */
enabled: boolean, port: Port, 
/**
 * **Whether the far end holds the load.** On, the load is carried through
 * every stage to the far port, attenuated by each stage's efficiency in
 * its direction of travel — a motor's torque delivered to the output, or a
 * brake at the motor holding an output load through every mesh. Off, only
 * a stage that cannot be driven that way holds it, and a train with no
 * such stage simply turns under it and carries none of it
 * (`docs/rationale.md#a-load-exists-only-where-it-is-reacted`). Either way
 * a stage that locks in the direction of travel holds the load where it
 * stands, and nothing beyond it sees any.
 */
reacted: boolean, 
/**
 * N·m at the port.
 */
torque: number, 
/**
 * rpm at the port. Zero is a load held still.
 */
speed: number, 
/**
 * The duty a fatigue case is spent over. Read by a fatigue case alone —
 * an ultimate load is survived once and has no cycles to count — and kept
 * while the case is ultimate for the reason [`Auto::manual`] is kept while
 * automatic: switching the kind back finds it where it was.
 */
duty: Duty, };
