// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One of a load's two figures, named so a caller can say which was
 * just touched.
 */
export type LoadFreedom = "torque" | "speed";
