// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the load is divided when two tooth pairs are in contact.
 */
export type LoadSharing = "none" | "linear_ramp";
