// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Family } from "./Family";
import type { LoadRatio } from "./LoadRatio";
import type { Measure } from "./Measure";
import type { Specimen } from "./Specimen";
import type { Value } from "./Value";

/**
 * A material, as the calculator sees it.
 *
 * Lengths are millimetres and stresses megapascals throughout the crate, but
 * **density is SI** (kg/m³) per the unit rule in `docs/reference.md#materials`: SI
 * internally except where the domain's own convention is unambiguous.
 */
export type Material = { 
/**
 * Display name, and the key the library is looked up by.
 */
name: string, class: Family, 
/**
 * The specific product or condition the numbers describe. A generic name
 * like "PA6" is not a material; some particular grade was measured, and
 * this says which.
 */
grade: string, 
/**
 * Heat treatment, moisture state, or temper the values apply to.
 */
condition: string, 
/**
 * Where the numbers came from, precisely enough to check them.
 */
source: string, 
/**
 * kg/m³.
 */
density: Value, 
/**
 * MPa.
 */
elastic_modulus: Value, 
/**
 * Dimensionless.
 */
poissons_ratio: Value, 
/**
 * MPa. The limit on a **peak** load — see the module documentation.
 */
ultimate_allowable: Value, 
/**
 * What `ultimate_allowable` measures: yield, or break for materials with
 * no yield point. The ultimate contact rating reads it: first yield below
 * a flank is `C·σ_y` ([`crate::hertz::first_yield_factor`]) and has no
 * reading from a stress at break.
 */
ultimate_measure: Measure, 
/**
 * MPa. The limit on a **cyclic** load.
 */
fatigue_allowable: Value, 
/**
 * The load ratio [`Self::fatigue_allowable`] was measured at. `None` where
 * the source does not say, which a reversed root reads as `R = 0` —
 * the lower allowable — and says so.
 */
fatigue_load_ratio?: LoadRatio | null, 
/**
 * What [`Self::fatigue_allowable`] was measured on. `None` where the
 * source does not say.
 */
fatigue_specimen?: Specimen | null, 
/**
 * MPa. The limit on a **cyclic contact pressure** — a flank's pitting
 * endurance, ISO 6336-5's `σ_Hlim` or a figure measured like it. A
 * different figure from [`Self::fatigue_allowable`], which is a root's.
 * **`None` where nothing publishes one**: contact fatigue is then not
 * judged, and the rating says so rather than borrowing a number.
 */
contact_fatigue_allowable?: Value | null, };
