// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Family } from "./Family";
import type { Measure } from "./Measure";
import type { Value } from "./Value";

/**
 * A material, as the calculator sees it.
 *
 * Lengths are millimetres and stresses megapascals throughout the crate, but
 * **density is SI** (kg/m³) per the unit rule in `docs/reference.md#materials`: SI
 * internally except where the domain's own convention is unambiguous.
 */
export type Material = { 
/**
 * Display name, and the key the library is looked up by.
 */
name: string, class: Family, 
/**
 * The specific product or condition the numbers describe. A generic name
 * like "PA6" is not a material; some particular grade was measured, and
 * this says which.
 */
grade: string, 
/**
 * Heat treatment, moisture state, or temper the values apply to.
 */
condition: string, 
/**
 * Where the numbers came from, precisely enough to check them.
 */
source: string, 
/**
 * kg/m³.
 */
density: Value, 
/**
 * MPa.
 */
elastic_modulus: Value, 
/**
 * Dimensionless.
 */
poissons_ratio: Value, 
/**
 * MPa. The limit on a **peak** load — see the module documentation.
 */
ultimate_allowable: Value, 
/**
 * What `ultimate_allowable` measures: yield, or break for materials with
 * no yield point.
 */
ultimate_measure: Measure, 
/**
 * MPa. The limit on a **cyclic** load.
 */
fatigue_allowable: Value, };
