// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Material } from "./Material";

/**
 * A set of materials, in presentation order.
 */
export type MaterialLibrary = { material: Array<Material>, };
