// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which quantity the ultimate allowable actually measures.
 *
 * Not cosmetic. Unfilled polymers and ductile metals yield before they break,
 * so their datasheets report a yield stress. Glass-filled grades have no yield
 * point at all — they break first — so their datasheets report stress at
 * break. Recording which one is in the field keeps the number comparable to
 * its own source instead of silently relabelled.
 */
export type Measure = "yield" | "break";
