// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberRole } from "./MemberRole";

/**
 * A member's role, numbered where the shape has more than one of it.
 */
export type MemberName = { role: MemberRole, 
/**
 * `1`, `2`, … where the role is shared, `None` where it is not.
 */
ordinal: number | null, };
