// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a member is, as a designer names it — read off the shape by
 * [`Shape::member_names`], so the harness and the panel name a member the
 * same way from one rule.
 */
export type MemberRole = "gear" | "worm" | "wheel" | "sun" | "planet" | "ring";
