// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One of a member's constrainable inputs.
 *
 * A helix here is one reading of **the size of the stage's teeth along the
 * axis**: every member's is bound to the others', so a pair's first member
 * is as big as its helix makes it, which is what absorbs a centre distance
 * once both shifts are pinned.
 */
export type MemberFreedom = "shift" | "helix" | "face_width";
