// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Auto } from "./Auto";
import type { Cutter } from "./Cutter";
import type { StageGear } from "./StageGear";

/**
 * A gear, on a shaft.
 */
export type Member = { 
/**
 * The shaft it spins with, numbered as [`ShaftOn`] is.
 */
shaft: number, gear: StageGear, 
/**
 * Normal module, mm. Every mesh a member is in shares it.
 */
module: number, 
/**
 * Tooth-thickness coefficient, `k`: above 1 this gear's teeth thicken.
 * **Given on one member of a mesh and automatic on the other**, which
 * follows the mesh's rule — the two sum to 2 across an external mesh, a
 * ring takes its pinion's — and relief keeps it so
 * ([`Shape::thickness_mods`]). Every member automatic is `k = 1`.
 */
thickness_mod: Auto<number>, 
/**
 * **A ring is a gear cut by a pinion cutter.** `Some` makes this member
 * internal, and every mesh it is in an internal one.
 */
ring: Cutter | null, 
/**
 * The pitch diameter as a reading of the helix — `cos β = z m_n / d` —
 * which is a worm's way of stating its size.
 */
pitch_diameter: Auto<number>, };
