// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Two members in mesh, and what the mesh owns.
 */
export type MeshInput = { 
/**
 * Indices into [`Shape::members`]. On an internal mesh `b` is the ring.
 */
a: number, b: number, sliding_friction: number, static_friction: number, };
