// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Backlash } from "./Backlash";
import type { ContactRatios } from "./ContactRatios";
import type { Directional } from "./Directional";
import type { LoadCase } from "./LoadCase";

/**
 * What one of the two meshes did.
 */
export type MeshReport = { contact_ratios: ContactRatios, 
/**
 * Mesh efficiency, both drive senses. Equal for a parallel-axis pair, and
 * arrived at rather than copied.
 */
efficiency: Directional<number>, 
/**
 * Hertzian contact stress, MPa — shared by the pair, in both load cases.
 */
contact_stress: LoadCase<number>, 
/**
 * Relative radius of curvature at the governing point, mm.
 */
relative_radius: number, 
/**
 * Angular backlash at each member, degrees: the first is the pinion-side
 * member (sun, then planet), the second the other.
 */
backlash: [Backlash, Backlash], };
