// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Auto } from "./Auto";
import type { LoadSharing } from "./LoadSharing";

/**
 * Two members in mesh, and what the mesh owns.
 */
export type MeshInput = { 
/**
 * Indices into [`Shape::members`]. On an internal mesh `b` is the ring.
 */
a: number, b: number, sliding_friction: number, static_friction: number, 
/**
 * **The axial contact ratio** `ε_β` this mesh is asked for — a floor
 * under an automatic face width, or, with every width of its mesh
 * group given, the thing that decides the group's helix (the group's
 * first mesh's is the reading; the rest of the group carry the same
 * number, written by the panel). Absent in a file, automatic at one.
 */
overlap: Auto<number>, 
/**
 * **The transverse contact ratio the efficiency search may not take
 * this mesh below** ([`super::DEFAULT_MIN_CONTACT_RATIO`] where a file
 * gives none) — each mesh's own, since a pair that must stay
 * continuous by more than its neighbour should not have its neighbour
 * held to the same. Bounds the optimiser only.
 */
min_contact_ratio: number, 
/**
 * **How the load is shared between tooth pairs in contact** on this
 * mesh — a model of one contact, so a mesh's own: two meshes on one
 * member can be rated under different ones. Absent in a file, none,
 * which is what every file written before it meant.
 */
load_sharing: LoadSharing, 
/**
 * **Choose this mesh's automatic shifts for efficiency** rather than
 * for undercut, the undercut shift then a floor rather than the answer
 * (docs/reference.md#efficiency-parallel-axes).
 *
 * **The search's unit is not the mesh but its component** — the meshes
 * a free member is shared between, and every mesh on an automatic
 * distance an absorber ties together ([`Shape::search_components`]):
 * a planet's shift moves both its meshes. So a component is searched
 * where *any* of its meshes asks, and a component none of whose
 * meshes asks keeps its undercut shifts. What is given constrains the
 * search rather than being overruled by it. Absent in a file, not
 * asked.
 */
search: boolean, };
