// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Auto } from "./Auto";

/**
 * Two members in mesh, and what the mesh owns.
 */
export type MeshInput = { 
/**
 * Indices into [`Shape::members`]. On an internal mesh `b` is the ring.
 */
a: number, b: number, sliding_friction: number, static_friction: number, 
/**
 * **The axial contact ratio** `ε_β` this mesh is asked for — a floor
 * under an automatic face width, or, with every width of its mesh
 * group given, the thing that decides the group's helix (the group's
 * first mesh's is the reading; the rest of the group carry the same
 * number, written by the panel). Absent in a file, automatic at one.
 */
overlap: Auto<number>, 
/**
 * **The transverse contact ratio the efficiency search may not take
 * this mesh below** ([`super::DEFAULT_MIN_CONTACT_RATIO`] where a file
 * gives none) — each mesh's own, since a pair that must stay
 * continuous by more than its neighbour should not have its neighbour
 * held to the same. Bounds the optimiser only.
 */
min_contact_ratio: number, };
