// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContactPatch } from "./ContactPatch";

/**
 * What one load case does to one mesh.
 */
export type MeshCase = { 
/**
 * Index into the train's list of load cases.
 */
case: number, contact: ContactPatch, 
/**
 * Sliding speed at the pitch point, mm/s, at this case's speed — exactly
 * zero on parallel shafts, where [`MeshReport::sliding_ratio`] is.
 */
sliding_velocity: number, };
