// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Backlash } from "./Backlash";
import type { Directional } from "./Directional";
import type { LineContact } from "./LineContact";
import type { MeshCase } from "./MeshCase";
import type { Note } from "./Note";
import type { PointContact } from "./PointContact";
import type { TipRoom } from "./TipRoom";

/**
 * **What one mesh reports**, whatever stage it is in and whichever way its
 * shafts run.
 *
 * One type, because the physics is one model with the shaft angle as a
 * parameter and not two models: the Hertz answer is general contact of which a
 * line is the degenerate value ([`crate::hertz::peak_pressure`]), the
 * efficiency is one friction balance the parallel loss integral is the limit
 * of, the backlash is one gap projected onto one normal, and the interference
 * verdict is one relation asked in the transverse plane or along the line —
 * each of which a test holds at the limit. So a designer turning a shaft
 * angle from zero sees the same rows with the numbers moving, not a readout
 * changing shape. What a line contact has that a point does not, and the other
 * way, is the little in [`LineContact`] and [`PointContact`]: the transverse
 * decomposition of the contact ratio and the operating angle on one side; the
 * face-limited zone and the parallel counterpart on the other. Bending is
 * the members' and stays on [`GearResult`], `None` on a point contact for the
 * reason `docs/rationale.md#a-worm-stage-reports-no-bending-stress` gives.
 *
 * A set's `sun_planet`/`planet_ring` and a hula stage's two pairs are the
 * same report, which is why it is one type; a pair's one mesh is on its own
 * result. This used to be the parallel-axis report only, with a crossed pair's
 * in a type of its own beside it and an enum choosing between them.
 */
export type MeshReport = { 
/**
 * Whether the two members' tooth counts share no factor — a hunting pair,
 * which spreads wear evenly instead of repeatedly bringing the same two
 * teeth together.
 *
 * A property of a *mesh*, which is why it is here: a pair reports one
 * (its one mesh being the stage), and a set with two meshes has two
 * answers. An epicyclic set's separate question — each central member
 * against the *planet count* — is a different check with a different
 * reason, and it stays where it is.
 */
coprime: boolean, 
/**
 * **Tooth pairs sharing the load.** A line contact's total, `ε_α + ε_β`;
 * a point contact's along its line of action, the zone over the normal
 * base pitch, as the face widths in use leave it. Below 1 the mesh loses
 * contact between one pair and the next, on either.
 *
 * The two are the same *count* and not the same measure, which is the
 * one place the two contacts do not meet continuously: a line counts
 * lines across the face, a point counts points along one line, and the
 * point's limit as the shafts straighten is the normal-plane `ε_α / cos²β_b`
 * rather than the total. The decomposition each has is in [`Self::line`]
 * and [`Self::point`].
 */
contact_ratio: number, 
/**
 * Mesh efficiency, both drive senses. Equal for a parallel-axis mesh — the
 * mirror flank is the same integral — and genuinely different on crossed
 * shafts, where **either** can be zero or negative: backward is what
 * self-locking is, forward a steep helix split that cannot drive at all.
 * [`Directional::locked`] reads them rather than a separate flag that
 * could disagree.
 */
efficiency: Directional<number>, 
/**
 * The coefficient of friction at which each direction stops driving,
 * read along the path; a **negative** value means no friction locks the
 * pair that way — a value rather than a missing one.
 *
 * Negative both ways on every line contact, and deliberately not the
 * number its loss model extrapolates to. That model is first order in
 * `μ` ([`crate::contact::efficiency`]), so it reaches zero at
 * `μ / (1 − η)` — about 5 on the shipped pair — which is nowhere the
 * model describes: the friction balance a hundredth of a degree off
 * parallel puts the threshold at half that, and asymmetric. What is true
 * within the model is that no friction near unity locks a parallel mesh,
 * and *never* is the honest reading of that.
 */
locking_friction: Directional<number>, 
/**
 * Sliding speed at the pitch point as a multiple of the first member's
 * pitch line speed — the lengthwise sliding crossed shafts have, and
 * **exactly zero** on parallel ones, where the pitch point is the one
 * place with no sliding at all and every loss is along the profile.
 */
sliding_ratio: number, 
/**
 * **What every load case does to this mesh**: the Hertzian contact — one
 * patch the two members share, an ellipse on crossed shafts and a line on
 * parallel ones — and the sliding speed at that case's speed.
 */
cases: Array<MeshCase>, 
/**
 * Angular backlash at each member, degrees, in the order the mesh was
 * built: the pinion-side member first, then the other.
 */
backlash: [Backlash, Backlash], 
/**
 * **Whether each member's flank is reached past its usable end** by the
 * other member's tip, in the order the mesh was built.
 *
 * The classical interference condition, and it belongs to **every** mesh.
 * An internal pair had it under two names — *involute* interference when
 * the ring's tip reaches below where the pinion's flank ends, which is
 * `[0]`, and *trochoid* when the pinion's tip reaches into the ring's
 * fillet, which is `[1]` — and an external pair had it under none, though a
 * long addendum on a small pinion is exactly where it bites. A crossed
 * pair asks it along its line of action
 * ([`crate::screw::CrossedPath::flank_interference`]).
 */
flank_interference: [boolean, boolean], 
/**
 * **Where an internal mesh's tips are**, and `None` for an external one,
 * which has no such question: an external pair's tip circles cross on the
 * line of centres or not at all.
 */
tips: TipRoom | null, 
/**
 * **What this mesh has to say**, on every kind alike: contact that does not
 * stay continuous, a helical pair without full axial overlap, a sharing
 * model that is extrapolating, a screw pair that locks or nearly does,
 * or one that loses more than it keeps. A set has two meshes and says
 * which, which a note on the stage could not.
 */
notes: Array<Note>, 
/**
 * What a line contact has and a point does not.
 */
line: LineContact | null, 
/**
 * What a point contact has and a line does not.
 */
point: PointContact | null, };
