// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Exact } from "./Exact";
import type { OpenPort } from "./OpenPort";
import type { ShaftRef } from "./ShaftRef";
import type { ShaftReport } from "./ShaftReport";
import type { TrainBody } from "./TrainBody";

/**
 * **The train's motion as the front end receives it** — present whenever the
 * tooth counts and topology give one, which is whether or not the geometry
 * solved.
 */
export type MotionReport = { 
/**
 * How many independent conditions the mechanism needs beyond its frame
 * — 1 for a chain, 2 for a set with nothing held.
 */
mobility: number, 
/**
 * How many it has been given, so a panel can say *one short* or *one
 * too many* rather than leaving a designer to count.
 */
constrained: number, 
/**
 * Shafts no mesh touches — named, not counted. Ground is the frame and
 * is not listed.
 */
untouched: Array<ShaftRef>, shafts: Array<ShaftReport>, 
/**
 * One per stage, input over output. `None` where the output does not
 * turn.
 */
ratios: Array<Exact | null>, 
/**
 * The first stage's input to the last stage's output. `None` where the
 * answer is a family, since a quotient of two families is not a number.
 */
total: Exact | null, 
/**
 * **The shafts whose turn parameterises a family** — one per condition
 * the train is short — and empty where the answer is one answer. Every
 * [`ShaftReport::terms`] is per turn of one of these.
 */
free: Array<ShaftRef>, 
/**
 * Shafts whose condition said nothing the structure had not already
 * said. Not a fault — a ring held and also coupled to ground is a
 * designer being explicit — but worth a reader's knowing.
 */
redundant: Array<ShaftRef>, 
/**
 * Every shaft a load can enter by, named — what a load case's picker
 * offers, in the order the chain runs.
 */
ports: Array<OpenPort>, 
/**
 * **The train's bodies**: every port of every stage, with the shafts
 * the couplings make one of it — what a load case has a row for.
 */
bodies: Array<TrainBody>, };
