// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One thing worth saying about a result, as a key and its values.
 *
 * Render it with `gear_io::strings`, or in the browser from the catalogue
 * `gear_wasm::strings` serves.
 */
export type Note = { 
/**
 * Stable identifier for the message. Never shown to anyone.
 */
key: string, 
/**
 * Values the message interpolates, already formatted. `BTreeMap` so the
 * serialised form is stable and two equal notes compare equal.
 */
values: { [key in string]: string }, };
