// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Edit } from "./Edit";
import type { Note } from "./Note";
import type { StagePreset } from "./StagePreset";

/**
 * **One edit a piece offers**, and why it would be refused, where it would.
 */
export type Offer = { edit: Edit, 
/**
 * The preset an [`Edit::Insert`] lays in, for a menu to name it by.
 */
preset: StagePreset | null, 
/**
 * The refusal's catalogue key ([`super::EditRefused::key`]).
 */
refused: Note | null, };
