// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What decides the crank offset — the one distance both meshes run at.
 *
 * The offset is the stage's own quantity rather than either mesh's, which is
 * why it is named once here and not twice in the pairs.
 */
export type Offset = { "given": number } | "clearance";
