// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BodyLabel } from "./BodyLabel";

/**
 * A body a load can enter the train by, with the name of its first end.
 */
export type OpenPort = { body: number, 
/**
 * The first stage the body is listed on, and what it is there.
 */
stage: number, label: BodyLabel, };
