// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Port } from "./Port";
import type { ShaftLabel } from "./ShaftLabel";
import type { ShaftRef } from "./ShaftRef";

/**
 * A shaft a load can enter the train by, with the name it answers to.
 */
export type OpenPort = { 
/**
 * `Start` or `End` where the chain names it, else the shaft itself.
 */
port: Port, at: ShaftRef, label: ShaftLabel, };
