// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShaftLabel } from "./ShaftLabel";
import type { ShaftRef } from "./ShaftRef";

/**
 * A shaft a load can enter the train by, with its name.
 */
export type OpenPort = { at: ShaftRef, label: ShaftLabel, };
