// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **What a stage is asked to optimise, and what it may not do to get there.**
 *
 * Every stage with shifts to choose carries the same two decisions, and they
 * were the same two fields written out three times — which is three places to
 * edit, three serde defaults to keep in step, and a fourth stage away from
 * being four. The searches differ in what is free and what it is worth; this
 * does not differ at all.
 */
export type Optimisation = { 
/**
 * **Choose the automatic shifts for efficiency rather than for undercut.**
 *
 * Off, so a stage answers as it always has. On, the shifts a designer has
 * left automatic are chosen to make the stage lose least, with the undercut
 * shift as a *floor* rather than as the answer
 * (docs/reference.md#efficiency-parallel-axes).
 *
 * What is already given constrains it rather than being overruled by it: a
 * manual shift is that gear's, and a manual centre distance or crank offset
 * fixes a shift sum. Enough of them leave nothing to choose, which is a
 * design fully specified rather than an error.
 */
enabled: boolean, };
