// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-use replacements for a material's properties.
 *
 * The specification asks for every material property to be editable beside the
 * dropdown, so a value can be tweaked for one design without authoring a whole
 * library file. `None` means "whatever the library says".
 *
 * These live in the **input** state rather than in the library, which is what
 * keeps `docs/rationale.md#inputs-are-the-only-state` intact: the library stays the shipped reference,
 * outputs stay a pure function of inputs, and nothing is written back except by
 * an explicit export.
 */
export type Overrides = { density: number | null, elastic_modulus: number | null, poissons_ratio: number | null, ultimate_allowable: number | null, fatigue_allowable: number | null, };
