// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadRatio } from "./LoadRatio";
import type { Specimen } from "./Specimen";

/**
 * Per-use replacements for a material's properties.
 *
 * The specification asks for every material property to be editable beside the
 * dropdown, so a value can be tweaked for one design without authoring a whole
 * library file. `None` means "whatever the library says".
 *
 * These live in the **input** state rather than in the library, which is what
 * keeps `docs/rationale.md#inputs-are-the-only-state` intact: the library stays the shipped reference,
 * outputs stay a pure function of inputs, and nothing is written back except by
 * an explicit export.
 */
export type Overrides = { density: number | null, elastic_modulus: number | null, poissons_ratio: number | null, ultimate_allowable: number | null, fatigue_allowable: number | null, 
/**
 * The load ratio a replaced fatigue figure was measured at. A replaced
 * figure does not inherit the library's: `None` here, with the figure
 * replaced, is a figure whose ratio nobody stated.
 */
fatigue_load_ratio: LoadRatio | null, 
/**
 * What a replaced fatigue figure was measured on, likewise.
 */
fatigue_specimen: Specimen | null, 
/**
 * A flank's contact endurance, replacing the library's or standing where
 * it has none.
 */
contact_fatigue_allowable: number | null, };
