// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CrossedMesh } from "./CrossedMesh";
import type { MeshReport } from "./MeshReport";

/**
 * **What a pair's one mesh reports** — the line contact of parallel axes, or
 * the point contact of crossed ones.
 *
 * The one place a pair's result branches, and it branches because the physics
 * does: parallel axes touch along a line, carry a bending rating and lose
 * power to sliding along the profile; crossed axes touch at a point, have no
 * honest bending figure, slide lengthwise and differ in the two directions.
 * What the two have in common is read through the accessors below, so the
 * train — and a front end's summary row — never asks which it is holding.
 */
export type PairMesh = { "kind": "line" } & MeshReport | { "kind": "point" } & CrossedMesh;
