// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **Which pair this is, to a designer** — the layer over [`PairStage`] that
 * a preset is.
 *
 * The model underneath is one model: a worm is a helical gear with a few
 * starts at a steep helix, its wheel a helical gear at the complementary one,
 * and their mesh the crossed-axis mesh any two such gears have. What the kind
 * decides is the little that is not geometry:
 *
 * - **the preset** — `Spur` starts as 17/43 on parallel shafts, `Worm` as a
 *   single start of 7 mm at a right angle to a 40-tooth brass wheel;
 * - **the automatic face width** where no rating sizes one — a worm and its
 *   wheel take the conventional proportions of a worm drive
 *   ([`super::crossed::proportions`]), a crossed gear pair the width at which
 *   contact is just continuous;
 * - **the words** — *starts*, *worm*, *wheel* — which the shape reads off
 *   the same flag ([`super::shape::Shape::member_names`]).
 *
 * Nothing in it is a constraint the model needs: a `Worm` at a shaft angle of
 * zero is a legal, if strange, helical pair and solves as one. On the shape
 * it is one bit, `Distance::worm`; this enum exists so a preset is built
 * by a name rather than a boolean, and nothing in the core reads it — the
 * two constructors that take it write the bit and are done.
 */
export type PairKind = "spur" | "worm";
