// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Auto } from "./Auto";
import type { LoadSharing } from "./LoadSharing";
import type { Optimisation } from "./Optimisation";
import type { StageGear } from "./StageGear";

/**
 * A stage of two gears on shafts at any angle.
 *
 * Spur when nothing is angled, helical when the teeth are, a **crossed gear
 * pair** when the shafts are, and a **worm stage** when the first member's
 * size is a diameter someone chose — one stage, as the specification has it,
 * with the shaft angle and which reading of the size is given as the inputs
 * that distinguish them. It
 * is not four types of stage: the tooth counts, the module, the shifts, the
 * materials and the tolerances mean the same thing throughout, and only the
 * *mesh* differs.
 *
 * # The two helix angles come from the shaft angle
 *
 * `β₁ + β₂ = Σ` — the relation crossed-axis screw gearing runs on
 * (docs/reference.md#crossed-axes) — so one number places them, and it can be
 * stated three ways: either member's helix angle, or the first member's
 * pitch diameter, since `d = z m_n / cos β` makes a diameter and a helix the
 * same freedom read as a size. Which reading a designer uses is the whole of
 * the difference between a worm and a crossed gear: a worm's pitch diameter
 * is a *free choice* that sets its lead angle, its efficiency and whether it
 * can be back-driven, while a gear's follows from its teeth. At `Σ = 0` it is
 * a parallel helical pair with its two hands opposed; the parallel case is
 * the shaft angle's zero rather than a separate construction.
 *
 * [verified: a `Screw` built with `d₁ = z₁ m_n / cos β₁` reports
 * `γ₁ = 90° − β₁` exactly, and `β₂ = Σ − β₁`, over three tooth pairs × four
 * shaft angles × three helix angles.]
 *
 * What *does* branch is the mesh, and it must: parallel axes touch along a
 * line and lose power to sliding along the profile, while crossed axes touch
 * at a point and slide lengthwise. Those are different mechanisms with
 * different formulas and different results (docs/reference.md#crossed-axes),
 * so a crossed pair's mesh report carries a contact ratio along the line of
 * action, no bending and two efficiencies — in the same [`super::MeshReport`]
 * a parallel pair's does, with [`super::PointContact`] where the other has
 * [`super::LineContact`].
 *
 * # One relation among five inputs
 *
 * The centre distance, the clearance, the two shifts and the size are bound
 * by `a = a₀(size, x₁ + x₂) + clearance`, so four of the five may be given and
 * the fifth follows — [`super::Stage::freedoms`] says so for every kind of
 * pair alike. Which one absorbs a given distance is a preference, not a law:
 * the shifts do wherever one of them is automatic, and the size only when
 * both shifts are pinned, because a shift moves the teeth and a size changes
 * them.
 */
export type PairStage = { 
/**
 * Normal module, mm. Shared by both gears.
 */
module: number, 
/**
 * Normal pressure angle, degrees. Shared.
 */
pressure_angle: number, 
/**
 * Shaft angle `Σ`, degrees. **Zero is a parallel-axis pair**; anything else
 * crosses the shafts.
 */
shaft_angle: number, 
/**
 * **The first member's pitch diameter, mm** — a worm's reading of how
 * big it is, and one of the three readings of the pair's one size freedom
 * with the two members' helix angles ([`StageGear::helix_angle`]).
 *
 * Given, it decides both helix angles. Automatic with a helix given, it
 * follows from that. Automatic with every size reading automatic, the
 * size is solved to reach a given centre distance, but only where both
 * shifts are pinned: a shift is the thing that absorbs a distance by
 * preference ([`Self::first_pitch_diameter`]). A worm stage is the case
 * that was built for — it has no profile shift by convention, so its
 * size is what a housing decides — and a helical pair cut to fit a
 * standard centre distance is the same request on parallel shafts.
 */
pitch_diameter: Auto<number>, 
/**
 * **The axial contact ratio** `ε_β` the pair is asked for, where it is
 * asked for one.
 *
 * Automatic, it is an output — what the helix and the face width the
 * mesh carries come to. Given, it is a constraint on whichever of the two
 * is free: a floor under an automatic face width, beside the ratings'
 * asks; or, with both widths given, the thing that decides the helix
 * ([`super::helix_for_overlap`]). Read on parallel shafts alone — a
 * point contact has no overlap — and the floor on a crossed pair's
 * automatic width is nothing at all: its contact's pressure does not
 * depend on the width, so nothing here can size one, and it stands at
 * its box ([`super::key::GEAR_FACE_WIDTH_AS_ENTERED`]).
 */
overlap: Auto<number>, 
/**
 * Coefficient of friction for the mesh.
 */
sliding_friction: number, 
/**
 * Coefficient of **static** friction, for breaking away.
 *
 * Whether a stage turns at all is decided at rest and against this; how
 * well it does once turning is decided against the sliding coefficient,
 * which is lower. See [`Directional::once_moving`] — the static figure's
 * only job is the sign, and it is never itself reported as an efficiency.
 */
static_friction: number, 
/**
 * `k₁`. Gear 2 takes `2 − k₁` by construction.
 */
thickness_mod: number, 
/**
 * Automatic uses the zero-backlash centre distance plus `clearance`.
 */
centre_distance: Auto<number>, 
/**
 * Added to the centre distance, mm — the assembly clearance, and so the
 * backlash.
 *
 * **Read only where something is free to absorb it** — the automatic
 * centre distance, which is this opened out, or the shifts when they are
 * being chosen. Given a distance with nothing free, it is not read at all
 * and the backlash is a consequence; `solve_parallel` is where that
 * happens and is the whole of the rule.
 */
clearance: Auto<number>, tolerance_plus: number, tolerance_minus: number, 
/**
 * What the stage is asked to optimise, and what it may not do to get
 * there. See [`super::Optimisation`].
 */
optimisation: Optimisation, 
/**
 * How the load is divided while two tooth pairs are engaged.
 *
 * **Off by default, and it reaches bending only.** A contact rating is
 * already taken where one tooth carries everything, so sharing cannot move
 * it; a bending rating's worst point is a product of the form factor and
 * the share, so it can. See
 * [`bending_section_shared`](crate::strength::bending_section_shared).
 *
 * The model behind it is an explicitly uncalibrated placeholder rather
 * than a stiffness calculation, which is why it is offered as a choice a
 * designer makes rather than applied on their behalf — the same treatment
 * every other estimate in this crate gets.
 */
load_sharing: LoadSharing, 
/**
 * Axial float of the first member along its own axis, mm.
 *
 * The dominant source of backlash in a worm drive, and **a displacement
 * every helical gear has**: a rigid slide along the axis opens one flank
 * exactly as far as it closes the other, by its component along the
 * common normal, `j_axial sin β_b1`. On a spur gear that component is zero
 * and the input is idle rather than wrong, which is why a spur kind need
 * not show it and a worm kind must.
 */
axial_clearance: number, gears: [StageGear, StageGear], };
