// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GearResult } from "./GearResult";
import type { MeshReport } from "./MeshReport";
import type { Note } from "./Note";

/**
 * Everything a pair produces, whichever mesh it has.
 */
export type PairResult = { 
/**
 * `z₂ / z₁`.
 */
ratio: number, 
/**
 * Zero-backlash centre distance, mm.
 */
centre_distance_nominal: number, 
/**
 * **The clearance the pair actually runs at**, which is
 * `centre_distance − centre_distance_nominal` and is derived rather than
 * echoed.
 *
 * A centre distance is the **true** distance and a clearance is what
 * portion of it is clearance, so these three numbers are two facts and a
 * subtraction — and reporting the input back is a fourth place the same
 * quantity can be said, which was wrong whenever the distance was given.
 * A pair told to run at 30.3 mm whose shifts put it at 30.0057 has 0.294 mm
 * of clearance; it used to report 0.02, the number in the box, or zero.
 *
 * Derived, so the panel can still grey the input by reading the answer,
 * and so the answer cannot disagree with the two numbers above it.
 */
clearance: number, 
/**
 * The centre distance actually used, including clearance.
 */
centre_distance: number, 
/**
 * **What this pair's one mesh reports**, in the type every mesh of every
 * kind reports in — a line contact on parallel shafts, a point contact
 * on crossed ones, and [`MeshReport`] says which by what it carries.
 *
 * Seven fields used to sit here loose — the operating pressure angle, the
 * three contact ratios, whether the pair hunts, the shared contact stress
 * and relative radius, the efficiency and the backlash — which made the
 * parallel-axis stage the one kind not using the type named for what a
 * parallel-axis mesh reports; then a crossed pair had a type of its own
 * and an enum chose. The front end had the same split each time.
 *
 * A pair's efficiency and backlash **are** its mesh's — one mesh, no
 * carrier — so they are read through here rather than stored a second
 * time, and `StageResult::efficiency` is where every kind is made to agree
 * about which level it is being asked for.
 */
mesh: MeshReport, gears: [GearResult, GearResult], 
/**
 * Anything the stage had to say about the design.
 */
notes: Array<Note>, };
