// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Shape } from "./Shape";

/**
 * **A piece of a shape that closes and is searched on its own**, and where
 * it came from: its members, meshes, distances and axes by the shape's
 * index, each in the shape's order.
 */
export type Part = { shape: Shape, members: Array<number>, meshes: Array<number>, distances: Array<number>, axes: Array<number>, 
/**
 * The shape's couplings the part keeps, by the shape's index.
 */
couplings: Array<number>, };
