// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Note } from "./Note";

/**
 * **What is a part's own** — what its search and its closures came to, and
 * the speed and the torque its meshes put on each of its bodies in each
 * case.
 */
export type PartReport = { notes: Array<Note>, };
