// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Note } from "./Note";
import type { SlotCase } from "./SlotCase";

/**
 * **What is a part's own** — its junction's, where it is one: the speed and
 * the torque its meshes put on each of its bodies in each case, which on a
 * shaft two parts share is what the one hands the other, and what its
 * search and its closures came to.
 */
export type PartReport = { 
/**
 * Per case, per body of the part, ground first.
 */
cases: Array<SlotCase>, notes: Array<Note>, };
