// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Backlash } from "./Backlash";
import type { Directional } from "./Directional";
import type { ShaftRef } from "./ShaftRef";

/**
 * **One path of the train**: what it comes to between two of its open
 * bodies, with nothing loaded anywhere else — the three questions a stage
 * answers of itself, asked of the whole graph.
 */
export type PathReport = { from: ShaftRef, to: ShaftRef, 
/**
 * Turns of `from` per turn of `to`, signed, off the one motion.
 */
ratio: number, 
/**
 * Driving `from` with `to` holding the load and every other open body
 * free, and the reverse — the train's flow at unit load, so a path
 * that crosses one stage of three is rated on that stage alone. A path
 * through a self-locking stage cannot be back-driven at all, and
 * [`Directional::locked`] on this pair says so.
 */
efficiency: Directional<number>, 
/**
 * Angular play at `to` driving from `from`, degrees, and at `from`
 * driving from `to`: every mesh's play through the kinematics' own
 * coefficients, so a mesh the path does not cross adds nothing.
 */
backlash: Directional<Backlash>, };
