// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Backlash } from "./Backlash";
import type { Directional } from "./Directional";
import type { RatioReading } from "./RatioReading";

/**
 * **One path of the train**: what it comes to between two of its open
 * bodies, with nothing loaded anywhere else — the three questions a stage
 * once answered of itself, asked of the whole graph.
 */
export type PathReport = { from: number, to: number, 
/**
 * The same ratio as it is read, never under one on either side.
 */
reads: RatioReading, 
/**
 * Driving `from` with `to` holding the load and every other open body
 * free, and the reverse — the train's flow at unit load, so a path
 * that crosses one preset of three is rated on that preset alone. A path
 * through a self-locking mesh cannot be back-driven at all, and
 * [`Directional::locked`] on this pair says so. **Whether it breaks
 * away** is the same flow against every mesh's static friction — each
 * mesh's efficiency at rest, off its cut ([`Directional::once_moving`]):
 * a path that cannot start delivers nothing, and one that can runs on
 * sliding friction.
 */
efficiency: Directional<number>, 
/**
 * Angular play at `to` driving from `from`, degrees, and at `from`
 * driving from `to`: every mesh's play through the kinematics' own
 * coefficients, so a mesh the path does not cross adds nothing.
 */
backlash: Directional<Backlash>, 
/**
 * **The power crossing the teeth, over the power in**, each way — the
 * sum over the meshes the path loads of what each passes: one across a
 * pair, under one where a carrier takes part of it bodily, many times
 * one where power circulates, which is where such a path's efficiency
 * goes ([`flow::Flow::mesh_powers`]). An offset coupling passes power
 * and has no teeth, so it counts for nothing here.
 */
circulation: Directional<number>, };
