// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Note } from "./Note";

/**
 * Teeth that are not the gear that was asked for, and why.
 *
 * A guard rail that is genuinely about **one tooth** — a tooth with too much
 * shift comes to a point, one with too little is undercut — cannot be shared
 * away like a tool setting, and smoothing it over would be inventing geometry.
 * It is reported instead, with the positions, because "some of your teeth are
 * not what you drew" is only useful if it says which.
 */
export type PerToothClamps = { 
/**
 * Positions round the gear, counting from `θ = 0`.
 */
teeth: Array<number>, 
/**
 * What happened, each reason once.
 */
notes: Array<Note>, };
