// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **A piece of the graph**, by the graph's index — a body by its number.
 */
export type Piece = { "member": number } | { "mesh": number } | { "axis": number } | { "body": number } | { "coupling": number };
