// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **Where a gear an edit adds goes.**
 */
export type Place = { "body": number } | { "new_body": number } | "new_axis";
