// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Arrangement } from "./Arrangement";
import type { Backlash } from "./Backlash";
import type { Directional } from "./Directional";
import type { GearResult } from "./GearResult";
import type { MeshReport } from "./MeshReport";
import type { Note } from "./Note";
import type { PlanetResult } from "./PlanetResult";
import type { PlanetaryShaft } from "./PlanetaryShaft";

/**
 * Everything a planetary stage produces.
 */
export type PlanetaryResult = { arrangement: Arrangement, 
/**
 * The shaft the other two leave over.
 */
output: PlanetaryShaft, 
/**
 * Speed reduction, input over output. Negative when the output reverses.
 */
ratio: number, 
/**
 * The common centre distance, zero-backlash, mm — sun-to-planet and
 * planet-to-ring, which the planet's shift has made the same number.
 */
centre_distance_nominal: number, 
/**
 * ...and the one actually used, including clearance.
 */
centre_distance: number, 
/**
 * Fixed-carrier efficiency `η₀`, the product of the two mesh efficiencies.
 * The quantity docs/reference.md#planetary-sets requires, because the meshes slide at their speeds
 * relative to the carrier rather than to ground.
 */
fixed_carrier_efficiency: Directional<number>, 
/**
 * Whole-set efficiency, driving forward and backward. Driving backward means
 * the output shaft becomes the input with the same shaft held.
 */
efficiency: Directional<number>, 
/**
 * Angular backlash at whichever shaft is the **output**, degrees: the
 * output shaft driving forward, the input shaft driving backward — the same
 * convention every other stage kind uses.
 */
backlash: Directional<Backlash>, 
/**
 * Speeds `[sun, carrier, ring]`, rpm. The held shaft is exactly zero.
 */
speeds: [number, number, number], 
/**
 * Torques `[sun, carrier, ring]`, N·m. They sum to zero.
 */
torques: [number, number, number], sun_planet: MeshReport, planet_ring: MeshReport, 
/**
 * Planets can be spaced evenly: `(z_s + z_r) mod N = 0`.
 */
equal_spacing: boolean, 
/**
 * Every planet meshes at the same phase — rarely true, and not a fault.
 */
simultaneous_meshing: boolean, 
/**
 * Gap between adjacent planets' tip circles, mm. `None` for a single planet.
 */
planet_clearance: number | null, 
/**
 * Whether that gap meets [`PlanetaryStage::min_planet_clearance`].
 */
planet_clearance_ok: boolean, 
/**
 * Whether the tooth counts share no factor with the planet count, which
 * spreads wear instead of repeatedly pairing the same teeth.
 */
sun_coprime_with_planets: boolean, ring_coprime_with_planets: boolean, sun: GearResult, planet: PlanetResult, ring: GearResult, 
/**
 * How many planets the set has — kept because the train needs it to count
 * tooth cycles, and the stage's inputs are not in reach by then.
 */
planets: number, 
/**
 * Anything the stage had to say — including what it did not model.
 */
notes: Array<Note>, };
