// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GearResult } from "./GearResult";
import type { Value } from "./Value";

/**
 * The planet's own answers, which are not the shape of the other two.
 */
export type PlanetResult = { 
/**
 * Everything a gear in a stage reports.
 */
gear: GearResult, 
/**
 * The shift the common-centre-distance solve required.
 */
profile_shift: number, 
/**
 * `|a_sun-planet − a_planet-ring|` at that shift, mm. Reported rather than
 * asserted: it is the one number that says the solve closed.
 */
shift_residual: number, 
/**
 * Speed in the fixed frame, rpm.
 */
speed_absolute: number, 
/**
 * Speed **relative to the carrier**, rpm — what its teeth actually see.
 */
speed_relative: number, 
/**
 * Bending is fully reversed: the sun drives one flank and the ring the
 * other. Always true, and carried so a reader meets it beside the stress
 * rather than in the documentation.
 */
fully_reversed: boolean, 
/**
 * The bending allowable a fully reversed load leaves, MPa, and where the
 * figure comes from.
 */
reversed_allowable: Value, 
/**
 * Face width the reversed bending would need against that allowable.
 */
min_face_width_reversed: number | null, };
