// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One of the three shafts a planetary set presents.
 *
 * The planets themselves are not on this list: they have no shaft of their own,
 * and their speed is a consequence of the other three.
 */
export type PlanetaryShaft = "sun" | "carrier" | "ring";
