// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Arrangement } from "./Arrangement";
import type { Cutter } from "./Cutter";
import type { StageGear } from "./StageGear";

/**
 * A planetary stage as its inputs describe it.
 */
export type PlanetaryStage = { 
/**
 * Normal module, mm. Shared by all three members.
 */
module: number, 
/**
 * Normal pressure angle, degrees. Shared.
 */
pressure_angle: number, 
/**
 * Helix angle, degrees. Shared; the internal pair takes the same hand and
 * the external pair the opposite, which is what the meshes require.
 */
helix_angle: number, 
/**
 * Coefficient of friction, sun-to-planet.
 */
sliding_friction_sun_planet: number, 
/**
 * Coefficient of **static** friction, for breaking away.
 *
 * Whether a drive turns at all is decided at rest and against this; how
 * well it does once turning is decided against the sliding coefficient,
 * which is lower. See [`Directional::once_moving`] — the static figure's
 * only job is the sign, and it is never itself reported as an efficiency.
 */
static_friction_sun_planet: number, 
/**
 * ...and planet-to-ring.
 */
sliding_friction_planet_ring: number, 
/**
 * Coefficient of **static** friction, for breaking away.
 *
 * Whether a drive turns at all is decided at rest and against this; how
 * well it does once turning is decided against the sliding coefficient,
 * which is lower. See [`Directional::once_moving`] — the static figure's
 * only job is the sign, and it is never itself reported as an efficiency.
 */
static_friction_planet_ring: number, 
/**
 * `k` for the **sun**. The planet takes `2 − k` (external pair) and the ring
 * takes the planet's (internal pair), so all three follow from this one.
 */
thickness_mod: number, 
/**
 * How many planets. One is legal; it just has no neighbour to clear.
 */
planets: number, 
/**
 * Which shaft drives and which is held.
 */
arrangement: Arrangement, 
/**
 * Added to the common centre distance, mm — the running clearance.
 */
clearance: number, tolerance_plus: number, tolerance_minus: number, 
/**
 * Smallest acceptable gap between adjacent planets' tip circles, mm.
 */
min_planet_clearance: number, 
/**
 * The shaper the ring is cut with. A ring has no geometry without one.
 */
cutter: Cutter, 
/**
 * The sun. Its profile shift is an input, automatic or manual.
 */
sun: StageGear, 
/**
 * The planet. **Its profile shift is ignored**: the shift is what makes the
 * two centre distances agree, so it is solved rather than chosen (docs/reference.md#planetary-sets).
 */
planet: StageGear, 
/**
 * The ring. Its `dedendum` and `root_radius` are ignored — a ring's root
 * circle is where its cutter reaches (docs/reference.md#internal-gears) — and its shift is a manual
 * input, since the automatic rule is an undercut criterion for an external
 * tooth.
 */
ring: StageGear, };
