// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GearResult } from "./GearResult";

/**
 * The planet's own answers, which are not the shape of the other two.
 */
export type PlanetResult = { 
/**
 * Everything a gear in a stage reports — including **the shift the
 * common-centre-distance solve required**, which is this member's
 * `profile_shift` like any other's, and its speed in the fixed frame.
 * What is left below is what no `GearResult` has a field for.
 */
gear: GearResult, 
/**
 * `|a_sun-planet − a_planet-ring|` at that shift, mm. Reported rather than
 * asserted: it is the one number that says the solve closed.
 */
shift_residual: number, 
/**
 * Speed **relative to the carrier**, rpm — what its teeth actually see.
 *
 * The planet is the one member whose fixed-frame speed is not the whole
 * story, and it is not the sun's relative speed either: the two differ by
 * `z_s/z_p` ([`crate::planetary::Power::planet_speed`]).
 */
speed_relative: number, };
