// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Auto } from "./Auto";
import type { Cutter } from "./Cutter";
import type { LoadSharing } from "./LoadSharing";
import type { Optimisation } from "./Optimisation";
import type { StageGear } from "./StageGear";

/**
 * A planetary stage as its inputs describe it.
 */
export type PlanetaryStage = { 
/**
 * Normal module, mm. Shared by all three members.
 */
module: number, 
/**
 * Normal pressure angle, degrees. Shared.
 */
pressure_angle: number, 
/**
 * **The axial contact ratio** `ε_β` the set is asked for, where it is
 * asked for one — the same input a pair has ([`super::PairStage::overlap`]),
 * asked of both meshes: a floor under every automatic face width, or,
 * with all three widths given, the thing that decides the helix, so that
 * the narrower of the two meshes reaches it.
 */
overlap: Auto<number>, 
/**
 * Coefficient of friction, sun-to-planet.
 */
sliding_friction_sun_planet: number, 
/**
 * Coefficient of **static** friction, for breaking away.
 *
 * Whether a stage turns at all is decided at rest and against this; how
 * well it does once turning is decided against the sliding coefficient,
 * which is lower. See [`Directional::once_moving`] — the static figure's
 * only job is the sign, and it is never itself reported as an efficiency.
 */
static_friction_sun_planet: number, 
/**
 * ...and planet-to-ring.
 */
sliding_friction_planet_ring: number, 
/**
 * Coefficient of **static** friction, for breaking away.
 *
 * Whether a stage turns at all is decided at rest and against this; how
 * well it does once turning is decided against the sliding coefficient,
 * which is lower. See [`Directional::once_moving`] — the static figure's
 * only job is the sign, and it is never itself reported as an efficiency.
 */
static_friction_planet_ring: number, 
/**
 * `k` for the **sun**. The planet takes `2 − k` (external pair) and the ring
 * takes the planet's (internal pair), so all three follow from this one.
 */
thickness_mod: number, 
/**
 * How many planets. One is legal; it just has no neighbour to clear.
 */
planets: number, 
/**
 * What the set is asked to optimise, and what it may not do to get there.
 * See [`Optimisation`]: the sun's and the ring's shifts are searched
 * together and the planet's follows, and both meshes are held to the
 * contact ratio since a set is only as continuous as its worse half.
 */
optimisation: Optimisation, 
/**
 * The transverse contact ratio the search may not take either mesh
 * below ([`super::DEFAULT_MIN_CONTACT_RATIO`]).
 */
min_contact_ratio: number, 
/**
 * How the load is divided while two tooth pairs are engaged.
 *
 * **Off by default, and it reaches bending only** — see
 * [`super::PairStage::load_sharing`], which is the same input for the same
 * reason. Both meshes take it: a set switching the model on and getting it
 * on one mesh would be one stage answering two ways.
 */
load_sharing: LoadSharing, 
/**
 * **The distance the sun runs from a planet, or automatic.**
 *
 * The same shape and the same decision every other stage's centre distance
 * has. Automatic, the common distance is whatever the shifts leave — which
 * is what this stage has always done. Given, each mesh has a shift sum it
 * must reach to run at it, and both of those are closed form
 * ([`crate::mesh::shift_sum_for`]), so a target makes the layout *easier*:
 * it removes the iteration rather than adding to it.
 *
 * Two equations instead of one means **two** of the three shifts are
 * absorbed rather than one, which is the same accounting a pair does — see
 * [`crate::train::FreedomGroup`].
 */
centre_distance: Auto<number>, 
/**
 * The running clearance, mm — in **both** meshes, and always an input.
 *
 * One physical distance carries a sun–planet mesh that opens as the planet
 * moves out and a planet–ring mesh that opens as it moves in, so a
 * clearance in both is the two zero-backlash distances differing by `2c`
 * ([`crate::mesh::MeshKind::run_at`]) — which is what the absorbing shift
 * is solved to leave. That is why it cannot be derived: a given distance
 * and given shifts leave one gap on each mesh, and there is no one number
 * for this field to be. It carries the same `Auto` every distance's does so
 * the front end can offer it the same way; [`super::Shape::freedoms`]
 * says it may not be automatic, and relief pins it.
 */
clearance: Auto<number>, tolerance_plus: number, tolerance_minus: number, 
/**
 * Smallest acceptable gap between adjacent planets' tip circles, mm.
 */
min_planet_clearance: number, 
/**
 * The shaper the ring is cut with. A ring has no geometry without one.
 */
cutter: Cutter, 
/**
 * The sun. Its profile shift is an input, automatic or manual.
 */
sun: StageGear, 
/**
 * The planet. **Its profile shift is ignored**: the shift is what makes the
 * two centre distances agree, so it is solved rather than chosen (docs/reference.md#planetary-sets).
 */
planet: StageGear, 
/**
 * The ring. Its `dedendum` and `root_radius` are ignored — a ring's root
 * circle is where its cutter reaches (docs/reference.md#internal-gears) — and its shift is a manual
 * input, since the automatic rule is an undercut criterion for an external
 * tooth.
 */
ring: StageGear, };
