// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ZoneLimit } from "./ZoneLimit";

/**
 * What only a point contact reports: the zone as the faces leave it, and the
 * pair it is compared against.
 */
export type PointContact = { 
/**
 * What ended the zone: the teeth, or the face they are cut on.
 */
limited_by: ZoneLimit, 
/**
 * The face width at which `ε = 1`, per member, mm.
 *
 * A **geometric** minimum: it keeps contact continuous and says nothing
 * about stress. That is the opposite of a line contact's automatic width,
 * which inverts a stress, and the difference has to travel with the
 * number.
 */
face_width_for_continuity: [number, number] | null, 
/**
 * How far the contact point runs along each member's own axis, mm — what a
 * face has to cover, and what a line contact does not have at all.
 */
axial_travel: [number, number], 
/**
 * What the same teeth would lose with their shafts brought **parallel**, as
 * an efficiency — `None` where the parallel pair cannot be built.
 *
 * Reported for comparison: crossing shafts adds sliding, so this is the
 * best the pair can be, and how far the crossed figure falls below it is
 * what the shaft angle costs. It was once a *check*, and the friction
 * balance has since made it worse than useless as one: the parallel
 * closed form is first order in `μ` where the balance is exact, so at a
 * very small shaft angle the crossed figure legitimately sits a hundredth
 * of a point above it (docs/corrections.md).
 */
parallel_axis_efficiency: number | null, };
