// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Constraint } from "./Constraint";
import type { ShaftLabel } from "./ShaftLabel";

/**
 * One of a stage's ports, as the front end names it.
 */
export type PortSpec = { 
/**
 * The local shaft index a [`ShaftRef`] names it by.
 */
shaft: number, label: ShaftLabel, 
/**
 * **What this port is asked if the train says nothing about it** — the
 * kind's convention *as the overlay leaves it*, with everything else
 * the train states in force: a set's ring reads `free` here once its
 * carrier is held, because holding the carrier releases it. What a
 * panel's "convention" choice would come to, computed by the rule
 * rather than guessed from the kind.
 */
by_convention: Constraint, };
