// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShaftRef } from "./ShaftRef";

/**
 * Where a load enters the train, or where a sweep is measured.
 *
 * A train has no forward (`docs/rationale.md#direction-is-the-readers-not-the-mechanisms`): a
 * load applied at a shaft works its way toward whatever holds it, and the
 * direction it travels in at each stage is found by walking the shaft line
 * from that shaft ([`Train::route`]) — never stored.
 *
 * Two names and a reference. `Start` and `End` are the two ports a chain
 * names for itself — the first stage's input and the last stage's output,
 * *under the constraints in force* — and they survive a stage being added
 * or rearranged, which is why they are names rather than indices. `At` is
 * any shaft a stage lists as a port ([`Ports`]): a load that enters a set by
 * its carrier while its sun is turned from upstream, or a sweep measured at
 * a shaft the chain does not end at. [`Train::port_shaft`] resolves all
 * three to a shaft and nothing downstream of it knows which was written.
 */
export type Port = "start" | "end" | { "at": ShaftRef };
