// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShaftLabel } from "./ShaftLabel";

/**
 * One of a stage's ports, as the front end names it.
 */
export type PortSpec = { 
/**
 * The local shaft index a [`ShaftRef`] names it by.
 */
shaft: number, label: ShaftLabel, };
