// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a load enters the train.
 *
 * A train has no forward (`docs/rationale.md#direction-is-the-readers-not-the-mechanisms`): it has
 * two ends, and a load applied at either one works its way toward the other.
 * The direction a load travels in is derived from its port and never stored —
 * [`Port::drive`] is the one place the two are related — so a train with a
 * third entry point some day is a third value here and not a branch anywhere.
 * [`Port::ALL`] is what a picker shows.
 */
export type Port = "start" | "end";
