// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One of a stage's ports, as the front end names it.
 */
export type PortSpec = { 
/**
 * The stage's own numbering of it.
 */
slot: number, 
/**
 * The train's body it is.
 */
body: number, };
