// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **One body a train may be addressed at**: a port, of one part or
 * several — a pair's output and the next set's sun are one body, and a
 * case says one thing of it.
 *
 * What the front end is handed as the train's ports ([`Train::bodies`]):
 * the picker offers the ones not held, and a case has a row per one.
 */
export type PortBody = { body: number, 
/**
 * Held by the train — ground under another name — so no case can say
 * anything of it.
 */
held: boolean, };
