// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanetaryShaft } from "./PlanetaryShaft";

/**
 * What the three shafts do, and what it costs to make them do it.
 */
export type Power = { 
/**
 * Angular speeds `[sun, carrier, ring]`, in whatever unit the input was
 * given. The held shaft is exactly zero.
 */
speeds: [number, number, number], 
/**
 * Torques `[sun, carrier, ring]`, in whatever unit the input was given.
 * They sum to zero — the set is in equilibrium, and the held shaft's torque
 * is the reaction it carries.
 */
torques: [number, number, number], 
/**
 * Speed reduction, input over output. Negative when the output turns the
 * other way.
 */
ratio: number, 
/**
 * Mechanical efficiency, `|T_out ω_out| / |T_in ω_in|`.
 */
efficiency: number, 
/**
 * The member the other two leave over.
 */
output: PlanetaryShaft, 
/**
 * Sign of the rolling power — which way power crosses the meshes in the
 * carrier's frame. `+1` when the sun leads the carrier under a driving
 * torque, `−1` when it trails.
 */
rolling_power_sign: number, };
