// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **The three families a shape reads as**, off its graph and never stored:
 * a carried axis makes it epicyclic; failing that, a distance at an angle
 * or marked as a worm drive makes it skew; anything else is parallel. A
 * spur pair is the epicyclic family with its carrier held and no ring —
 * which is why the family is a reading and not a kind, and why a crossed
 * pair turned to nought is simply a parallel one afterwards.
 */
export type PresetFamily = "parallel" | "skew" | "epicyclic";
