// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Note } from "./Note";

/**
 * **What an edit would do** ([`preview`]).
 */
export type Preview = { 
/**
 * Why the edit would not be made, where it would not.
 */
refused: Note | null, 
/**
 * **What it would change**: each kind of piece whose count moves —
 * gears, meshes, axes, bodies, axis distances, couplings — the holds
 * and the case entries, before and after; or that it changes nothing
 * at all.
 */
changes: Array<Note>, 
/**
 * **What the headline path would come to** — the path the headline
 * case walks first — its ratio and efficiency before and after, or
 * that it would go, or appear.
 */
paths: Array<Note>, 
/**
 * Why the train would not solve after it, where it would not.
 */
unsolved: Note | null, };
