// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **ISO 6336-5's material quality grade**: how far a producer's control of
 * the material and its treatment is demonstrated. The same hardness buys a
 * higher allowable at a better grade.
 */
export type QualityGrade = "ml" | "mq" | "me";
