// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bound } from "./Bound";
import type { ShiftRange } from "./ShiftRange";

/**
 * Every input range the geometry decides, rather than convention.
 *
 * # What these are for
 *
 * **Only to stop a gear that cannot exist**, not one that is merely strange or
 * useless. A one-tooth gear, an 85° helix, a negative addendum and a pressure
 * angle of 2° are all peculiar and all perfectly constructible — the generator
 * builds every one of them, finite and closed. They are not this crate's to
 * forbid.
 *
 * So the bounds here mark impossibility: a tip inside its own root, a root
 * circle at or through the axis, a fillet that cannot fit the space it must sit
 * in. The parameters that stay fixed in the UI are the ones whose bounds are
 * *also* impossibility, and simply do not vary: `m > 0`, `z ≥ 1`, `0 < α < 90°`,
 * `|β| < 90°`, and `0 < k < 2` (a rack whose tooth or space has non-positive
 * width is not a rack).
 */
export type Ranges = { 
/**
 * `m > 0`: at zero every radius collapses.
 */
module: Bound, 
/**
 * `0 < α < 90°`: at zero the thickness-equivalent shift diverges, at 90°
 * the base circle does.
 */
pressure_angle: Bound, 
/**
 * `z ≥ 1`.
 */
teeth: Bound, 
/**
 * `|β| < 90°`: the transverse module diverges at the limit.
 */
helix_angle: Bound, 
/**
 * `0 < k < 2`: a rack whose tooth or space has non-positive width is not a
 * rack.
 */
thickness_mod: Bound, profile_shift: ShiftRange, 
/**
 * Lower bound only. There is no upper: too much addendum gives a pointed
 * tooth, which the generator caps and reports rather than refuses.
 */
addendum: Bound, dedendum: Bound, 
/**
 * Upper bound only, from the fillet fit.
 */
root_radius: Bound, 
/**
 * How far the shift may vary around the revolution — see
 * [`admissible_angular_shift`]. Symmetric about zero, and the one bound
 * that is about the *tool* the teeth share rather than about any one tooth.
 */
angular_shift: Bound, };
