// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **A ratio as it is read**: so many turns to one, whichever way round
 * keeps the figure at one or more — `2.5294 : 1` for a reduction, and
 * `1 : 2.5294` for a step-up rather than `0.3953 : 1`. The sign, where the
 * two ends turn opposite ways, is the figure's. Decided here once, so the
 * path's row and an edit's dry run read a path the same way.
 */
export type RatioReading = { 
/**
 * The side that is not one: `|turns| ≥ 1`.
 */
turns: number, 
/**
 * Whether the one is the first side's — a step-up, read `1 : turns`.
 */
step_up: boolean, };
