// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Exact } from "./Exact";
import type { ShaftLabel } from "./ShaftLabel";
import type { ShaftRef } from "./ShaftRef";

/**
 * One shaft of the train's motion, for the front end.
 */
export type ShaftReport = { at: ShaftRef, label: ShaftLabel, 
/**
 * Turns per turn of what is driven.
 */
speed: Exact, };
