// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a shaft is in one load case.
 */
export type ShaftRole = "load" | "reacted" | "fixed" | "free";
