// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one load case puts on the **shafts** of an epicyclic kind, by
 * [`PlanetaryShaft`](crate::planetary::PlanetaryShaft) index — the set's sun,
 * carrier and ring, or the hula stage's grounded gear, crank and output. The
 * members print their own; this is where the shaft that is not a gear reads.
 */
export type ShaftsCase = { 
/**
 * Index into the train's list of load cases.
 */
case: number, 
/**
 * rpm. The held shaft is exactly zero.
 */
speeds: [number, number, number], 
/**
 * N·m. They sum to zero.
 */
torques: [number, number, number], };
