// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a shaft is, from the train's point of view.
 */
export type ShaftRef = { "kind": "ground" } | { "kind": "of", stage: number, shaft: number, };
