// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Constraint } from "./Constraint";
import type { ShaftRef } from "./ShaftRef";

/**
 * One shaft, and what is asked of it.
 */
export type ShaftConstraint = { at: ShaftRef, constraint: Constraint, };
