// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A shaft, by the axis it turns about. Shaft `i` here is shaft `i + 1` of
 * the wiring; ground is shaft 0 and is not listed.
 */
export type ShaftOn = { axis: number, };
