// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Every shaft's speed and torque in one load case.
 */
export type ShaftCase = { case: number, 
/**
 * Per local shaft, ground first.
 */
speeds: Array<number>, torques: Array<number>, };
