// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Backlash } from "./Backlash";
import type { Directional } from "./Directional";
import type { DistanceReport } from "./DistanceReport";
import type { GearResult } from "./GearResult";
import type { LayoutReport } from "./LayoutReport";
import type { MeshReport } from "./MeshReport";
import type { Note } from "./Note";
import type { ShaftCase } from "./ShaftCase";

/**
 * What a shape produces.
 */
export type ShapeResult = { 
/**
 * Input turns per output turn, signed.
 */
ratio: number, efficiency: Directional<number>, 
/**
 * Play at the output shaft driven forward, at the input driven back.
 */
backlash: Directional<Backlash>, distances: Array<DistanceReport>, overlap: number, layout: LayoutReport | null, cases: Array<ShaftCase>, members: Array<GearResult>, meshes: Array<MeshReport>, notes: Array<Note>, };
