// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DistanceReport } from "./DistanceReport";
import type { GearResult } from "./GearResult";
import type { LayoutReport } from "./LayoutReport";
import type { MeshReport } from "./MeshReport";
import type { Note } from "./Note";
import type { SlotCase } from "./SlotCase";

/**
 * What a shape produces: its geometry, and its members and meshes rated
 * for the train's cases.
 *
 * **No figures of its own.** A ratio, an efficiency, a play and what one
 * more tooth does are a path's ([`super::PathReport`]), read between two
 * bodies a case names. A stage's were a second motion solved under a
 * convention of its own, and a law held them to the path across its ends
 * until nothing read them but the stage.
 */
export type ShapeResult = { distances: Array<DistanceReport>, 
/**
 * One per replicated axis, in axis order.
 */
layouts: Array<LayoutReport>, cases: Array<SlotCase>, members: Array<GearResult>, meshes: Array<MeshReport>, notes: Array<Note>, };
