// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Axis } from "./Axis";
import type { Distance } from "./Distance";
import type { LoadSharing } from "./LoadSharing";
import type { Member } from "./Member";
import type { MeshInput } from "./MeshInput";
import type { Optimisation } from "./Optimisation";
import type { ShaftOn } from "./ShaftOn";

/**
 * The stage.
 */
export type Shape = { optimisation: Optimisation, load_sharing: LoadSharing, axes: Array<Axis>, shafts: Array<ShaftOn>, members: Array<Member>, meshes: Array<MeshInput>, distances: Array<Distance>, };
