// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bound } from "./Bound";

/**
 * What profile shifts a gear can be built at, and the design thresholds inside
 * that range.
 *
 * Two tiers, deliberately, because they answer different questions.
 */
export type ShiftRange = { 
/**
 * What can be built: below it the tooth is thinner than the guards allow or
 * the cutter runs past the centre; above it the cutter no longer reaches
 * the root.
 */
bound: Bound, 
/**
 * Below this the flank is undercut at the stated working depth — the same
 * figure [`minimum_profile_shift`] returns. **Advisory, not a limit:** an
 * undercut gear is a real gear, and this crate generates it exactly.
 */
undercut: number, 
/**
 * The undercut threshold a sharp-cornered rack would give. Reported so the
 * classical rule's hidden assumption stays visible.
 */
sharp_rack_undercut: number, 
/**
 * Above this the tooth would be pointed at the requested addendum, so the
 * tip radius is capped and a clamp note is raised. `None` when the tooth
 * never comes to a point anywhere in the buildable range.
 */
pointed: number | null, 
/**
 * Above this the cutter has to reach **deeper than the dedendum asked
 * for**, because a shift moves the tool out and the depth `m(h_f − x)` runs
 * out before the shift does.
 *
 * A threshold rather than a limit, and it was a limit until it was measured
 * (`docs/corrections.md`). The dedendum is a request for where the root
 * should sit, and the tool is derived from it — the same reading a ring has
 * always had, where the root circle is wherever the cutter reaches and
 * there is no dedendum input at all. So a shift past here is buildable, by
 * a deeper tool, and what the designer is owed is to be told that the tool
 * is no longer the one specified rather than to be refused a gear that can
 * be cut.
 *
 * Treating it as a limit is also what made the buildable range **step by
 * 62 %** as the angular shift left zero: an eccentric gear's teeth share
 * one tool and cannot each own a dedendum, so that path had already derived
 * the depth, while a concentric gear refused. One reading now, and this
 * threshold is where the two used to part.
 */
shallow_cut: number, };
