// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The mean, amplitude and phase of a pure sinusoid, in the units it is read in.
 *
 * A named struct rather than `[f64; 3]`, because the three carry **different
 * units** and an array says they do not. The phase is in **degrees**: angles
 * are radians everywhere inside this crate and degrees at the boundary, and
 * this type exists to be reported. Converting it in the front end instead put
 * both the conversion and the choice of decimals on the side of the boundary
 * that has no tests, which is the rule `docs/corrections.md` records a
 * diameter breaking once already.
 */
export type Sinusoid = { 
/**
 * The value it oscillates about, mm.
 */
mean: number, 
/**
 * Half its peak-to-peak swing, mm.
 */
amplitude: number, 
/**
 * Where its maximum sits, **degrees**.
 */
phase_degrees: number, };
