// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **What a fatigue figure was measured on.**
 */
export type Specimen = "coupon" | "gear_root";
