// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What decides how a mesh's profile shift is divided between its two members.
 *
 * The **difference** is not free: it is what the crank offset is, and what the
 * far-side gap depends on. This names the one freedom a mesh has left, and
 * names it by what fixes it rather than by which member "gets" the shift — so
 * neither member is privileged and a design can be entered from either end.
 *
 * What the shape is for beyond the two arms below: with the difference already
 * spent, the split is exactly the freedom a distribution rule needs, so a rule
 * that chooses it — for efficiency, say — is one more arm here rather than
 * another way to describe a gear.
 */
export type Split = { "ring": number } | { "pinion": number };
