// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Auto } from "./Auto";
import type { StageGear } from "./StageGear";

/**
 * A stage of two gears on shafts at any angle.
 *
 * Spur when nothing is angled, helical when the teeth are, and a **crossed
 * gear pair** when the shafts are — one stage, as the specification has it,
 * with the shaft angle as the input that distinguishes them. It is not three
 * kinds of stage: the tooth counts, the module, the materials and the
 * tolerances mean the same thing throughout, and only the *mesh* differs.
 *
 * # The two helix angles come from the shaft angle
 *
 * ```text
 * β₁ = Σ/2 + β_add,     β₂ = Σ/2 − β_add
 * ```
 *
 * so `β₁ + β₂ = Σ` — the relation crossed-axis screw gearing runs on (docs/reference.md#crossed-axes)
 * — and at `Σ = 0` it collapses to `β₁ = −β₂ = β_add`, a parallel helical pair
 * with its two hands opposed. The parallel case is the shaft angle's zero
 * rather than a separate construction, which is the specification's own
 * reading: "Total Helix Angle = 0.5 × Axis Angle + Additional Helix Angle".
 *
 * What *does* branch is the mesh, and it must: parallel axes touch along a
 * line and lose power to sliding along the profile, while crossed axes touch
 * at a point and slide lengthwise. Those are different mechanisms with
 * different formulas and different results (docs/reference.md#crossed-axes), so a crossed stage
 * answers with the screw result — no contact ratio, no bending, two
 * efficiencies — and says so.
 */
export type SpurStage = { 
/**
 * Normal module, mm. Shared by both gears.
 */
module: number, 
/**
 * Normal pressure angle, degrees. Shared.
 */
pressure_angle: number, 
/**
 * Shaft angle `Σ`, degrees. **Zero is a parallel-axis pair**; anything else
 * crosses the shafts.
 */
shaft_angle: number, 
/**
 * Additional helix angle, degrees — what each gear carries *beyond* half
 * the shaft angle. Gear 2 takes it with the opposite sign, so at `Σ = 0`
 * this is the familiar shared helix angle with opposed hands.
 */
additional_helix: number, 
/**
 * Coefficient of friction for the mesh.
 */
sliding_friction: number, 
/**
 * Coefficient of **static** friction, for breaking away.
 *
 * Whether a drive turns at all is decided at rest and against this; how
 * well it does once turning is decided against the sliding coefficient,
 * which is lower. See [`Directional::once_moving`] — the static figure's
 * only job is the sign, and it is never itself reported as an efficiency.
 */
static_friction: number, 
/**
 * `k₁`. Gear 2 takes `2 − k₁` by construction.
 */
thickness_mod: number, 
/**
 * Automatic uses the zero-backlash centre distance plus `clearance`.
 */
centre_distance: Auto<number>, 
/**
 * Added to the centre distance, mm. Forced to zero when the centre distance
 * is set manually, per the specification.
 */
clearance: number, tolerance_plus: number, tolerance_minus: number, gears: [StageGear, StageGear], };
