// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GearResult } from "./GearResult";
import type { MeshReport } from "./MeshReport";
import type { Note } from "./Note";

/**
 * Everything a parallel-axis stage produces.
 */
export type SpurResult = { 
/**
 * `z₂ / z₁`.
 */
ratio: number, 
/**
 * Zero-backlash centre distance, mm.
 */
centre_distance_nominal: number, 
/**
 * **The clearance the stage opened by**, which is zero where nothing was
 * free to absorb it — see [`SpurStage::clearance_taken`], the one place
 * that is decided. Reported so a reader is told the input went unread
 * rather than left to work it out, and so the panel can grey the field by
 * reading the answer instead of knowing the rule a second time.
 */
clearance: number, 
/**
 * The centre distance actually used, including clearance.
 */
centre_distance: number, 
/**
 * **What this pair's one mesh reports**, in the type every other kind
 * reports a parallel-axis mesh in.
 *
 * Seven fields used to sit here loose — the operating pressure angle, the
 * three contact ratios, whether the pair hunts, the shared contact stress
 * and relative radius, the efficiency and the backlash — which made the
 * parallel-axis stage the one kind not using the type named for what a
 * parallel-axis mesh reports. The front end had the same split: a
 * `meshRows` snippet for the kinds carrying a `MeshReport`, and the same
 * rows written out again for this one.
 *
 * A spur pair's efficiency and backlash **are** its mesh's — one mesh, no
 * carrier — so they are read through here rather than stored a second
 * time, and `StageResult::efficiency` is where every kind is made to agree
 * about which level it is being asked for.
 */
mesh: MeshReport, gears: [GearResult, GearResult], 
/**
 * Anything the stage had to say about the design.
 */
notes: Array<Note>, };
