// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Backlash } from "./Backlash";
import type { ContactRatios } from "./ContactRatios";
import type { Directional } from "./Directional";
import type { GearResult } from "./GearResult";
import type { LoadCase } from "./LoadCase";
import type { Note } from "./Note";

/**
 * Everything a parallel-axis stage produces.
 */
export type SpurResult = { 
/**
 * `z₂ / z₁`.
 */
ratio: number, 
/**
 * Zero-backlash centre distance, mm.
 */
centre_distance_nominal: number, 
/**
 * The centre distance actually used, including clearance.
 */
centre_distance: number, contact_ratios: ContactRatios, 
/**
 * Hertzian contact stress, MPa, in both load cases.
 *
 * **A property of the mesh, not of either gear.** The two flanks share one
 * patch, one normal force and one `E*`, so there is one pressure and it is
 * reported once. What differs between the gears is the allowable it is
 * judged against, which is why [`GearResult::min_face_width`] is per gear
 * and this is not.
 */
contact_stress: LoadCase<number>, 
/**
 * Relative radius of curvature at the governing point, mm.
 */
relative_radius: number, 
/**
 * Mesh efficiency, 0..1, in both drive directions.
 *
 * The two are equal for a parallel-axis stage, and they are computed
 * independently rather than copied — see
 * [`crate::contact::efficiency`] for why they come out that way.
 */
efficiency: Directional<number>, 
/**
 * Angular backlash at whichever gear is the output in each direction,
 * degrees: gear 2 driving forward, gear 1 driving backward. The same tooth
 * gap subtends a different angle at each, so these differ whenever the
 * tooth counts do.
 */
backlash: Directional<Backlash>, 
/**
 * Whether the tooth counts share no factor — a hunting ratio, which spreads
 * wear evenly instead of repeatedly pairing the same teeth.
 */
coprime: boolean, gears: [GearResult, GearResult], 
/**
 * Anything the stage had to say about the design.
 */
notes: Array<Note>, };
