// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShapeResult } from "./ShapeResult";

/**
 * What a stage produced.
 *
 * One result, the shape's, under the tag the stage carries. What the train
 * needs from it is small enough to read through the accessors below —
 * ratio, efficiency, the backlash at the output member, every member and
 * every mesh — which is what a sweep over "every number every stage
 * reports" walks.
 */
export type StageResult = { "kind": "shape" } & ShapeResult;
