// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortSpec } from "./PortSpec";

/**
 * **A stage's ports and its conventional holds**, so a panel can offer
 * exactly the shafts a train may constrain or couple — read from the kind's
 * own wiring rather than written into the front end a second time.
 */
export type StagePorts = { ports: Array<PortSpec>, 
/**
 * What the kind holds when the train says nothing.
 */
held_by_convention: Array<number>, };
