// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanetaryStage } from "./PlanetaryStage";
import type { SpurStage } from "./SpurStage";
import type { WormStage } from "./WormStage";

/**
 * A stage of a geartrain, of whichever kind.
 *
 * Serialised with a `kind` tag alongside the stage's own fields, so a train
 * file says what each stage is rather than relying on position.
 */
export type Stage = { "kind": "spur" } & SpurStage | { "kind": "worm" } & WormStage | { "kind": "planetary" } & PlanetaryStage;
