// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Auto } from "./Auto";
import type { FaceSources } from "./FaceSources";
import type { Overrides } from "./Overrides";

/**
 * One gear of a stage.
 *
 * Note what is *absent*: module, pressure angle and helix angle live on the
 * stage, because they are shared.
 */
export type StageGear = { teeth: number, 
/**
 * The shift, and who decides it: **automatic means the stage does**, not
 * that undercut does. What it resolves to when nothing else constrains it
 * is [`StageGear::no_undercut`]'s business.
 */
profile_shift: Auto<number>, 
/**
 * **The shift may not go below the least that clears undercut.**
 *
 * A constraint rather than a source, which is what lets it combine with
 * everything else: it bounds a shift a designer typed, a shift the stage
 * solved from a centre distance or a crank offset, and a shift the
 * efficiency search chose, all in the same words.
 *
 * The bound is the **true** minimum from [`minimum_profile_shift`], which
 * on a comfortable tooth count is negative — so a deliberate negative
 * shift is left alone and only a genuinely undercut one is raised. That is
 * deliberate: negative shift is a decision about centre distance or
 * balance, and this is a question about undercut. Where the *stage* is
 * choosing and nothing else decides, the answer is instead
 * [`automatic_profile_shift`] — the same bound taken no lower than zero,
 * because a shift chosen for no reason should not thin a tooth that needed
 * no help.
 *
 * Off, the gear may undercut, and the searches stop asking
 * ([`crate::auto::member_is_buildable`]).
 *
 * **Meaningless on a ring**, whose flank is its shaper's rather than a
 * rack's, and which is never asked — see `member_is_buildable`.
 */
no_undercut: boolean, 
/**
 * Depth, in modules, at which the undercut question is asked.
 *
 * **Automatic is the gear's own dedendum**, which makes this ask the same
 * question the profile generator answers: *is the flank undercut at all?*
 * A fixed 1 module — the classical rule, and what this used to default to —
 * asks a narrower one, *is it undercut within a module of depth?*, and the
 * two have different answers: at α = 20° with a sharp rack they part at 18
 * teeth and 22 (docs/reference.md#automatic-values). Following the dedendum rather than naming a number
 * also means a gear cut shallower is asked about the depth it actually has.
 */
working_depth: Auto<number>, 
/**
 * Automatic uses [`addendum_for_tip_width`] at `min_tip_width`.
 */
addendum: Auto<number>, 
/**
 * Minimum transverse tooth tip width, mm.
 */
min_tip_width: number, dedendum: number, root_radius: number, 
/**
 * Automatic takes the larger of the enabled minimums below.
 */
face_width: Auto<number>, 
/**
 * Which of the four ratings an automatic face width is sized from.
 */
face_sources: FaceSources, 
/**
 * Name of a material in the library.
 */
material: string, 
/**
 * Properties replaced for this gear only. Empty means "as the library
 * says" — see [`Overrides`].
 */
material_overrides: Overrides, };
