// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HulaResult } from "./HulaResult";
import type { PairResult } from "./PairResult";
import type { PlanetaryResult } from "./PlanetaryResult";

/**
 * What a stage produced, of whichever kind.
 *
 * **Each shape keeps its own result** — a pair's, a set's, a hula stage's —
 * and the two pair kinds share one. What the train needs from any of them is
 * small enough to read through the accessors below — ratio, efficiency, the
 * backlash at the output member — so the accumulation never asks what kind it
 * was, without every result having to pretend to be the same shape.
 */
export type StageResult = { "kind": "pair" } & PairResult | { "kind": "planetary" } & PlanetaryResult | { "kind": "hula" } & HulaResult;
