// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **A preset: a shape pre-assembled at sensible teeth**, offered by name
 * under its family. None is a kind — every one is a list of what sits
 * where, and a designer edits it into its neighbours afterwards — but a
 * worm is not an obvious construction from a pair and a Wolfrom is not one
 * from a planetary set, so each is a menu entry. The order here is the
 * menu's.
 */
export type StagePreset = "spur" | "idler" | "layshaft" | "worm" | "crossed" | "planetary" | "wolfrom" | "compound" | "planocentric" | "meshed_planets";
