// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanetaryResult } from "./PlanetaryResult";
import type { SpurResult } from "./SpurResult";
import type { WormResult } from "./WormResult";

/**
 * What a stage produced, of whichever kind.
 *
 * **Each kind keeps its own shape.** A worm stage has no bending stress, no
 * minimum face width from contact and two efficiencies; a spur stage has all
 * three and one. What the train needs from either is small enough to read
 * through the accessors below — ratio, efficiency, the backlash at the output
 * member — so the accumulation never asks what kind it was, without every
 * result having to pretend to be the same shape.
 */
export type StageResult = { "kind": "spur" } & SpurResult | { "kind": "worm" } & WormResult | { "kind": "planetary" } & PlanetaryResult;
