// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HulaStage } from "./HulaStage";
import type { Shape } from "./Shape";

/**
 * A stage of a geartrain, of whichever kind.
 *
 * Serialised with a `kind` tag alongside the stage's own fields, so a train
 * file says what each stage is rather than relying on position.
 *
 * **One shape, and the hula stage still beside it.** Every kind a train
 * used to have — a spur pair, a worm, a planetary set — is a tick pattern
 * of [`shape::Shape`] and is built as one through the constructors below;
 * the kind a document or a panel names is a *preset* over that shape, not
 * a second type in the core. The hula stage stays a kind until the shape
 * can size a distance from a tip bound (`geartrain-refactor-plan.md`,
 * *Phase 6*).
 */
export type Stage = { "kind": "shape" } & Shape | { "kind": "hula" } & HulaStage;
