// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Shape } from "./Shape";

/**
 * A stage of a geartrain, of whichever kind.
 *
 * Serialised with a `kind` tag alongside the stage's own fields, so a train
 * file says what each stage is rather than relying on position.
 *
 * **One shape.** Every kind a train used to have — a spur pair, a worm, a
 * planetary set, a hula stage — is a tick pattern of [`shape::Shape`] and
 * is built as one through the constructors below; the kind a document or a
 * panel names is a *preset* over that shape, not a second type in the
 * core. The enum has one variant and keeps its tag, so a document says
 * `kind = "shape"` and a stage of another nature, should one ever be
 * needed, has a place to go.
 */
export type Stage = { "kind": "shape" } & Shape;
