// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kinds a stage comes in — the tag of [`Stage`], on its own.
 */
export type StageKind = "spur" | "worm" | "planetary" | "hula";
