// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Auto } from "./Auto";
import type { Overrides } from "./Overrides";

/**
 * One gear of a stage.
 *
 * Note what is *absent*: module, pressure angle and helix angle live on the
 * stage, because they are shared.
 */
export type StageGear = { teeth: number, 
/**
 * Automatic uses [`minimum_profile_shift`] at `working_depth`.
 */
profile_shift: Auto<number>, 
/**
 * Depth, in modules, at which the undercut question is asked.
 *
 * **Automatic is the gear's own dedendum**, which makes this ask the same
 * question the profile generator answers: *is the flank undercut at all?*
 * A fixed 1 module — the classical rule, and what this used to default to —
 * asks a narrower one, *is it undercut within a module of depth?*, and the
 * two have different answers: at α = 20° with a sharp rack they part at 18
 * teeth and 22 (docs/reference.md#automatic-values). Following the dedendum rather than naming a number
 * also means a gear cut shallower is asked about the depth it actually has.
 */
working_depth: Auto<number>, 
/**
 * Automatic uses [`addendum_for_tip_width`] at `min_tip_width`.
 */
addendum: Auto<number>, 
/**
 * Minimum transverse tooth tip width, mm.
 */
min_tip_width: number, dedendum: number, root_radius: number, 
/**
 * Automatic takes the larger of the enabled minimums below.
 */
face_width: Auto<number>, auto_face_from_bending: boolean, auto_face_from_contact: boolean, 
/**
 * Name of a material in the library.
 */
material: string, 
/**
 * Properties replaced for this gear only. Empty means "as the library
 * says" — see [`Overrides`].
 */
material_overrides: Overrides, };
