// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberName } from "./MemberName";
import type { PortSpec } from "./PortSpec";

/**
 * **A stage's ports and its conventional holds**, so a panel can offer
 * exactly the shafts a train may constrain or couple — read from the
 * stage's own wiring rather than written into the front end a second time.
 */
export type StagePorts = { ports: Array<PortSpec>, 
/**
 * What each member is — sun, planet, ring, worm, wheel or a gear by
 * its number — read off the shape by the one rule
 * ([`super::shape::Shape::member_names`]), so a panel names a member
 * as the harness does without deriving it a second time.
 */
members: Array<MemberName>, 
/**
 * **The members that share a normal module** — the mesh graph's
 * connected components ([`super::shape::Shape::module_groups`]) — so a
 * panel offers one box per group and writes it to every member in it,
 * rather than one per member with nothing tying them.
 */
module_groups: Array<Array<number>>, };
