// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberName } from "./MemberName";
import type { PortSpec } from "./PortSpec";
import type { StageFamily } from "./StageFamily";

/**
 * **A stage's ports and its conventional holds**, so a panel can offer
 * exactly the bodies a train may constrain or share — read from the
 * stage's own wiring rather than written into the front end a second time.
 */
export type StagePorts = { ports: Array<PortSpec>, 
/**
 * What each member is — sun, planet, ring, worm, wheel or a gear by
 * its number — read off the shape by the one rule
 * ([`super::shape::Shape::member_names`]), so a panel names a member
 * as the harness does without deriving it a second time.
 */
members: Array<MemberName>, 
/**
 * **The mesh groups** — the mesh graph's connected components
 * ([`super::shape::Shape::mesh_groups`]), the members a run of meshes
 * joins — so a panel offers one module and one pressure angle per
 * group and writes them to every member in it, and deals the cards a
 * group to a row.
 */
mesh_groups: Array<Array<number>>, 
/**
 * **The family the shape reads as** ([`super::shape::Shape::family`]),
 * which decides the card's structural buttons and its chip — the
 * core's reading, so the panel does not derive it a second time.
 */
family: StageFamily, };
