// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **A piece of the graph a designer can select**, by the graph's index —
 * a body by its number — or the train, where nothing is.
 */
export type Target = "train" | { "member": number } | { "mesh": number } | { "body": number } | { "axis": number } | { "distance": number } | { "coupling": number };
