// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Exact } from "./Exact";

/**
 * One term of a body's speed in a family: so many turns per turn of a
 * body the conditions left free.
 */
export type Term = { per: number, coefficient: Exact, };
