// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Exact } from "./Exact";
import type { ShaftRef } from "./ShaftRef";

/**
 * One term of a shaft's speed in a family: so many turns per turn of a
 * shaft the conditions left free.
 */
export type Term = { per: ShaftRef, coefficient: Exact, };
