// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **The three ways an internal mesh's teeth can foul**, and the room the third
 * leaves.
 *
 * An external pair has none of them: its two members curve opposite ways, so a
 * tip meets a flank where the teeth mesh and nowhere else, and the one question
 * left is whether the tips bottom out — which is a radial comparison every
 * mesh already makes ([`crate::mesh::Mesh::bottom_clearance`]). An internal
 * pair's members curve the *same* way, and that opens three more:
 *
 * - the pinion's tip reaching past where the ring's flank ends, into the fillet
 *   its shaper left (**trochoid**);
 * - the ring's tip reaching below where the pinion's flank ends, or not
 *   reaching its involute at all (**involute**) — the one a **full-depth**
 *   internal pair fails as a matter of course, which is why internal gears are
 *   not built full-depth (`crate::ring::mesh_with`);
 * - and the tips fouling **away from the line of action** entirely (**tip**),
 *   which the first two cannot see: they ask what happens where the teeth mesh,
 *   and this asks whether two teeth try to occupy the same place somewhere
 *   else. It is what decides a small tooth difference, where the tip circles
 *   cross far from the line of centres and the mesh itself is perfectly
 *   conjugate.
 *
 * # Why it is on the mesh report
 *
 * It was a hula stage's, in four fields of its own, and the epicyclic set with
 * the same internal mesh in it reported nothing — so a designer was told
 * whether the teeth foul or not according to which stage kind they had picked.
 * The set's shipped proportions fail the involute question and had never said
 * so. *A constraint belongs to the mesh*, and so does what it found: a ring's
 * tip is the mesh's business wherever the ring is.
 */
export type TipRoom = { 
/**
 * The pinion's tip reaches past where the ring's flank ends.
 */
trochoid_interference: boolean, 
/**
 * The ring's tip reaches below where the pinion's flank ends.
 */
involute_interference: boolean, 
/**
 * The tips foul away from the line of action.
 */
tip_interference: boolean, 
/**
 * How much room the tips have where their circles cross, as an angle of
 * **pinion** rotation, degrees. Negative is the overlap, and infinite where
 * the tip circles do not cross at all — the ordinary case, where there is
 * no place for the tips to meet.
 */
tip_margin: number, };
