// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShaftLabel } from "./ShaftLabel";
import type { ShaftRef } from "./ShaftRef";

/**
 * **One body of the train**: a port, or the shafts the couplings fix to
 * one another — a pair's output and the next pair's input are one shaft
 * with two names, and a case says one thing of it. What a load case is a
 * row of: fixed where the train holds it, and otherwise a load, a
 * reaction or free.
 */
export type TrainBody = { 
/**
 * Every shaft of it, in the order the chain runs, each with its name.
 */
shafts: Array<[ShaftRef, ShaftLabel]>, 
/**
 * Held by the train — ground under another name — so no case can say
 * anything of it.
 */
held: boolean, };
