// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaseShaft } from "./CaseShaft";
import type { Note } from "./Note";

/**
 * **What one load case comes to at the train level**: every shaft, with
 * what it is in this case and what it carries — the loads as given or
 * derived, the reactions found.
 */
export type TrainCase = { 
/**
 * Index into the train's list of load cases.
 */
case: number, 
/**
 * Every shaft of every stage, ground first, in the train's order.
 */
shafts: Array<CaseShaft>, 
/**
 * Whether the case could be solved at all: its loads decide the motion
 * and the flow. Where they do not — too few given, or nothing driving —
 * the shafts carry nothing and the notes say why.
 */
solved: boolean, 
/**
 * What the train wants read about this case: that it is short of a
 * speed or a torque, that nothing drives it, or that nothing holds it.
 */
notes: Array<Note>, };
