// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Note } from "./Note";
import type { Port } from "./Port";

/**
 * **What one load case comes to at the train level**: what reaches the far
 * end, and where — or whether — it was held.
 *
 * Facts about the shaft line, so no stage is in a position to say them.
 */
export type TrainCase = { 
/**
 * Index into the train's list of load cases.
 */
case: number, 
/**
 * The port the load is carried toward.
 */
delivered_at: Port, 
/**
 * The torque arriving there, N·m, after every loss on the way — zero
 * where a stage held the load first, or where nothing held it at all.
 */
delivered_torque: number, 
/**
 * The speed of that shaft, rpm, from the case's own speed through the
 * ratios.
 */
delivered_speed: number, 
/**
 * The stage that holds the load because it cannot be driven in the
 * load's direction, if one does. Stages beyond it carry none of it.
 */
reacted_at: number | null, 
/**
 * What the train wants read about this case: where it was held, or that
 * nothing held it.
 */
notes: Array<Note>, };
