// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Backlash } from "./Backlash";
import type { Directional } from "./Directional";
import type { StageResult } from "./StageResult";
import type { TrainCase } from "./TrainCase";

/**
 * What a train produces.
 */
export type TrainResult = { 
/**
 * The first stage's input to the last stage's output, signed — `None`
 * where the train's motion under its own constraints is a **family**
 * (a differential: a set with its ring released and only its sun
 * driven), or where the output does not turn. A family is still rated:
 * each case's loads decide its motion, and every stage rates under
 * that; what a family has none of is the no-load figures here and on
 * each stage — a ratio, an efficiency, a play — since each is read
 * under one motion.
 */
total_ratio: number | null, 
/**
 * Product of the stage efficiencies, in both drive directions — `None`
 * with the ratio.
 *
 * A train containing a self-locking stage cannot be back-driven at all, and
 * [`Directional::locked`] on this pair says so.
 */
total_efficiency: Directional<number> | null, 
/**
 * Angular backlash referred to whichever shaft is the output, degrees: the
 * last shaft driving forward, the first driving backward. `None` with
 * the ratio.
 */
backlash: Directional<Backlash> | null, 
/**
 * Every load case, in the train's order — the ones switched off too,
 * solved at the train level alone so a panel can say whether one
 * could be switched on; no stage rates a case that is off.
 */
cases: Array<TrainCase>, stages: Array<StageResult>, };
