// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PathReport } from "./PathReport";
import type { ShapeResult } from "./ShapeResult";
import type { TrainCase } from "./TrainCase";

/**
 * What a train produces.
 */
export type TrainResult = { 
/**
 * **The train's own figures, one row per path**, where its holds leave
 * it one motion: every path an enabled case uses, from each of its
 * loads to each of its reactions, once each, in case order — the
 * headline case's first. Empty where the motion is
 * a family (a differential, an isolated stage), which is still rated:
 * each case's loads decide its motion, and every stage rates under
 * that; what a family has none of is a figure read under one motion.
 */
paths: Array<PathReport>, 
/**
 * Every load case, in the train's order — the ones switched off too,
 * solved at the train level alone so a panel can say whether one
 * could be switched on; no stage rates a case that is off.
 */
cases: Array<TrainCase>, stages: Array<ShapeResult>, };
