// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadCase } from "./LoadCase";
import type { Stage } from "./Stage";

/**
 * A whole geartrain.
 */
export type Train = { 
/**
 * Every load the train is rated for. Any number, as the stages are any
 * number — including none, which is a shaft line with nothing rated on
 * it; a case switched off is kept and takes part in nothing.
 */
load_cases: Array<LoadCase>, 
/**
 * Judge a root that is loaded on **both** flanks against the reduced
 * bending allowable.
 *
 * Off by default. A planet's root is always loaded both ways and a
 * reversing duty loads every root both ways, but what to do about it is a
 * convention that multiplies a stress — so the train asks rather than
 * assumes, and says where reversal is present and uncorrected. See
 * [`Reversal`].
 */
reversed_bending: boolean, stages: Array<Stage>, };
