// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Actuation } from "./Actuation";
import type { Stage } from "./Stage";

/**
 * A whole geartrain.
 */
export type Train = { 
/**
 * Peak input speed, rpm.
 */
input_speed: number, 
/**
 * Peak input torque, N·m.
 */
input_torque: number, actuation: Actuation, stages: Array<Stage>, };
