// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Backlash } from "./Backlash";
import type { Directional } from "./Directional";
import type { Note } from "./Note";
import type { StageResult } from "./StageResult";

/**
 * What a train produces.
 */
export type TrainResult = { 
/**
 * Product of the stage ratios.
 */
total_ratio: number, 
/**
 * Output speed, rpm — an *output*, per Q1.
 */
output_speed: number, 
/**
 * Output torque, N·m, after efficiency losses.
 */
output_torque: number, 
/**
 * Product of the stage efficiencies, in both drive directions.
 *
 * A train containing a self-locking stage cannot be back-driven at all, and
 * [`Directional::self_locking`] on this pair says so.
 */
total_efficiency: Directional<number>, 
/**
 * Angular backlash referred to whichever shaft is the output, degrees: the
 * last shaft driving forward, the first driving backward.
 */
backlash: Directional<Backlash>, 
/**
 * The operating torque as a percentage of the peak — see
 * [`Train::operating_torque_percent`] for why this is an output and not an
 * input. `None` at zero peak.
 */
operating_torque_percent: number | null, 
/**
 * What the train as a whole wants read: an input clamped against its peak,
 * and where a back-driving load is reacted. Facts about the shaft line, so
 * no stage is in a position to say them.
 */
notes: Array<Note>, stages: Array<StageResult>, };
