// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadCase } from "./LoadCase";
import type { Shape } from "./Shape";

/**
 * A whole geartrain.
 */
export type Train = { 
/**
 * Every load the train is rated for. Any number, as the stages are any
 * number — including none, which is a shaft line with nothing rated on
 * it; a case switched off is kept and takes part in nothing.
 */
load_cases: Array<LoadCase>, 
/**
 * Judge a root that is loaded on **both** flanks against the reduced
 * bending allowable.
 *
 * Off by default. A planet's root is always loaded both ways and a
 * reversing duty loads every root both ways, but what to do about it is a
 * convention that multiplies a stress — so the train asks rather than
 * assumes, and says where reversal is present and uncorrected. See
 * [`Reversal`].
 */
reversed_bending: boolean, 
/**
 * **The train as one graph** — its axes, the bodies on them, the gears
 * on those, the meshes and the distances between axes that mesh, and
 * the couplings — every preset added laid into it, a body two presets
 * share listed once on the one axis it turns about. Its parts are what
 * the stages were ([`Train::parts`]); nothing stores them.
 */
shape: Shape, 
/**
 * **The bodies held to ground**, every one stated. A preset's
 * conventional hold — a set's ring — is written here when it is
 * inserted ([`Train::push_stage`]), so a body is held exactly where
 * this says, and released by taking it out. It was a list of
 * constraints laid over each stage's conventions, which held what
 * nobody had written and needed a *free* to say otherwise.
 */
held: Array<number>, };
