// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BodyLabel } from "./BodyLabel";

/**
 * **One body of the train** as a case sees it: a port, on one stage or
 * several — a pair's output and the next pair's input are one body with
 * two ends, and a case says one thing of it. Fixed where the train holds
 * it, and otherwise a load, a reaction or free.
 */
export type TrainBody = { body: number, 
/**
 * Every stage it is a port of, in stage order, with its name there.
 */
ends: Array<[number, BodyLabel]>, 
/**
 * Held by the train — ground under another name — so no case can say
 * anything of it.
 */
held: boolean, };
