// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Basis } from "./Basis";

/**
 * One material property: its value, and how far it can be trusted.
 */
export type Value = { value: number, basis: Basis, 
/**
 * Why this number is what it is, where that is not obvious. Always present
 * on anything that is not a plain datasheet reading.
 */
note?: string | null, };
