// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an eccentric gear costs, and what it varies over.
 *
 * Every figure here is zero or degenerate for a concentric gear, which is what
 * makes it safe to report unconditionally.
 */
export type Variation = { 
/**
 * `e = m Δx`, mm — how far the tip and root envelopes are displaced.
 */
eccentricity: number, 
/**
 * How far the tip envelope departs from a true displaced circle, mm.
 *
 * The envelope is a limaçon, not a circle, and the departure has the closed
 * form `e²/2ρ`. It is what makes "nearly a shifted circle" a measurement
 * rather than a hope: 0.5 µm at `e` = 0.1 mm, 13 µm at 0.5 mm.
 */
circle_departure: number, 
/**
 * Tip radius, smallest and largest around the revolution, mm.
 */
tip_radius: [number, number], 
/**
 * Root radius, smallest and largest, mm.
 */
root_radius: [number, number], 
/**
 * Transverse tooth thickness at the reference circle, smallest and
 * largest, mm.
 */
tooth_thickness: [number, number], 
/**
 * Tooth thickness at the **base** circle, smallest and largest, mm.
 *
 * Where the eccentricity actually lives: it is the flanks that carry it,
 * and their seat is a base-circle quantity. 339 µm of spread at
 * `e` = 0.25 mm, z = 17.
 */
base_thickness: [number, number], 
/**
 * Single-flank pitch error on the **drive** flank, mm at the base circle.
 *
 * The largest departure of adjacent flank spacing from uniform. Scales as
 * `|1 − λ|`, so `λ = 1` drives it to zero — at the cost of the next one.
 */
drive_pitch_error: number, 
/**
 * The same on the **coast** flank. Scales as `|1 + λ|`.
 *
 * Reversing the drive makes these the driving flanks, which is why `λ = 1`
 * buys a one-way component: it is exactly conjugate forward and twice
 * E2's error in reverse.
 */
coast_pitch_error: number, 
/**
 * Accumulated (index) error on each flank, mm at the base circle — the
 * full swing of the departure from uniform spacing, not its tooth-to-tooth
 * difference.
 */
drive_index_error: number, 
/**
 * The same on the coast flank.
 */
coast_index_error: number, };
