// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The face width a pair of ratings asks for, at one load case.
 */
export type Widths = { 
/**
 * From bending. `None` where the section has no rating.
 */
bending: number | null, 
/**
 * From contact.
 */
contact: number, };
