// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Material } from "./Material";

/**
 * What a worm stage does to one of its members.
 */
export type WormMemberResult = { 
/**
 * Torque on this member, N·m.
 */
torque: number, 
/**
 * Rotational speed, rpm. Filled in by the train.
 */
speed: number, 
/**
 * Tooth load cycles over the duty. Filled in by the train.
 */
tooth_cycles: number, 
/**
 * The width in use, mm — the recommendation when automatic, the input
 * otherwise. For the worm this is a *length* along its axis.
 */
face_width: number, 
/**
 * What the conventional proportion asks for, mm, whether or not it is what
 * is in use. Reported always, so a hand-set width can be read against it.
 *
 * A **convention with a named source**, not a derivation, and it sizes no
 * stress in this crate — see [`proportions`].
 *
 * `None` for a crossed gear pair: the proportions describe a worm carrying
 * an enveloping wheel, and there is neither.
 */
recommended_face_width: number | null, pitch_diameter: number, 
/**
 * The material as used, after any overrides.
 */
material: Material, };
