// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cycles } from "./Cycles";
import type { Material } from "./Material";
import type { Note } from "./Note";

/**
 * What a worm stage does to one of its members.
 */
export type WormMemberResult = { 
/**
 * Torque on this member, N·m — the peak, driven forward.
 */
torque: number, 
/**
 * Torque on this member when the load drives the train backward, N·m.
 *
 * `None` when there is no such load to react: either none was entered, or
 * the train is back-drivable and so nothing upstream holds it — see
 * [`super::back_driving_torques`].
 */
back_driving_torque: number | null, 
/**
 * Rotational speed, rpm. Filled in by the train.
 */
speed: number, 
/**
 * Tooth load cycles over the duty, bending and contact. Filled in by the
 * train.
 */
tooth_cycles: Cycles, 
/**
 * The width in use, mm — the recommendation when automatic, the input
 * otherwise. For the worm this is a *length* along its axis.
 */
face_width: number, 
/**
 * What the conventional proportion asks for, mm, whether or not it is what
 * is in use. Reported always, so a hand-set width can be read against it.
 *
 * A **convention with a named source**, not a derivation, and it sizes no
 * stress in this crate — see [`proportions`].
 *
 * `None` for a crossed gear pair: the proportions describe a worm carrying
 * an enveloping wheel, and there is neither.
 */
recommended_face_width: number | null, pitch_diameter: number, 
/**
 * Guards that altered this member's tooth form, and what the rating has to
 * say about it — the two lists a `GearResult` keeps apart, kept apart here.
 *
 * **Empty for a worm stage, and that is the difference between the two
 * arrangements this type serves.** A worm is a thread and its wheel is the
 * envelope of one, so neither is cut by a rack and neither has a profile
 * shift, a dedendum or a buildable range to report. A **crossed gear pair**
 * is two helical gears: its members are rack-cut, its designer types those
 * numbers, and every other stage kind says when a cutter has eaten into a
 * flank (`docs/corrections.md`, "A gear in a geartrain never said it was
 * undercut"). This one said nothing — the same pair reported
 * `clamp.tooth_undercut` with its shafts parallel and nothing at all with
 * them crossed, because the translation into the equivalent worm stage
 * dropped the tooth form on the way.
 */
clamps: Array<Note>, notes: Array<Note>, 
/**
 * The material as used, after any overrides.
 */
material: Material, };
