// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The contact patch a worm mesh presses.
 */
export type WormContact = { 
/**
 * Peak Hertzian pressure, MPa — **the** strength figure for this stage.
 *
 * The worst of the points a rating is taken at: the pitch point, and the
 * two boundaries of single-pair contact where one tooth carries the whole
 * load. Rated at the pitch point *alone* this came out 0.7–2.2 % low.
 *
 * The relative radius peaks where the two roll lengths are equal and falls
 * away toward both ends of the zone, and the pitch point sits near that
 * peak — so it is close to the *least* severe place the mesh offers, not
 * the worst.
 *
 * The **ends** of the zone are 10–27 % worse than the pitch point, and the
 * rating deliberately does not use them: with `ε > 1` a second pair is in
 * contact there and the load is shared. Losing that sharing does push the
 * rating outward — but a face narrow enough to lose it has also cut the
 * zone's ends off, which pulls it back in, so the two effects nearly
 * cancel and the net is about a further 0.5 %.
 */
max_pressure: number, 
/**
 * What the pitch point alone would have said, MPa — the figure this
 * replaced, kept so the difference is visible rather than asserted.
 */
at_pitch_point: number, 
/**
 * Where the worst point sits on the path, mm from the pitch point.
 */
worst_position: number, 
/**
 * The patch, mm. An ellipse, not a line.
 */
patch_length: number, patch_width: number, 
/**
 * Relative curvature along the contact, 1/mm. Zero would mean line
 * contact; that it is not zero is what crossing the shafts did.
 */
curvature_along: number, 
/**
 * ...and across it.
 */
curvature_across: number, };
