// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Auto } from "./Auto";
import type { FirstMemberSizing } from "./FirstMemberSizing";
import type { WormMember } from "./WormMember";

/**
 * A crossed-axis worm stage.
 */
export type WormStage = { 
/**
 * Normal module, mm. Shared.
 */
module: number, 
/**
 * Normal pressure angle, degrees. Shared.
 */
pressure_angle: number, 
/**
 * Shaft angle, degrees. 90 is the ordinary drive.
 */
shaft_angle: number, 
/**
 * Coefficient of friction for the mesh. **Not** optional in the way it is
 * for a spur stage: a worm's whole character comes from it.
 */
sliding_friction: number, 
/**
 * Coefficient of **static** friction, for breaking away.
 *
 * Whether a drive turns at all is decided at rest and against this; how
 * well it does once turning is decided against the sliding coefficient,
 * which is lower. See [`Directional::once_moving`] — the static figure's
 * only job is the sign, and it is never itself reported as an efficiency.
 */
static_friction: number, 
/**
 * `k₁`. The wheel takes `2 − k₁` by construction, as in a spur stage.
 *
 * # What it reaches, and why that is not a gap
 *
 * The teeth that get **cut**, and nothing this stage reports. That is not a
 * missing model: `k₁ + k₂ = 2` means a thickness modification *moves*
 * thickness between the two members without opening the pair, so the
 * backlash it contributes is **exactly zero** — structurally, not
 * approximately. docs/reference.md#crossed-axes used to record this as something a crossed stage
 * could not yet answer for want of the normal-plane play; that play is
 * derived now (docs/reference.md#centre-distance-and-backlash), and the answer it gives is zero.
 *
 * It is offered because a designer specifying this pair is specifying those
 * parts, and a stage document that could not record them would be
 * describing a drive nobody could make.
 */
thickness_mod: number, 
/**
 * Starts on the worm.
 */
starts: number, 
/**
 * How the first member's size is fixed — the *only* thing that
 * distinguishes a worm drive from a crossed gear pair.
 */
sizing: FirstMemberSizing, 
/**
 * Teeth on the wheel.
 */
wheel_teeth: number, 
/**
 * Automatic uses the geometry's own centre distance plus `clearance`.
 */
centre_distance: Auto<number>, 
/**
 * Added to the centre distance, mm. Forced to zero when the centre
 * distance is set by hand, as in a spur stage.
 */
clearance: number, tolerance_plus: number, tolerance_minus: number, 
/**
 * Axial play of the worm, mm. The dominant source of backlash in a worm
 * drive, and one a spur stage has no equivalent of.
 */
axial_clearance: number, worm: WormMember, wheel: WormMember, };
