// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cycles } from "./Cycles";
import type { GearResult } from "./GearResult";
import type { Material } from "./Material";

/**
 * What a worm stage does to one of its members.
 */
export type WormMemberResult = { 
/**
 * Torque on this member, N·m — the peak, driven forward.
 */
torque: number, 
/**
 * Torque on this member when the load drives the train backward, N·m.
 *
 * `None` when there is no such load to react: either none was entered, or
 * the train is back-drivable and so nothing upstream holds it — see
 * [`super::back_driving_torques`].
 */
back_driving_torque: number | null, 
/**
 * Rotational speed, rpm. Filled in by the train.
 */
speed: number, 
/**
 * Tooth load cycles over the duty, bending and contact. Filled in by the
 * train.
 */
tooth_cycles: Cycles, 
/**
 * The width in use, mm — the recommendation when automatic, the input
 * otherwise. For the worm this is a *length* along its axis.
 */
face_width: number, 
/**
 * What the conventional proportion asks for, mm, whether or not it is what
 * is in use. Reported always, so a hand-set width can be read against it.
 *
 * A **convention with a named source**, not a derivation, and it sizes no
 * stress in this crate — see [`proportions`].
 *
 * `None` for a crossed gear pair: the proportions describe a worm carrying
 * an enveloping wheel, and there is neither.
 */
recommended_face_width: number | null, pitch_diameter: number, 
/**
 * This member as a gear, where it **is** one.
 *
 * `Some` for a **crossed gear pair**, whose two members are ordinary
 * helical gears: rack-cut, with a profile shift, a dedendum and a root
 * round the designer typed, a buildable range those sit inside, and clamps
 * when a cutter has eaten into a flank. Everything a spur stage's member
 * reports, reported the same way and by the same type.
 *
 * `None` for a **worm stage**. A worm is a thread and its wheel is the
 * envelope of one, so neither is cut by a rack. A profile shift and an
 * admissible range are not values those members are missing — they are
 * questions that cannot be put to them, and inventing answers is what a
 * ring's "no dedendum input; it has a cutter" already refuses.
 *
 * **The two arrangements share this result type and do not share this
 * field**, which is the whole of what separates them. It was found by
 * discarding the crossed half: `solve_crossed_stage` translates a
 * `SpurStage` into an equivalent `WormStage` and the translation threw the
 * tooth form away, so a crossed pinion could not say its flank was
 * undercut where the same pinion with parallel shafts could
 * (`docs/corrections.md`).
 */
gear: GearResult | null, 
/**
 * The material as used, after any overrides.
 */
material: Material, };
