// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Backlash } from "./Backlash";
import type { CrossedMesh } from "./CrossedMesh";
import type { Directional } from "./Directional";
import type { Note } from "./Note";
import type { WormContact } from "./WormContact";
import type { WormMemberResult } from "./WormMemberResult";

/**
 * Everything a worm stage produces.
 */
export type WormResult = { 
/**
 * `z₂ / z₁` — for a worm, usually large.
 */
ratio: number, centre_distance_nominal: number, centre_distance: number, 
/**
 * Lead angle of the worm, degrees.
 */
lead_angle: number, 
/**
 * Lead angle of the wheel, degrees.
 */
wheel_lead_angle: number, 
/**
 * Helix angle of the first member, degrees — `90° − γ₁`.
 *
 * The same fact as the lead angle, from the other datum: a worm is
 * described by how far its thread advances, a gear by how far its tooth
 * leans. Both are reported because a crossed *gear* pair is entered by
 * helix angle and read that way, and converting between them on the far
 * side of the boundary is arithmetic.
 */
helix_angle: number, 
/**
 * Helix angle of the wheel, degrees — an output, per the specification.
 */
wheel_helix_angle: number, 
/**
 * Lead, mm, and axial module, mm.
 */
lead: number, axial_module: number, 
/**
 * The path of contact, for a crossed **gear** pair. `None` for a worm
 * drive: see [`CrossedMesh`].
 */
crossed: CrossedMesh | null, 
/**
 * Mesh efficiency in both drive directions.
 *
 * Unlike a parallel-axis stage these genuinely differ, and the backward one
 * can be zero or negative — that is what self-locking is, and
 * [`Directional::self_locking`] reads it rather than a separate flag that
 * could disagree.
 */
efficiency: Directional<number>, 
/**
 * The coefficient of friction at which self-locking begins.
 */
self_locking_friction: number, 
/**
 * Sliding speed at the pitch point as a multiple of the worm's pitch line
 * speed. The absolute figure needs a shaft speed, so the train fills
 * [`Self::sliding_velocity`] instead.
 */
sliding_ratio: number, 
/**
 * Sliding speed at the pitch point, mm/s. Filled in by the train.
 */
sliding_velocity: number, contact: WormContact, 
/**
 * Angular backlash at whichever member is the output in each direction,
 * degrees: the wheel driving forward, the worm driving backward. A worm
 * stage shows the gap the two ways round more starkly than any other,
 * because the ratio between the lever arms *is* the gear ratio.
 */
backlash: Directional<Backlash>, members: [WormMemberResult, WormMemberResult], notes: Array<Note>, };
