// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Auto } from "./Auto";
import type { Overrides } from "./Overrides";

/**
 * One member of a worm stage.
 *
 * Note what is *absent* against [`super::StageGear`]: no profile shift and no
 * addendum. Both belong to a generated involute profile that a worm stage does
 * not yet build.
 */
export type WormMember = { 
/**
 * Face width of the wheel, or length of the worm, mm.
 *
 * Automatic takes the recommended proportion for this member — see
 * [`proportions`], and note what those are and are not. Unlike the spur
 * stage's automatic face width, this one is **not** a minimum derived from
 * a rating: nothing here is sized against a stress, because a point
 * contact's peak pressure does not depend on the face width at all.
 */
face_width: Auto<number>, 
/**
 * Name of a material in the library.
 */
material: string, material_overrides: Overrides, };
