// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Note } from "../core/Note";
import type { Adopted } from "./Adopted";

/**
 * What adopting a member came to — the member, or why there is none, as a
 * [`Note`] the catalogue renders, for the reason [`TrainOutcome`] gives: a
 * train that will not build is an answer a designer is regularly holding,
 * and the words belong to the catalogue.
 */
export type AdoptOutcome = { adopted: Adopted | null, failure: Note | null, };
