// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GearParams } from "../core/GearParams";
import type { CutterRef } from "./CutterRef";

/**
 * What [`adopt_member`] answers.
 */
export type Adopted = { 
/**
 * The tooth as the stage cut it.
 */
params: GearParams, 
/**
 * Whether the member is a ring — cut by a pinion cutter — and so the
 * tab's *internal* kind.
 */
internal: boolean, 
/**
 * The cutter that cut it, where it is a ring.
 */
cutter: CutterRef | null, };
