// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MaterialLibrary } from "../core/MaterialLibrary";
import type { Train } from "../core/Train";

/**
 * What [`adopt_member`] is asked.
 */
export type AdoptRequest = { train: Train, 
/**
 * The library, as [`TrainRequest::materials`].
 */
materials?: MaterialLibrary, 
/**
 * The member, by the graph's index.
 */
member: number, };
