// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The pinion cutter, as the UI sends it.
 */
export type CutterRef = { teeth: number, 
/**
 * Addendum, in modules.
 */
addendum: number, 
/**
 * Tip corner round, in modules.
 */
tip_round: number, };
