// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Duty } from "../core/Duty";
import type { LoadCase } from "../core/LoadCase";
import type { Stage } from "../core/Stage";
import type { Train } from "../core/Train";
import type { GearTabDefaults } from "./GearTabDefaults";

/**
 * Everything a fresh tab starts at.
 *
 * **These are engineering numbers, so they live here rather than in
 * TypeScript.** They used to be written down in both places, and the two
 * copies drifted: the gear tab's cutter carried `tip_round = 0.38`, which is
 * the *rack's* figure. A 20-tooth shaper's tip is only 0.377 modules wide, so
 * no such tool exists — every ring the UI built was cut by a cutter that
 * generates no fillet, and the viewport drew the result as a straight-sided
 * polygon. The core's own default has been 0.2 all along, with a comment
 * saying why. See `docs/corrections.md`.
 *
 * Serving them across the boundary is what makes that class of drift
 * impossible rather than merely fixed.
 */
export type Defaults = { gear: GearTabDefaults, 
/**
 * A fresh geartrain, with one spur stage in it.
 */
train: Train, 
/**
 * One of each stage kind, for the "add stage" menu. A crossed gear pair is
 * **not** one of them — it is a spur stage with its shafts at an angle
 * (docs/reference.md#crossed-axes).
 */
spur_stage: Stage, worm_stage: Stage, planetary_stage: Stage, 
/**
 * The hula stage (docs/reference.md#the-hula-stage). Offered only behind
 * the interface's developer mode, which is a decision about what to put in
 * front of a reader rather than about the mathematics — so it crosses the
 * boundary like the other three and the front end decides who sees it.
 */
hula_stage: Stage, 
/**
 * One of each load case kind, for the "add load case" menu — and what a
 * train whose last case is removed is left with, as a stage is.
 */
ultimate_case: LoadCase, fatigue_case: LoadCase, 
/**
 * The duty a fatigue case starts with when switched to continuous —
 * the intermittent one is the fresh case's own. A number the panel seeds
 * is a number Rust decided, this one included.
 */
continuous_duty: Duty, 
/**
 * The fraction a reversed root's fatigue bending allowable is taken at.
 *
 * Crosses so the control's own note can name it. It is
 * [`REVERSED_BENDING_FRACTION`](gear_core::material::REVERSED_BENDING_FRACTION)
 * and nothing else — a number the interface shows is a number Rust decided,
 * this one included.
 */
reverse_loading_coefficient: number, };
