// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Train } from "../core/Train";
import type { GearTabDefaults } from "./GearTabDefaults";
import type { PresetEntry } from "./PresetEntry";
import type { PresetFamilyEntry } from "./PresetFamilyEntry";

/**
 * Everything a fresh tab starts at.
 *
 * **These are engineering numbers, so they live here rather than in
 * TypeScript.** They used to be written down in both places, and the two
 * copies drifted: the gear tab's cutter carried `tip_round = 0.38`, which is
 * the *rack's* figure. A 20-tooth shaper's tip is only 0.377 modules wide, so
 * no such tool exists — every ring the UI built was cut by a cutter that
 * generates no fillet, and the viewport drew the result as a straight-sided
 * polygon. The core's own default has been 0.2 all along, with a comment
 * saying why. See `docs/corrections.md`.
 *
 * Serving them across the boundary is what makes that class of drift
 * impossible rather than merely fixed.
 */
export type Defaults = { gear: GearTabDefaults, 
/**
 * A fresh geartrain, with one spur pair in it.
 */
train: Train, 
/**
 * **One of each preset, for the add menu**, in the menu's order and
 * each under its family — the core's list ([`Preset::ALL`]), so a
 * preset is a variant there and a row here, never a field. A crossed
 * pair is one of them for the menu's sake: it is a spur pair with its
 * shafts at an angle (docs/reference.md#crossed-axes), and a worm is a
 * distance marked as one, and neither is obvious to build from a pair.
 */
presets: Array<PresetEntry>, 
/**
 * The three families the menu groups them under, in order, each
 * with the key of its name — the core's list ([`PresetFamily::ALL`]).
 */
families: Array<PresetFamilyEntry>, 
/**
 * The fraction a reversed root's fatigue bending allowable is taken at.
 *
 * Crosses so the control's own note can name it. It is
 * [`REVERSED_BENDING_FRACTION`](gear_core::material::REVERSED_BENDING_FRACTION)
 * and nothing else — a number the interface shows is a number Rust decided,
 * this one included.
 */
reverse_loading_coefficient: number, };
