// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Stage } from "../core/Stage";
import type { Train } from "../core/Train";
import type { GearTabDefaults } from "./GearTabDefaults";

/**
 * Everything a fresh tab starts at.
 *
 * **These are engineering numbers, so they live here rather than in
 * TypeScript.** They used to be written down in both places, and the two
 * copies drifted: the gear tab's cutter carried `tip_round = 0.38`, which is
 * the *rack's* figure. A 20-tooth shaper's tip is only 0.377 modules wide, so
 * no such tool exists — every ring the UI built was cut by a cutter that
 * generates no fillet, and the viewport drew the result as a straight-sided
 * polygon. The core's own default has been 0.2 all along, with a comment
 * saying why. See `docs/corrections.md`.
 *
 * Serving them across the boundary is what makes that class of drift
 * impossible rather than merely fixed.
 */
export type Defaults = { gear: GearTabDefaults, 
/**
 * A fresh geartrain, with one spur stage in it.
 */
train: Train, 
/**
 * One of each stage kind, for the "add stage" menu. Three, as the
 * specification lists them: a crossed gear pair is **not** a fourth — it is
 * a spur stage with its shafts at an angle (docs/reference.md#crossed-axes).
 */
spur_stage: Stage, worm_stage: Stage, planetary_stage: Stage, 
/**
 * The fraction a reversed root's cyclic bending allowable is taken at.
 *
 * Crosses so the control's own note can name it. It is
 * [`REVERSED_BENDING_FRACTION`](gear_core::material::REVERSED_BENDING_FRACTION)
 * and nothing else — a number the interface shows is a number Rust decided,
 * this one included.
 */
reverse_loading_coefficient: number, };
