// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A case's duty switched, seeded as a fresh case's is.
 */
export type DutyEdit = { 
/**
 * The case, by index.
 */
case: number, 
/**
 * Intermittent, or continuous.
 */
intermittent: boolean, };
