// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Note } from "../core/Note";
import type { Train } from "../core/Train";

/**
 * What [`edit_train`] answers: the train edited, or as it was with the
 * reason the edit was refused.
 */
export type EditAnswer = { train: Train, 
/**
 * **A refusal a designer can reach is an answer, not a throw**: the
 * note of why, which the panel says beside the verb. `None` where the
 * edit was made.
 */
refused: Note | null, };
