// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Train } from "../core/Train";
import type { TrainEdit } from "./TrainEdit";

/**
 * What [`edit_train`] is asked.
 */
export type EditRequest = { train: Train, edit: TrainEdit, };
