// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CentreProfile } from "../core/CentreProfile";
import type { Note } from "../core/Note";
import type { PerToothClamps } from "../core/PerToothClamps";
import type { Ranges } from "../core/Ranges";
import type { Variation } from "../core/Variation";
import type { ClassRef } from "./ClassRef";
import type { Maybe } from "./Maybe";
import type { PinsOut } from "./PinsOut";
import type { SpanOut } from "./SpanOut";
import type { ToleranceOut } from "./ToleranceOut";

/**
 * Derived geometry and metrology for one gear.
 *
 * Lengths are millimetres, angles degrees, composite errors micrometres.
 */
export type GearSummary = { 
/**
 * Every bound on this gear's inputs.
 *
 * The core type is serialised directly rather than mirrored here: a mirror
 * is one more place a limit could be written down, and there is meant to be
 * exactly one. See `gear_core::auto::admissible_ranges`.
 */
ranges: Ranges, 
/**
 * The four reference circles as **radii**, mm — what a drawing is built
 * from, and what the viewport scales by.
 */
pitch_radius: number, base_radius: number, tip_radius: number, root_radius: number, 
/**
 * ...and as **diameters**, mm, which is how a gear is specified, measured
 * and called out on a drawing.
 *
 * Both are served rather than one derived from the other on the far side,
 * because doubling a number is arithmetic and arithmetic belongs here: the
 * UI displays what Rust computed and nothing else (docs/rationale.md#the-stack).
 */
pitch_diameter: number, base_diameter: number, tip_diameter: number, root_diameter: number, tooth_thickness: number, fillet_radius: number, transverse_pressure_angle: number, cutter_tip_width: number, 
/**
 * Whether **any** tooth is undercut / severed — for a concentric gear that
 * is its only tooth; for an eccentric one the short teeth can while the mean
 * does not, and `per_tooth_clamps` names which and where.
 */
undercut: boolean, severed: boolean, 
/**
 * Tool-level guards that altered the requested geometry — for an eccentric
 * gear the shared cutter's, with per-tooth clamps in `per_tooth_clamps`.
 * Empty is the normal case.
 */
clamps: Array<Note>, 
/**
 * The angular-shift amplitude in force, modules. Normally the input; when
 * the eccentricity was sized by a centre-distance throw instead, this is
 * the value solved for — the field the UI shows in place of the throw.
 */
angular_shift: number, 
/**
 * What varies around the revolution. Every field is zero for an ordinary
 * gear, so it crosses unconditionally rather than behind a flag.
 */
variation: Variation, 
/**
 * Teeth that came out other than as drawn, and why. Empty is the normal
 * case, for an ordinary gear and for a buildable eccentric one alike.
 */
per_tooth_clamps: PerToothClamps, 
/**
 * The centre distance this gear's mesh commands around a revolution.
 *
 * Needs a mate, so it is `Unavailable` with the reason when none was sent —
 * which is every concentric gear, since a concentric one commands a
 * constant and there is nothing to profile.
 */
centre_profile: Maybe<CentreProfile>, span: Maybe<SpanOut>, over_two_pins: Maybe<PinsOut>, over_three_pins: Maybe<PinsOut>, 
/**
 * Classes the standard actually covers for this gear.
 */
available_classes: Array<ClassRef>, tolerance: Maybe<ToleranceOut>, };
