// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GearParams } from "../core/GearParams";
import type { ClassRef } from "./ClassRef";
import type { MateRef } from "./MateRef";

/**
 * Everything the UI asks about one gear.
 */
export type GearRequest = { params: GearParams, 
/**
 * Pin or ball diameter for the over-pins measurement, mm.
 */
pin_diameter?: number, 
/**
 * Tolerance class, as `{ "scale": "fine" | "standard", "grade": n }`.
 */
tolerance_class?: ClassRef, 
/**
 * Maximum deviation of the exported outline from the true curve, mm.
 */
chord_tolerance?: number, 
/**
 * Include the pitch, base, tip and root circles in the DXF.
 *
 * `None` is "not stated", which is not the same as `false` — and saying so
 * in the type is what lets the generated TypeScript describe the request a
 * caller actually builds. [`REFERENCE_CIRCLES_BY_DEFAULT`] is the value.
 */
reference_circles?: boolean, 
/**
 * Depth, in modules, at which the undercut question is asked.
 *
 * `None` takes [`WORKING_DEPTH_BY_DEFAULT`]. Optional for the same reason:
 * the gear tab has no control for it, so it is genuinely absent.
 */
working_depth?: number, 
/**
 * What this gear runs against, when the answer depends on it.
 *
 * Only an **eccentric** gear has such an answer today — the centre distance
 * its mesh commands around a revolution — and a concentric one has nothing
 * that varies for a mate to be needed for. Absent means "do not ask".
 */
mate?: MateRef, 
/**
 * Size the eccentricity by the **centre-distance throw** instead of the
 * angular-shift amplitude: the amplitude is then solved so the commanded
 * centre distance's best-fit sinusoid has this half-amplitude, mm. Signed —
 * the sign carries to `angular_shift` (which end runs thick). Needs the
 * mate. Absent leaves `params.angular_shift` as the input.
 */
eccentric_throw?: number, };
