// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GearParams } from "../core/GearParams";
import type { CutterRef } from "./CutterRef";

/**
 * What a new gear tab holds. The values are the specification's, and the
 * tooth count is deliberately *not* the core's own default of 17.
 */
export type GearTabDefaults = { params: GearParams, cutter: CutterRef, 
/**
 * Pin or ball diameter for the over-pins measurement, mm.
 */
pin_diameter: number, 
/**
 * Export accuracy, mm.
 */
chord_tolerance: number, reference_circles: boolean, 
/**
 * The centre-distance throw a gear starts at when the eccentricity is
 * entered that way round and the geometry cannot seed it.
 *
 * It crosses from here for the same reason every other default does: a
 * number the application shows is a number Rust decided. The gear tab
 * carried this one in TypeScript, which is the class of drift that put a
 * rack's tip round on a shaper (`docs/corrections.md`).
 */
eccentric_throw: number, };
