// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GearParams } from "../core/GearParams";
import type { CutterRef } from "./CutterRef";

/**
 * What a new gear tab holds. The values are the specification's, and the
 * tooth count is deliberately *not* the core's own default of 17.
 */
export type GearTabDefaults = { params: GearParams, cutter: CutterRef, 
/**
 * Pin or ball diameter for the over-pins measurement, mm.
 */
pin_diameter: number, 
/**
 * Export accuracy, mm.
 */
chord_tolerance: number, reference_circles: boolean, };
