// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A language this build can be read in, as [`languages`] lists it.
 */
export type LanguageOption = { 
/**
 * The code a catalogue is asked for by.
 */
code: string, 
/**
 * The language's name in itself — what a reader looks for.
 */
name: string, 
/**
 * ...and in English, so a reader stranded in a script they cannot read
 * has something they can recognise.
 */
english: string, };
