// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The gear on the other side, as far as a commanded centre distance needs it.
 *
 * Not a whole [`GearParams`]: a mate shares this gear's module, pressure angle
 * and helix by definition — a pair that did not could not mesh — so sending
 * them again would be sending a constraint that can be broken.
 */
export type MateRef = { teeth: number, profile_shift: number, 
/**
 * The mate is a ring, and this gear runs inside it.
 */
internal: boolean, };
