// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Note } from "../core/Note";

/**
 * A value, or the reason there is not one.
 */
export type Maybe<T> = T | { unavailable: Note, };
