// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Target } from "../core/Target";
import type { Train } from "../core/Train";

/**
 * What [`offers`] is asked.
 */
export type OffersRequest = { train: Train, at: Target, };
