// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A measurement over (or between) pins.
 *
 * The nominal figure only. `metrology::OverPins` also carries the pin centre
 * and contact radii — they are how the measurement is *derived*, and how its
 * tangency is verified against the generated flank — but nothing displays
 * them, and a field on the wire that no one reads is a field that can go wrong
 * unnoticed.
 */
export type PinsOut = { nominal: number, 
/**
 * `[smallest, largest]` around the revolution — identical ends for an
 * ordinary gear, as [`SpanOut::around`].
 */
around: [number, number], };
