// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Preset } from "../core/Preset";
import type { PresetFamily } from "../core/PresetFamily";
import type { Shape } from "../core/Shape";

/**
 * A preset as the menu takes it: which, under what family, called what,
 * and the shape it lays in.
 */
export type PresetEntry = { preset: Preset, family: PresetFamily, 
/**
 * The catalogue key of its name.
 */
label: string, shape: Shape, };
