// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresetFamily } from "../core/PresetFamily";

/**
 * A family as the menu groups by it: which, and called what.
 */
export type PresetFamilyEntry = { family: PresetFamily, label: string, };
