// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MaterialLibrary } from "../core/MaterialLibrary";
import type { Train } from "../core/Train";
import type { TrainEdit } from "./TrainEdit";

/**
 * What [`preview_edit`] is asked.
 */
export type PreviewRequest = { train: Train, 
/**
 * The library, as [`TrainRequest::materials`].
 */
materials?: MaterialLibrary, edit: TrainEdit, };
