// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaseFreedom } from "../core/CaseFreedom";
import type { MaterialLibrary } from "../core/MaterialLibrary";
import type { Train } from "../core/Train";

/**
 * What [`relieve_case`] is asked.
 */
export type RelieveCaseRequest = { train: Train, 
/**
 * The library, as [`TrainRequest::materials`].
 */
materials?: MaterialLibrary, 
/**
 * The case, by index.
 */
case: number, 
/**
 * The figure just pinned, which is never the one relieved.
 */
just: CaseFreedom | null, };
