// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Figure } from "../core/Figure";
import type { Freedom } from "../core/Freedom";
import type { Shape } from "../core/Shape";

/**
 * What [`relieve`] is asked.
 */
export type RelieveRequest = { shape: Shape, 
/**
 * The freedom just pinned, which is never the one relieved.
 */
just: Freedom | null, 
/**
 * What the graph's inputs last came to ([`TrainOutcome::figures`]);
 * omitted, none.
 */
figures: Array<Figure>, };
