// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GearParams } from "../core/GearParams";
import type { CutterRef } from "./CutterRef";

/**
 * Everything the UI asks about one **internal** gear.
 *
 * A separate request from [`GearRequest`], for the reason the worm stage got a
 * separate result: a ring's answers are a different shape. It has no span or
 * over-pins measurement in the sense the metrology module means, no strength
 * rating yet, and it has something an external gear does not — the cutter that
 * shaped it, without which its fillet is undefined.
 */
export type RingRequest = { params: GearParams, 
/**
 * Pin or ball diameter for the between-pins measurement, mm.
 */
pin_diameter?: number, cutter: CutterRef, chord_tolerance?: number, reference_circles?: boolean, };
