// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Note } from "../core/Note";
import type { Maybe } from "./Maybe";
import type { PinsOut } from "./PinsOut";
import type { RootForm } from "./RootForm";

/**
 * What the UI shows for a ring.
 */
export type RingSummary = { teeth: number, transverse_module: number, transverse_pressure_angle: number, 
/**
 * Pitch, base, tip and root radii, mm. The tip is **inside** the pitch
 * circle and the root outside it. These are what the viewport draws with.
 */
pitch_radius: number, base_radius: number, tip_radius: number, root_radius: number, 
/**
 * The same four as diameters, mm — how a ring is specified and gauged.
 */
pitch_diameter: number, base_diameter: number, tip_diameter: number, root_diameter: number, 
/**
 * Radius at which the flank hands over to the fillet, mm.
 *
 * `None` when the cut generated no fillet: there is then no handover, and
 * reporting the root radius here said there was one.
 */
junction_radius: number | null, 
/**
 * How the tooth space closes.
 */
root_form: RootForm, 
/**
 * Where a drawing shades the rim out to, mm. A convention with no
 * engineering meaning — see [`gear_core::ring::Ring::rim_radius`].
 */
rim_radius: number, 
/**
 * The lowest radius this cutter can generate as an involute, mm. Below it
 * the cutter's own involute has run out.
 */
generation_limit: number, 
/**
 * Whether the tip stays above that limit.
 */
fully_generated: boolean, 
/**
 * The fewest teeth this design could have had and still cleared its own
 * base circle: `2 h_a cos β / (1 − cos α_t)`, rounded up.
 *
 * Reported because it is the constraint that actually bites on internal
 * gears, it moves with the addendum, pressure angle and helix, and a
 * designer meeting it by accident should be told which margin they are on.
 */
smallest_tooth_count: number, 
/**
 * Measurement **between** two pins or balls, the internal counterpart of
 * the gear tab's over-pins. Two pins only, and
 * [`gear_core::metrology::between_pins`] says why.
 */
between_pins: Maybe<PinsOut>, clamps: Array<Note>, };
