// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the space between two ring teeth closes.
 *
 * Three cases rather than the two a boolean allowed: a cut that generates no
 * fillet at all is not "a root arc between the fillets", and saying so put a
 * description of a fillet next to a drawing that had none.
 */
export type RootForm = "fully_filleted" | "root_arc" | "no_fillet";
