// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpanOut = { teeth_spanned: number, nominal: number, contact_radius: number, };
