// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpanOut = { teeth_spanned: number, nominal: number, contact_radius: number, 
/**
 * `[smallest, largest]` around the revolution. **The two ends are the same
 * bits for an ordinary gear**, so the front end can render a range
 * unconditionally and an evenly cut gear reads as one number with no flag
 * to check.
 */
around: [number, number], };
