// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StageFamily } from "../core/StageFamily";

/**
 * A family as the menu groups by it: which, and called what.
 */
export type StageFamilyEntry = { family: StageFamily, label: string, };
