// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Shape } from "../core/Shape";
import type { StageFamily } from "../core/StageFamily";
import type { StagePreset } from "../core/StagePreset";

/**
 * A preset as the menu takes it: which, under what family, called what,
 * and the stage it starts as.
 */
export type StagePresetEntry = { preset: StagePreset, family: StageFamily, 
/**
 * The catalogue key of its name.
 */
label: string, stage: Shape, };
