// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassRef } from "./ClassRef";

export type ToleranceOut = { class: ClassRef, tooth_to_tooth: number, total: number, };
