// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrainResult } from "../core/TrainResult";
import type { TrainFailure } from "./TrainFailure";

/**
 * What a train solve came to — an answer, or why there is none.
 *
 * **A refusal is data, not an exception.** A geartrain that cannot be built is
 * an ordinary thing for a designer to be holding halfway through an edit, and
 * the front end has to keep showing them every input that produced it. Sent
 * back as a value for that reason, and as a [`Note`] rather than a sentence
 * for the reason every other message here is one: the words belong to the
 * catalogue, and `TrainError`'s `Display` is English written in Rust —
 * which is what this used to hand over, making the failure the one thing the
 * application said in a language nobody chose.
 */
export type TrainOutcome = { result: TrainResult | null, failure: TrainFailure | null, };
