// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Figure } from "../core/Figure";
import type { MotionReport } from "../core/MotionReport";
import type { StagePorts } from "../core/StagePorts";
import type { TrainResult } from "../core/TrainResult";
import type { TrainFailure } from "./TrainFailure";

/**
 * What a train solve came to — an answer, or why there is none.
 *
 * **A refusal is data, not an exception.** A geartrain that cannot be built is
 * an ordinary thing for a designer to be holding halfway through an edit, and
 * the front end has to keep showing them every input that produced it. Sent
 * back as a value for that reason, and as a [`Note`] rather than a sentence
 * for the reason every other message here is one: the words belong to the
 * catalogue, and `TrainError`'s `Display` is English written in Rust —
 * which is what this used to hand over, making the failure the one thing the
 * application said in a language nobody chose.
 */
export type TrainOutcome = { result: TrainResult | null, failure: TrainFailure | null, 
/**
 * **What each stage's constrainable inputs came to**, one list per
 * stage, by the name relief knows them by — what a box relief turns
 * given is seeded from ([`relieve_stage`]). Beside the result rather
 * than inside it because it is the *inputs'* names lined up against the
 * result's figures, which the core does in one place
 * (`StageResult::figure`) and the panel need not know at all: it hands
 * this list back with the stage, and never learns which field is which.
 */
figures: Array<Array<Figure>>, 
/**
 * **Every stage's ports**, with the label the panel names each by — so a
 * designer is offered exactly the bodies a train may hold, drive or
 * couple, read from the stage's wiring rather than written into the front
 * end a second time. Present on success and failure alike: it needs no
 * geometry.
 */
topology: Array<StagePorts>, 
/**
 * **The train's motion** — exact ratios, every body's speed, mobility —
 * present whenever the tooth counts and topology give one, which is
 * whether or not the geometry solved. A train mid-edit whose stage will
 * not close still turns, and this is what says at what.
 */
motion: MotionReport | null, };
