// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Figure } from "../core/Figure";
import type { FlowRow } from "../core/FlowRow";
import type { Groupings } from "../core/Groupings";
import type { MemberName } from "../core/MemberName";
import type { Part } from "../core/Part";
import type { PortBody } from "../core/PortBody";
import type { TrainResult } from "../core/TrainResult";
import type { TrainFailure } from "./TrainFailure";

/**
 * What a train solve came to — an answer, or why there is none.
 *
 * **A refusal is data, not an exception.** A geartrain that cannot be built is
 * an ordinary thing for a designer to be holding halfway through an edit, and
 * the front end has to keep showing them every input that produced it. Sent
 * back as a value for that reason, and as a [`Note`] rather than a sentence
 * for the reason every other message here is one: the words belong to the
 * catalogue, and `TrainError`'s `Display` is English written in Rust —
 * which is what this used to hand over, making the failure the one thing the
 * application said in a language nobody chose.
 */
export type TrainOutcome = { result: TrainResult | null, failure: TrainFailure | null, 
/**
 * **What every constrainable input of the train came to**, by the name
 * relief knows it by, indexed as the graph is — what a box relief turns
 * given is seeded from ([`relieve`]). Beside the result rather than
 * inside it because it is the *inputs'* names lined up against the
 * result's figures, which the core does in one place
 * (`TrainResult::figure`) and the panel need not know at all: it hands
 * this list back with the graph, and never learns which field is which.
 */
figures: Array<Figure>, 
/**
 * **Every part** of the train's graph — the pieces that close apart —
 * in its own numbering with where each of its pieces is in the graph,
 * and its ports: what the panel names a part by (its meshes), and how
 * it reads what a part's meshes put on each of its bodies
 * (`TrainResult::parts`, by the part's own numbering). Present on
 * success and failure alike: it needs no geometry.
 */
parts: Array<Part>, 
/**
 * **The train's ports** — every body a case may address, in number
 * order, and whether the train holds it — present whether or not the
 * train solved, since it needs no geometry and no motion: the picker
 * offers the ones not held, and a case has a row per one.
 */
ports: Array<PortBody>, 
/**
 * **The train's centres and its axes** — two of the three groupings a
 * list shows the graph in, derived by the core; present whether or not
 * the train solved, since neither needs a solve.
 */
groupings: Groupings, 
/**
 * **Each case's flow** — the third grouping — the bodies in the order
 * the case's power reaches them, the meshes carrying it, epicyclic
 * parts as junctions and idle branches, by the graph's indices. Empty
 * where the train did not solve.
 */
flows: Array<Array<FlowRow>>, 
/**
 * **What each gear is**, read off the whole graph — sun, planet, ring,
 * worm, wheel, or a gear by its number — by the graph's index.
 */
names: Array<MemberName>, 
/**
 * **The graph's mesh groups** — the gears a run of meshes joins, which
 * share one module, one pressure angle and one axial contact ratio —
 * by the graph's indices ([`gear_core::train::Shape::mesh_groups`]).
 */
mesh_groups: Array<Array<number>>, };
