// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Note } from "../core/Note";

/**
 * Why a train has no answer, and where.
 */
export type TrainFailure = { 
/**
 * The message, as a key and its already-formatted values.
 */
note: Note, 
/**
 * Which part could not be built, **numbered from one**, in the order
 * `parts` deals them — the panel names it by its meshes. `None`
 * where the fault is the train's own rather than any one part's — an
 * empty train, say.
 */
part: number | null, };
