// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaseKind } from "../core/CaseKind";
import type { Edit } from "../core/Edit";

/**
 * One edit [`edit_train`] and [`preview_edit`] make.
 */
export type TrainEdit = { "graph": Edit } | { "add_case": CaseKind } | { "duty": { case: number, intermittent: boolean, } };
