// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Note } from "../core/Note";

/**
 * Why a train has no answer, and where.
 */
export type TrainFailure = { 
/**
 * The message, as a key and its already-formatted values.
 */
note: Note, 
/**
 * Which stage could not be built, **numbered from one** as the panel
 * numbers them. `None` where the fault is the train's own rather than any
 * one stage's — an empty train, say.
 */
stage: number | null, };
