// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MaterialLibrary } from "../core/MaterialLibrary";
import type { Train } from "../core/Train";

/**
 * A geartrain, plus optionally the material library to rate it against.
 */
export type TrainRequest = { train: Train, 
/**
 * The library to use. Omitted means the one the tool ships with, which is
 * the common case — the UI only sends this once the user has imported or
 * edited a library of their own.
 */
materials?: MaterialLibrary, };
