#!/usr/bin/env bash
# The generated TypeScript is up to date with the Rust it was generated from.
#
# `web/src/wire` is written by `ts-rs` from the `#[derive(TS)]` on each type that
# crosses the WebAssembly boundary. Committing it is what lets the front end
# typecheck without a Rust build in the loop — but a committed generated file is
# a *third* copy of the boundary, and a stale one drifts exactly the way the
# hand-written mirror it replaced did (`docs/corrections.md`).
#
# So the check is regeneration itself: emit into a scratch directory and require
# the result to be identical. Nothing here has to know what the types are.
#
#     tools/check_bindings.sh            # exits non-zero and shows the diff
#     tools/check_bindings.sh --write    # ...or regenerate them in place
#
# One script for both directions deliberately: a check whose fix is a different
# command is a check people learn to skip, and the two could then disagree about
# what "generated" means.
set -euo pipefail

write=false
[[ "${1:-}" == "--write" ]] && write=true

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
scratch="$(mktemp -d)"
trap 'rm -rf "$scratch"' EXIT

TS_RS_EXPORT_DIR="$scratch" cargo test \
  --manifest-path "$root/Cargo.toml" \
  -p gear-core -p gear-wasm \
  --features gear-core/typescript,gear-wasm/typescript \
  export_bindings >/dev/null

# The barrel is generated too — an added type nobody re-exported is as invisible
# as a changed field, so it is rebuilt from what is on disk rather than edited.
{
  cat <<'HEADER'
// The Rust types that cross the WebAssembly boundary, written down by Rust.
//
// Generated by `ts-rs` from the `#[derive(TS)]` on each type. Regenerate with
//     tools/check_bindings.sh --write
//
// Nothing here is written by hand. `core.ts` used to carry a copy of every one
// of these, which made a renamed field in Rust a silent mismatch here rather
// than a type error — the duplicated-default fault (`docs/corrections.md`) one
// level up, and the last place the project still had it.

HEADER
  for sub in core wasm; do
    for f in "$scratch/$sub"/*.ts; do
      n="$(basename "$f" .ts)"
      echo "export type { $n } from \"./$sub/$n\";"
    done
  done
} >"$scratch/index.ts"

if $write; then
  rm -rf "$root/web/src/wire"
  cp -r "$scratch" "$root/web/src/wire"
  echo "web/src/wire regenerated"
  exit 0
fi

if ! diff -r -u "$root/web/src/wire" "$scratch"; then
  echo
  echo "web/src/wire is stale — regenerate it with:" >&2
  echo "  tools/check_bindings.sh --write" >&2
  exit 1
fi

echo "web/src/wire matches the Rust types it is generated from"
