// The Rust types that cross the WebAssembly boundary, written down by Rust.
//
// Generated by `ts-rs` from the `#[derive(TS)]` on each type. Regenerate with
//     tools/check_bindings.sh --write
//
// Nothing here is written by hand. `core.ts` used to carry a copy of every one
// of these, which made a renamed field in Rust a silent mismatch here rather
// than a type error — the duplicated-default fault (`docs/corrections.md`) one
// level up, and the last place the project still had it.

export type { Actuation } from "./core/Actuation";
export type { Arrangement } from "./core/Arrangement";
export type { Auto } from "./core/Auto";
export type { Backlash } from "./core/Backlash";
export type { Basis } from "./core/Basis";
export type { BetweenPins } from "./core/BetweenPins";
export type { Bound } from "./core/Bound";
export type { CentreProfile } from "./core/CentreProfile";
export type { Clamps } from "./core/Clamps";
export type { ContactRatios } from "./core/ContactRatios";
export type { CrossedMesh } from "./core/CrossedMesh";
export type { Cutter } from "./core/Cutter";
export type { Directional } from "./core/Directional";
export type { Family } from "./core/Family";
export type { Fillet } from "./core/Fillet";
export type { FirstMemberSizing } from "./core/FirstMemberSizing";
export type { GearParams } from "./core/GearParams";
export type { GearResult } from "./core/GearResult";
export type { Layout } from "./core/Layout";
export type { Material } from "./core/Material";
export type { MaterialLibrary } from "./core/MaterialLibrary";
export type { Measure } from "./core/Measure";
export type { MeshReport } from "./core/MeshReport";
export type { Note } from "./core/Note";
export type { Overrides } from "./core/Overrides";
export type { PerToothClamps } from "./core/PerToothClamps";
export type { PlanetResult } from "./core/PlanetResult";
export type { PlanetaryResult } from "./core/PlanetaryResult";
export type { PlanetaryShaft } from "./core/PlanetaryShaft";
export type { PlanetaryStage } from "./core/PlanetaryStage";
export type { Power } from "./core/Power";
export type { Ranges } from "./core/Ranges";
export type { ShiftRange } from "./core/ShiftRange";
export type { Sinusoid } from "./core/Sinusoid";
export type { SpurResult } from "./core/SpurResult";
export type { SpurStage } from "./core/SpurStage";
export type { Stage } from "./core/Stage";
export type { StageGear } from "./core/StageGear";
export type { StageResult } from "./core/StageResult";
export type { Train } from "./core/Train";
export type { TrainResult } from "./core/TrainResult";
export type { Value } from "./core/Value";
export type { Variation } from "./core/Variation";
export type { WormContact } from "./core/WormContact";
export type { WormMember } from "./core/WormMember";
export type { WormMemberResult } from "./core/WormMemberResult";
export type { WormResult } from "./core/WormResult";
export type { WormStage } from "./core/WormStage";
export type { ZoneLimit } from "./core/ZoneLimit";
export type { ClassRef } from "./wasm/ClassRef";
export type { CutterRef } from "./wasm/CutterRef";
export type { Defaults } from "./wasm/Defaults";
export type { GearRequest } from "./wasm/GearRequest";
export type { GearSummary } from "./wasm/GearSummary";
export type { GearTabDefaults } from "./wasm/GearTabDefaults";
export type { MateRef } from "./wasm/MateRef";
export type { Maybe } from "./wasm/Maybe";
export type { PinsOut } from "./wasm/PinsOut";
export type { RingRequest } from "./wasm/RingRequest";
export type { RingSummary } from "./wasm/RingSummary";
export type { RootForm } from "./wasm/RootForm";
export type { SpanOut } from "./wasm/SpanOut";
export type { ToleranceOut } from "./wasm/ToleranceOut";
export type { TrainRequest } from "./wasm/TrainRequest";
